apiVersion: v1
kind: Secret
metadata:
    name: gitlab-agent-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:MtzcUFFAndmwgONBRekGmDX6XQwKxaXsgpLqdugJEgzAfiTYSxNBGf/Nbwm2X7OhWxl4AQgV582bAo2R/r9ewtg=,iv:8wQP2YfzNa+9Op9Wjv71jl8ugjLP5rch81+xlQZ98cQ=,tag:kmbZtp3ZSNb3eH9dwmy6IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA4YkQ2
            MmlmY1k2VWxFVmw5bUNPc25KWEJIM3hsNGxveWhZZmtNNjdRL1NvCk96M3dwVUlr
            b2dqTDFkTDNZWnNBUzRhSWpRaGVLL09Oc0NRNUNmMzVTZWcKLS0tIHRjNUpTanRY
            ZUdCTjVUeUdZU1RCbGtSTXN1L1A3ejlaWUtlZVcwU216bjAKXgrrWTS2PJe8CBq7
            yfjXmTrrBTMsagbrq6SVpCz85b1DpXdDOj9cnxONqxNP25NLrygprIMNVte1JkF7
            PNADLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnpQRjdWR1Y0UFlwRm1r
            KzZLWWlXcXBGaWpkaHp3QTN3aTh4dHdhUjEwCkwvZXpqbVpOYTFXeTJhZ0RQOVNz
            cC9RbXc5R0ROemlDejV4MnFDRkhreXMKLS0tIHFXVmlqa2RQczRTOERHa2JZM3pS
            bEZHVEdqOWQxN2ZNdTZ3cENmaVV2WEUKuy88X3Bn3g6QrnZTopbMSf7LwvLR07FO
            gFcmuUhYs+pnJWHVzKpY5d4FfhtJZh4PalHfltMv9QFSXPXuaMPhcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBkNkNH
            OUc2VDJCNFBJMzhjWUZnM2RXbXhFYVBOS1Q4RkJRQTloYTd5OWxJClRCSWdJZzNH
            dVQ5Qzc0R3J0ZlJ4c0ppTHFPRGNyQlJUMjdBVThmVU9EeEUKLS0tIEszY1Y5enRB
            YnUyakk2enE2eTZCa3BiSXZmVzhMK1IwQmRCbkx6VVptcXcK2jzpbQI5tVq3esU/
            8n7pSKRj2gE75oOCK1UAWfSYjl7CSySX+VEvrfDjFoHC8rfaLRJ9ZeJDzGdHGmgs
            EjSIvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVmdrU0J6MzVLVnBVOUJG
            L0FjYWkyY1VibVFWNmMzMFlIUFUydzV2dFdFCnQ1cFZGSWlVdXM4amV2QkFyeWRL
            M3lqRzYzYncvUHRiOXp6VUgrZGtFSUUKLS0tIHBONEpmQnZ3RVNtT0oxR29aOGRE
            RGZYbXErS1RPWlZzOTFIa21Xam80TDAKc4lO15DzkP4MyUE2/C+h/nI6Paw/8w3a
            PUjlP9j1DywUDt9Wpsn6V9XskkY9o6lK2BLOP/AWPrNlo+iVcGY97w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T00:34:24Z"
    mac: ENC[AES256_GCM,data:XW/Z71BAxJyMUZGwvzsvn0luQ38BPCfS+UqTQi5qzHrj0lV8ZROEYe2whlXMy5G5c+T/BMVv/NFz55to0Yyr0oeU2ijnwQ9es5CS1W2+avU5jEv/2w7HnOnnrSd6F2geE41r0P46EQ7bnec14gW3OTHZxjnUAlikOwHQTojEenQ=,iv:o6tzAOxb25g6W95X8rNpHU9jk8G44/aP/d6jtlhxwpY=,tag:4wqqjoCqP4+J0nsHFxIYXA==,type:str]
    version: 3.13.1
