apiVersion: v1
kind: Secret
metadata:
    name: alloy
    namespace: alloy
type: Opaque
data:
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:FG6X3+VvqFguT3IgfXrDO9sqrTN7iP5RU9ZuN7MEwmntBgzsR+PHAZ/5BWxRs5ZdglvlFHJxbB4TDK3wi4ASzgiVN89S4GxCkGwopNSm4BBK66Y5NvjLrbPuxamolhTgH/IBL9isoKLQ4sfc+HzwEOKTBDCZ46tqgTUNPr20tUi59XOlfU+m5CSQtTgMzG7r,iv:1PI0aMAdUx6ZzGmHzP9IlA27HrGf6RxB0hwLgz664Y4=,tag:aEHIf8iNdw4Yf/YsSE3+bg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBsWURj
            ZkwxbFNQWi9FaWNVNHRGbVEyb3RHMHVyY3VkOXBEMzJzT3FQaG1VCmRneHkwNEcx
            c0VHYUlaQU5uYlRZaUtveTNISDVwMTJ3alRTQ21JZ3Vvc3cKLS0tIEVwNVI5dHVV
            VVVNTlNoRnBNaFhiZTFHc0NxcGdtQ1J3ekYzdGs3aXBIM1kKfkyu5kpSQjuIrhwV
            +3UxQeM48pU2Oxa5qkL96jpbgXEBKWZuf408BCCENEYM9SE1+VTiZs/AZQQO/GRy
            Ln7p8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXAydkhhL3dRQmdUYWNq
            Slo2NlluaGlLTnc0UlpLcFRLblg5c1lyVUZ3Ck9PWjZ3UHR2cU13Wm51cUlZSnVO
            YzZxMERsN1hndlpzZ21YS3N2Q0VzRDgKLS0tIEVtV1NFNTJjZ0plc0JsZTNiOFpi
            ZWlGS2FBa3RaalF1Z1REcWdtWVpSMkUKX4LP5pp60ApLQqB97Xy6sPS4Cb5XniWp
            vRZiXBi4LlSWCVqVPmZQCKBSK66X9ShuRIWofjtr4wW5epipmFV78A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA4OHp0
            TjZpUlBtbHkwcEtUYjdYYytLWllCYk9PNURhQWoxR0JKT1Z1WkhRCmprYWQrQ2Yw
            cjd4THFnMGtSSDFqbmd5Z2dvcU40UTNhbTQzejZPSXpoRGMKLS0tIElaVFlBMUph
            akpqZkEwdTVIV2FmTTE3SXNCUGxOamJ1N1U5UktaNEQ1WmcKbNAMAGG1BAFlES4N
            /S2nkM8UZet3lZWJvLXjxJemNbFc9CcGQ+11WpSFtm4oNI4YzTNPXS7YOuY+WYb0
            I3ZC/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ny9KY1dBNzNXZU42SmNN
            bzRRTWYrZHJDejE0dlVCR3lOUUhWVmZhMm1FCnJZM2U5cVp3Q0xlN3J0ekhUY21S
            TnVVZFJHUW9xaGF3K0UrV0Y3ZUpKcjAKLS0tIEZHazRaL0Y4YWpYUW9XTCtBS2M0
            OXNDSkxSQktpc1QzcGZ4Rml5QzY4WEEKR2QBolAJiHbUluTIDE5dtlgDdpI+2BcP
            wS0SWCSODydLLZz4uDNJUZaAJyafNWJikJ8CCW4MVQRPWYMdKjxZKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:24:45Z"
    mac: ENC[AES256_GCM,data:1Fr5Z/1GYpV4+4RPoRxOBdocWnbibKHRHeqWKdg2FfWFE4+3FQIDwSQhzd195Zu+TEhmnKThMeFKGI35nxyE7d/EurXcRBaAYB+XXq9jenScTqqakI+p2VA0z3MiCSmQ1IfGBuw278bgdxDZ8zw08Y6LC0B9VY+1UMQ2YTeXl2o=,iv:B1+d1Z352mJWYVa+nqt8AEtBMAqrMcqMpME/4uqD+Ks=,tag:CoJSw/eKa/U5ov11kdSzXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
