apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/controllers/cert-manager
  - ../../base/controllers/openebs
  - ../../base/controllers/envoy
  - ../../base/controllers/cilium
  - ../../base/controllers/node-feature-discovery
  - ../../base/controllers/intel-device-plugins-operator

patches:
  - path: ipam.yaml
