apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redmanager-generated-password
spec:
  length: 64
  allowRepeat: true
  secretKeys:
    - TRANSMISSION_PASS
    - REDMANAGER_API_KEY
    - WRTAG_WEB_API_KEY
    - ND_DEVAUTOCREATEADMINPASSWORD
