apiVersion: v1
kind: Secret
metadata:
    name: alloy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:06abK3czmlRdt6L15+ggzCnyW1pb+Rd8m21HBvVrJlku9s+pfx6z9TiSZGhMLhThEkhfZed1,iv:9OXkm/DJlgAO7ZvGn5GwQCq4+JtymKszJoZjhiGVwDE=,tag:UEAqfq1o7FROEqVsBQ3bcA==,type:comment]
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:prkM3p98zCfX2VzEcYP3/iWpKae9CNfowOMvFCxeqd9BpQaD1hcpnaPWWtdRqBDAIcmd31tHJro2k78qSqVPrOFwUkNEyDBN2ovce/QKRyQjfD0OERU9nyJM3MvPpoR1G9pRfVXAv7N60w/pKmLIwr0Ox56e0g/2XF4dh9sx9ldViRCr1Vmt7vGJwulB3UPbiokYZWMkzyTbYOrLpnEA/A==,iv:DRHl/w/7wqSEYWswu6BM4mLdA38N/zLkEWGzrkhFlMc=,tag:a9R83txDb0FrYBHWEBB7pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA3Y20y
            TDIvbkplaVFKNU45bllLZWIxL2h1VUc1dkJvcURweUVvcjlkT3k4CnErT0IxeUd0
            S3FRTC80RmFzTEp5T1E4VlZncTlKSVRaMjRRY0w5aEJwbFkKLS0tIHpPTUZibEx5
            VUtWQjd1eXRxcTBrejV2MFU5ekRtTzErVWd5aEppTExobVkKO28j0+JHW+H5Xcw7
            lJs4Kpa0259pviE57dZKBbE8RbLK32Cjygccl/zf4asZRNPWD5rTPcMY5UO8YBnP
            3UZQYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK2c4YVZxQjcvQzBxUFpO
            WmdBeGNpOEo4WUZOWkZjak5tSU93WGtRYjNFCi85M1F4bDVZb0pUYnlSMEtWbVN0
            azExQmtybmJzUUpRbjB4VlB2TWZlY3MKLS0tIHFPaTVkNTl4Q0lqLzV6WVhYRlZz
            dkttRlpLL2c3M0w0ajdlV3V0TGRabFEKK9LOJJnaN+6YMQ7Kx4sZH6hhqijfDA2R
            F03eqr1anzCBN3QkbVpPeTqaPjhyybzjljvUVDnF+LtidimfiAENRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBKZnhx
            NFpSRnNXWjdHWlhlNzd5SUxwWHprcktnNDA0UjQwVGczbjZFem5RCklKQlRaZ3lI
            bUpnb2RIL1luQkNMNUdsYWpYZEg1blVWMGJwRE5kaFg2ckkKLS0tIEtJcm5MWm9k
            aVk0L3psckhmVUFiOEk4RlJ5Q3psU2huUG43eFpwRGlYWDgKDAGymMew6P4LcrZN
            1FJebx+kxHv1fWpzt5iuvWJhoJhvyy266uFOx6mYTIfu8+TlK605WXIn92IcTEGD
            mJjBzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUx4UDk0ZFRWK0FXc2E0
            VERYbWlpNnhhdnpqeC94ZlJ0ZEdDUWlnR0JrClJJSEpnNjhXNFdDdDBzSXg2Smts
            TDkxOE5keWZLOEpDWERLeUE0WDFtMncKLS0tIHFGS2xNdXIwTnBmaUZUbjZkYy9N
            Uy9NUi9hR2s2SmY5WnJUckp6WE1EVXMKA63d0GTXhBd33L0JvNHAlYpO77EXq8rt
            4rxpbxkNp3DeqXgAW6pOTPK/LFXcuGtsrhel9pStB2ER21PEEdLhyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T22:27:11Z"
    mac: ENC[AES256_GCM,data:v0jTvAKMoLEIP6UguZg/Xfnf6Qz76kXWXZmjq2SIShW/FeP7WPGRSmqbacYyAugBoGJAPEDruOWscL2ExyqPIUM4kXYzLuEsm6KzZMgklb5jPrYIWvwoieEifjIwwsodSUHtpxXsC6AxeysMYhyDVQBggEfZ3UVqarW3HgsuZgY=,iv:yWvzSYZAMlIZ2h/H6gSw9cGTlCODWlZXEjp/HcKyS+o=,tag:MgfvH06aOsGyrwVYZsluqg==,type:str]
    version: 3.13.1
