apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: backup-creds
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-operator
  identityRef:
    name: backup
  secretRef:
    name: backup-s3-credentials
