stages:
  - publish

publish-fleet:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/fleet/**/*
      variables:
        ARTIFACT_TAG: "latest"
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/fleet"
          image_tag: "$ARTIFACT_TAG"
          manifest_path: "./kubernetes/fleet"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "fleet"
          flux_oci_namespace_name: "flux-system"

publish-cert-manager:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/cert-manager/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/cert-manager"
          manifest_path: "./kubernetes/infra/components/cert-manager"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "cert-manager"

publish-openebs:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/openebs/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/openebs"
          manifest_path: "./kubernetes/infra/components/openebs"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "openebs"

publish-envoy-gateway-system:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/envoy-gateway-system/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/envoy-gateway-system"
          manifest_path: "./kubernetes/infra/components/envoy-gateway-system"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "envoy-gateway-system"

publish-cnpg-system:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/cnpg-system/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/cnpg-system"
          manifest_path: "./kubernetes/infra/components/cnpg-system"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "cnpg-system"

publish-external-dns:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/external-dns/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/external-dns"
          manifest_path: "./kubernetes/infra/components/external-dns"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "external-dns"

publish-external-secrets:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/external-secrets/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/external-secrets"
          manifest_path: "./kubernetes/infra/components/external-secrets"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "external-secrets"

publish-keycloak:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/keycloak/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/keycloak"
          manifest_path: "./kubernetes/infra/components/keycloak"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "keycloak"

publish-alloy:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/alloy/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/alloy"
          manifest_path: "./kubernetes/infra/components/alloy"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "alloy"

publish-node-feature-discovery:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/node-feature-discovery/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/node-feature-discovery"
          manifest_path: "./kubernetes/infra/components/node-feature-discovery"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "node-feature-discovery"

publish-inteldeviceplugins-system:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/inteldeviceplugins-system/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/inteldeviceplugins-system"
          manifest_path: "./kubernetes/infra/components/inteldeviceplugins-system"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "inteldeviceplugins-system"

publish-rbac:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/rbac/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/rbac"
          manifest_path: "./kubernetes/infra/components/rbac"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "rbac"

publish-gitlab-agent:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/gitlab-agent/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/gitlab-agent"
          manifest_path: "./kubernetes/infra/components/gitlab-agent"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "infra"
          flux_oci_namespace_name: "gitlab-agent"

publish-arr:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/apps/components/arr/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/oci-artifact@0.4.1
        inputs:
          version: "0.4.1"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/apps/arr"
          manifest_path: "./kubernetes/apps/components/arr"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "apps"
          flux_oci_namespace_name: "arr"
          job_image_name: "$CI_TEMPLATE_REGISTRY_HOST/starfruit6000/fluxcd/fluxcd"

publish-seerr:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/apps/components/seerr/**/*
  parallel:
    matrix:
      - TARGET_AGENT:
          # - "starfruit6000/homelab:meddle"
          - "starfruit6000/homelab:meddle-local"
          # - "starfruit6000/homelab:animals"
          # - "starfruit6000/homelab:animals-local"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/starfruit6000/fluxcd/fluxcd@0.4.1
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/apps/seerr"
          manifest_path: "./kubernetes/apps/components/seerr"
          kubernetes_agent_reference: "$TARGET_AGENT"
          flux_oci_repo_name: "apps"
          flux_oci_namespace_name: "seerr"
