stages:
  - publish

publish-fleet:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/fleet/**/*
        - .gitlab-ci.yml
      variables:
        ARTIFACT_TAG: "latest"
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/components/fluxcd/oci-artifact@0.4.0
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/fleet"
          image_tag: "$ARTIFACT_TAG"
          manifest_path: "./kubernetes/fleet"
          skip_reconcile: true

publish-cert-manager:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/cert-manager/**/*
        - .gitlab-ci.yml
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/components/fluxcd/oci-artifact@0.4.0
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/cert-manager"
          image_tag: "$ARTIFACT_TAG"
          manifest_path: "./kubernetes/infra/components/cert-manager"
          skip_reconcile: true

publish-openebs:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/flux-d2-architecture"'
      changes:
        - kubernetes/infra/components/openebs/**/*
        - .gitlab-ci.yml
  trigger:
    forward:
      pipeline_variables: true
    include:
      - component: $CI_SERVER_FQDN/components/fluxcd/oci-artifact@0.4.0
        inputs:
          version: "0.4.0"
          registry_image_url: "oci://$CI_REGISTRY_IMAGE/infra/openebs"
          image_tag: "$ARTIFACT_TAG"
          manifest_path: "./kubernetes/infra/components/openebs"
          skip_reconcile: true
