creation_rules:
  - path_regex: sops/.*/age\.enc\.yaml$
    encrypted_regex: ".*"
    key_groups:
      - age:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb"
          - "age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m" #masterkey
  - path_regex: sops/meddle/.*\.enc\.yaml$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb"
          - "age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm"
          - "age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m" #masterkey
  - path_regex: sops/meddle-local/.*\.enc\.yaml$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb"
          - "age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n"
          - "age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m" #masterkey
