stages: [baremetal-config, build, deploy, configure]

include:
  - component: $CI_SERVER_FQDN/components/opentofu/job-templates@1.1.0
    inputs:
      version: 1.1.0

.ansible:
  image: alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
  before_script:
    - apk add --no-cache ansible bash openssh-client ansible-lint

.ansible-playbook:
  extends: .ansible
  stage: configure
  variables:
    ANSIBLE_HOST_KEY_CHECKING: False
    ANSIBLE_CONFIG: ansible.cfg
  script:
    - mkdir -p ~/.ssh
    - echo $ANSIBLE_PRIVATE_KEY | base64 -d >> ~/.ssh/id_ed25519 && chmod '600' ~/.ssh/id_ed25519
    - cd ansible
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -i $INVENTORY --extra-vars '{"environment_name":"'$ENVIRONMENT_NAME'"}' $PLAYBOOK


# configure stuff that needs to be provisioned before everything else
# eg. baremetal hosts, IdM server
ansible bare metal:
  stage: baremetal-config
  #needs: ['tofu apply baremetal']
  extends: .ansible-playbook
  variables:
    INVENTORY: inventory_baremetal.yml
    ENVIRONMENT_NAME: baremetal
  parallel:
    matrix:
      - PLAYBOOK: ['proxmox.yml', 'freeipa.yml']
  rules:
    - when: on_success

tofu plan prod:
  extends: [.opentofu:plan]
  variables:
    GITLAB_TOFU_STATE_NAME: prod
    GITLAB_TOFU_VAR_FILE: prod.tfvars
    GITLAB_TOFU_ROOT_DIR: terraform/vm/
  before_script:
    - apk add --no-cache ca-certificates
    - mkdir -p /usr/local/share/ca-certificates/
    - cp "$CUSTOM_CA" /usr/local/share/ca-certificates/custom-ca.pem
    - update-ca-certificates
  rules:
    - when: on_success

tofu apply prod:
  extends: [.opentofu:apply]
  variables:
    GITLAB_TOFU_STATE_NAME: prod
    GITLAB_TOFU_VAR_FILE: prod.tfvars
    GITLAB_TOFU_ROOT_DIR: terraform/vm/
  before_script:
    - apk add --no-cache ca-certificates
    - mkdir -p /usr/local/share/ca-certificates/
    - cp "$CUSTOM_CA" /usr/local/share/ca-certificates/custom-ca.pem
    - update-ca-certificates
  rules:
    - when: manual

ansible VM prod:
  extends: .ansible-playbook
  variables:
    INVENTORY: inventory_VMs.config
    ENVIRONMENT_NAME: prod
  parallel:
    matrix:
      - PLAYBOOK: ['speak-to-me.yml', 'breathe.yml']
  rules:
    - when: on_success
