apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest"
  components:
    - source-controller
    - source-watcher
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    size: medium
    multitenant: true
    tenantDefaultServiceAccount: flux
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: OCIRepository
    url: "oci://registry.gitlab.com/starfruit6000/homelab/fleet"
    ref: "latest"
    path: "clusters/animals-local"
  kustomize:
    patches:
      - target:
          kind: OCIRepository
          name: flux-system
        patch: |
          - op: add
            path: /spec/verify
            value:
              provider: cosign
              matchOIDCIdentity:
              - issuer: ^https://gitlab\.com$
                subject: ^https://gitlab\.com/starfruit6000/homelab//\.gitlab-ci\.yml@refs/(heads|tags)/.*$
      - target:
          kind: Kustomization
        patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: flux-sops
