apiVersion: v1
kind: Secret
metadata:
    name: gitlab-agent-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Tey5zJWHxB3htk1QZaN1tvBYrwNgVbp1jnYSGOc4iH4MKlNkW+fY5Aeuj3xYVvK8EbZF4HbV1Fsd512QL4z1UIM=,iv:/ecCZ7s8nxt03KF6fyaGaxfPJcAnd33PzVJRAWzpzPw=,tag:Qbs3TPtQeJSzm9ekQGfBng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA3Y20y
            TDIvbkplaVFKNU45bllLZWIxL2h1VUc1dkJvcURweUVvcjlkT3k4CnErT0IxeUd0
            S3FRTC80RmFzTEp5T1E4VlZncTlKSVRaMjRRY0w5aEJwbFkKLS0tIHpPTUZibEx5
            VUtWQjd1eXRxcTBrejV2MFU5ekRtTzErVWd5aEppTExobVkKO28j0+JHW+H5Xcw7
            lJs4Kpa0259pviE57dZKBbE8RbLK32Cjygccl/zf4asZRNPWD5rTPcMY5UO8YBnP
            3UZQYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK2c4YVZxQjcvQzBxUFpO
            WmdBeGNpOEo4WUZOWkZjak5tSU93WGtRYjNFCi85M1F4bDVZb0pUYnlSMEtWbVN0
            azExQmtybmJzUUpRbjB4VlB2TWZlY3MKLS0tIHFPaTVkNTl4Q0lqLzV6WVhYRlZz
            dkttRlpLL2c3M0w0ajdlV3V0TGRabFEKK9LOJJnaN+6YMQ7Kx4sZH6hhqijfDA2R
            F03eqr1anzCBN3QkbVpPeTqaPjhyybzjljvUVDnF+LtidimfiAENRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBKZnhx
            NFpSRnNXWjdHWlhlNzd5SUxwWHprcktnNDA0UjQwVGczbjZFem5RCklKQlRaZ3lI
            bUpnb2RIL1luQkNMNUdsYWpYZEg1blVWMGJwRE5kaFg2ckkKLS0tIEtJcm5MWm9k
            aVk0L3psckhmVUFiOEk4RlJ5Q3psU2huUG43eFpwRGlYWDgKDAGymMew6P4LcrZN
            1FJebx+kxHv1fWpzt5iuvWJhoJhvyy266uFOx6mYTIfu8+TlK605WXIn92IcTEGD
            mJjBzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUx4UDk0ZFRWK0FXc2E0
            VERYbWlpNnhhdnpqeC94ZlJ0ZEdDUWlnR0JrClJJSEpnNjhXNFdDdDBzSXg2Smts
            TDkxOE5keWZLOEpDWERLeUE0WDFtMncKLS0tIHFGS2xNdXIwTnBmaUZUbjZkYy9N
            Uy9NUi9hR2s2SmY5WnJUckp6WE1EVXMKA63d0GTXhBd33L0JvNHAlYpO77EXq8rt
            4rxpbxkNp3DeqXgAW6pOTPK/LFXcuGtsrhel9pStB2ER21PEEdLhyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T00:32:00Z"
    mac: ENC[AES256_GCM,data:lMShDow3HTuG1du02mr5HPO0m/9Uk+A+bkqKmtybGQunVarht6VJ69kv7Rn7HvIASmyiLA5uqPMDQnu7R38qWfnsIDR/yHftRRvoYiqdwsd6gFcOkBzJS3+WDg7KNKjkl3tU95HzUaaFCPY5Ytrmi2H3Xms8pLh69pOR30Z+Llo=,iv:vjx4VgEXIoAUOgCqDbP+3z574vt4aVZGboTiZ5CjXl0=,tag:RJsjJEZUpY4UPpV4n6AsXQ==,type:str]
    version: 3.13.1
