apiVersion: v1
kind: Secret
metadata:
    name: homelab-s3-credentials
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:3xZyRSnxJBx6tIPb2MX4ioFn4dCfl3RGBA5v7/7TGE2wW4yVF5siljtDehIrCf7XvckiC4pDxJo9CJVdPErwlA==,iv:77tc2oga4hhV8rdqchj/SXwkyDWTse9+7JfgNx9iP/0=,tag:z9FydYdUR0jnruAvdiq/gw==,type:str]
    secretKey: ENC[AES256_GCM,data:kEios6E+lGVnGRfp9fkTC3nN6J8z72Lye91IuHfez0Icdms4/fWyw2JIsE3ngxMR+lLBEEX+d68+rv+hTSG+2A==,iv:JIGm/LIutkHRODkELi0rT2SIOZxe3jYflbQd81tkugk=,tag:HCcdwTrqa3mAQwrIhQZCCw==,type:str]
    cloud: ENC[AES256_GCM,data:f5JNaBTW1ExiayuDNbnBdKTKdqd4Nwpft3MUrBAk/knBwS43pzQJwEmb0lKgD2ilB5e9i6rVCBQXqL9GxRXKbr5OU33YqVnn7JUAYyUQ2uvLtMK9ZhyuL6gbi7HwWVYDN+9yB/K2GRad9NbcTS4FqhrtS2auYItx0whMX+ULAPD1WKTvEy2CjtWC5rfmA8eeVGh3WBc40ZSoxbRSNdBnO/B5lKRbJgI4C67xiH1H78v9plXR,iv:xlckUoN9rKHY7wNfSeNypc+6pbr51UOkBUNf6MrsD2E=,tag:ZFXE4lAFEO0791LApbh0vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA2RCtP
            aEN0SUtVcmJJL21hcTZBNFBXN3QxTFpQbVVyenB1aGdJYU12WVRzCkpZNWNJOExT
            ZFdGWmVzM0RwSnRSVmxXYks4SG9vTnV3M3ZUZ1g0ZlBOeFEKLS0tIFNtMU0vS2ZS
            NzhUeWFnY0J4OHliRzZMY3lFSStxakdvSkVxOG03R1g3Tk0KfXf02LKLyydnUqHB
            +PCO0jVMIu6FUfZ19t+Bh0X7o/9KeSx8rKRjPDdyek/ZnwBpqXVwLwJRsx0MD+NR
            31QcvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUnp0YkUzZ2NKZWhsY0E4
            NzY0NXVyVjF4OCtBUHBEYXlyendHTFE2VHlzCmFSVWNnTDNLMzhuajh1bUtFeWU4
            YldKUkNTeFN4WGxxYWtqT2hwSTZETFUKLS0tIGdEU3JjZ1oxS2lnczgzbzJxRVF3
            RHNBd0RSQVlwOS9TeXUvQ1Zhb1BuRUUKaa6cJb8/Yj/jG9GeWIWH7EAmykXLuwFc
            dcNOAb/jzA/BFVF1E5mc7jVCPMXKCGGz1qpXn5JZUEtG/ZoN2Qv2Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBsTnYw
            K29uVVBpeDdqUEs2V2Mxc2R6R3JDbzRjQTJ0U0M3RGpZYWFJMGpBCjZhRGVKN05B
            SE8rYlZPSm44K1JaMm8rSzVJQ1h4bDR5SThFQWQvemJnb28KLS0tIHJaaFJzZzY2
            RkE2dkZlMXhvaUVZUEZsSUZkME90bWpueTVBNnhuc1ErRFUKxY0NKfYNZlxH6f9q
            eZ5B1RSYOYXCCwAEeXnJ2cX0pn1Ik99uuHCKDqnrxHZP2GqyEloSqJ9X+qzWGkUv
            WJM8QQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL0s4SFRGQ3pRRG9KVnVp
            THJXbk8zKzk3cjBxSWxMUDBLNjZpa2JzSjNjCkNDek9leS9YTWxHeUU1cGkyKzN0
            Um9YdTdFSk81VEE0WG1OL21GSjJOSmsKLS0tIDY3aVRtUTJ2b2s2bk50QmpTYTNC
            Tmg0WUo2S2xLSGRCdTlsaHhTbWljU2sK034d3uXey45PlQmPjZjvPbJZAaeSgn4n
            NJ1pg3MJYboAZdRJ9sknLypjlnBAJIuFP3zLqWHU5Sihdtdnoj66uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3ZLNlpCZ2ZiWHBPMnRH
            eDZIVDBhdVRoeVp2RFRiVDlHR3U5Z0tsMFM4CnlPOGRJWk54NVk4eHlGdjZuNm8r
            V2x5Q3ZxNmF2eExIOHYvT2tiYWxXOTgKLS0tIDdmblplM0gxVVZZZDM4c2VSUFo1
            M0NkU2d1cWY1RmFVYUhJSDBJRWdqZmsKBHx7EqOpupo5sW1TJPE1cdceb5iBEidZ
            p9vdp65VKv96Yo+lm/zA3DEveDW2VLdpT49sbLn13SCbJasSHK3xDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T23:08:38Z"
    mac: ENC[AES256_GCM,data:3LQCxyJ117FxCGxjMudjiKJe3mPxx9stBXUdrVWMVw8dFLNZG6liROVRne8lJpzI5IrjOGpScaOok+mY2QZUgnepLtMUnRHGuMnxagme6vKNrTPXAGlbXibcLCyih1NmM6H6bru+lLwwaZyAKy3IQB6uCqsRvjUbHhfpHh3LtN4=,iv:gbut1FHudF2pSS0+AJPEfDzqNcWwedNN2I+kKqYzMjY=,tag:0zKVs6jRoPXRPBmeXRbGZg==,type:str]
    version: 3.13.3
