apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:dTHPFC+o/CJAW+marvwZHcstXnua4kilgaDb/wcpMxBR8W94skxLzzHw1FwA+VOytMyZe9M=,iv:DT7gBQNSEvP4CPWE9r95Bi2djmL8EW9Psk4vd+9AlJY=,tag:l8hRxdDRGEyeFAJnrd2HRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBaWmNa
            UmtIMElJZmU0K3pPMGJ4cjI1RkYzeUNuN09GVW1qemF0bVNUT0J3Cis1M051UnA4
            UHVkanRNalRTZkt3WVBiMEkrVW9qZHJEeVdkK0NZUnBXZTQKLS0tIDJlbXZ4Rmp1
            SHVvWkxYVlhoc1dKLzY2R0VNcTZsL1hpdzd4Tzc4ek1OWFEKZBKt0PEOToxqdXiw
            wj4K5kGLNcnFMKYo2QhCHWl/dDFWNWSoQf+lCtkCluKagdrsXPyUuYhQhe7ICNMZ
            rqTLNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZzM5cXhTYmNsZkY2Nm9V
            OGlIQmhFOVlzb0ZiSkNkbnJuT1QwYUZyTmpZCmNvc1NpUHkwUThOM1J0aEpQOEto
            YmltTm1DNkMza1h1MWN3MlJLSkUwUmMKLS0tIExZaFFqcE44Q1NzSzF3Si9DZkVh
            TXBwY2VWRVl3VkIrOHNoRTQ4b2loakUK4/CcAEWMl8mNQbift4/PPMOozXbH+ACa
            u5TP1Kf4AxeCZqg0ALLvE0mvNNlWNgHkyxQe26qe97QznPB94KIuEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA4dXVK
            TGMyV3k1QkttSkl4NmczNGZZWndzWUJrYVRacStFS0tqSEIrVGlVCnl1ZjRXRlov
            WDYyOUg3SmVuSlVQYmM2WWVyMWg4bVJJcWxmQ2JUNWljTkEKLS0tIHc4RFNXZm5y
            NUQyQmxmQzcrYkR5eFJuRFZGWi9rZ1EvNnU5V1dEYWRNSjQK6gvBqt0aSo+qCdD6
            VJ85IA89rh8/j1qQ4ofr2c/aaOFM8R4xOz8RoLwDDGru6ZqQG/4o6QR0+uS8mf9U
            ul/waA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cDYwTnJzQms0L3A5bWxT
            Mmx2UXIyODdQVk0xY0M0MmNCMkRscWhzbnhzCkp4ejhNcHlaUVZSdyswcEhjcVVx
            YlpWK3NzZmhsVktreFVBOUhRSHVqYkUKLS0tIEpqR0Fma1p4ekhrWVFSQjViYVV6
            S3NVb245ZVBXVVpYejBNN3V3Q2FGaFkKouegMdJw/QDM3NHCMilyifGdVbDdp/kf
            vf59IvPBU6mfpCok+aRxrlPntl6PS3cDXUS0jSz7Ow5+Iyze/I1CdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T16:20:46Z"
    mac: ENC[AES256_GCM,data:8wn8neT45z3nKn71DOmJswnE5bu74yUcHEganurwHan5JMQajNCuB9F6+8ePNgfbPgE1git0o2LkbRAl5XBTyqBBpxRBxZnnT1rr/ipyoiW6XuGHC2h/dmmT6QX6wwLUhnaNCwh6zWtTiXakZ9/M7lWGvpTjysAMzKt/BD/sUo8=,iv:mkXXxBhtVKkMtrJf5ewyMoXiEkXD7EmmeKWD5992R9c=,tag:CLjKKIAycvbS2ZNLYuuWDA==,type:str]
    version: 3.13.1
