apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.31.0@sha256:ae97eb6eb4009bbbe81a754e7b6e8d33608443c1353b3a1197c55a8ff3e989fa
              tty: true
              env:
                - name: LOG_STACKTRACE
                  value: "true"
                - name: SONARR__AUTH__APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: arr-stack-static-secret
                      key: SONARR__AUTH__APIKEY
                - name: RADARR__AUTH__APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: arr-stack-static-secret
                      key: RADARR__AUTH__APIKEY
                - name: QBITTORRENT_USER
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent-secret
                      key: QBITTORRENT_USER
                - name: QBITTORRENT_PASS
                  valueFrom:
                    secretKeyRef:
                      name: qbittorrent-secret
                      key: QBITTORRENT_PASS
              volumeMounts:
                - mountPath: /app/repos
                  name: configarr-cache
                - name: config-volume
                  mountPath: /app/config/config.yml
                  subPath: config.yml

          volumes:
            - name: configarr-cache
              persistentVolumeClaim:
                claimName: configarr-cache
            - name: config-volume
              configMap:
                name: configarr
