apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7jHx/Hg1ELmD9uquWmyMEd2btuI5wb57ssAJDPyl8JEUyVyc9y9cwQ==,iv:S3D5Jeg/TBhrbCO51xzx2BUO7Aqds4d7Eek70nvLArY=,tag:XJwxLAoPGFXu0G3DhGRJlg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBVTTVm
            OUh5TkdFd0hvUXJ2eEh6OHgrODR1WStUV3VPbmlTSU5lbE0yN1Q0Ci8vdU9tb3pm
            d01LeDVHMnFZN2xPVVZuVE1Id1ZlVEhkUGcwTFdzV1VhZDAKLS0tIHU5WitPUGFJ
            d0VnRFlxR2R1ME1EM2pGWlY0OHhGdDZjZ1BzYnpadFloWUkKQOeciaK9H9KmeCOh
            zD7uWBkbw/vdQEjV/5BKb+2nSbilJ2a2nQcLCRNQ2F10P63OZ5NV4JkNSezXhvaB
            HkBWUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRUZhRjJSSGtGY0Zmc05U
            b25jTHZWdmJYWm1CWHJrK3d4cjlTbHlHdXlFCk9CQlBZQ09ESFJDOFFrR3lsNWVK
            QzlYSWo5TndxWm1jVVVZUWxNYTAyb00KLS0tIE82a1BiM3FTdGQ4ZTNXcUpoQ0p4
            eVh5RGhQT2s4cWpOeEIyWkRPOXM5TFkKtc57qcLFy5hTemsaoIOjg2GqwhwXToXt
            L88lUVRJkVe5LFL48lApbRvZvSacoPTXQPhZPExJb8brCafD2SX4ZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBRNDZT
            S0pYOTNTeHpuOEE0YWQ1elYxZFZ3R1FkakdQWHZvQnNrMVZDcGw4Ck1Vc1dPa0RW
            aGluMk9RaGdlL1hhNnp1OGlVR04xbWVsUWVwZU1jVHBwZkkKLS0tIE1JY0R2OG4r
            T25TYVNkcW1PMlQzNkprZGpYaEJ2alc5ZytVNE1hMjkyL0UKPCkr8lDwZwBl6qVE
            cJ3cKhdg8KXVkIaEVVwQbNR0RmKcRYsQ34WjTbqBUdiNVyDYTSXjiiBJYxDSQYEy
            SQBOsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocEpFNnJtQkxuUEFNRUQ2
            dVgrQi9INEtQb0svdE50NE13Z0QvbGJLb1VjCjRUV3Y3VG1obWN4Y1FxSDUrQ3lH
            SEZZS2Q5OS83SnNMZFpOdnZYekRzUE0KLS0tIEg4MFNmTGdZVEFHOGg1ME9XV0o4
            K0hJTWFYclYwQ1BPcjdDT2JUdDVQTTQKaqgs46TKmquw9UUzFCUXLaMbZxhT3DyC
            Om6c1Ldwij2JXGHEX3zsGP/5Stt3S4EuM+mDNbulV2jUeYgICXEwpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T22:20:00Z"
    mac: ENC[AES256_GCM,data:+wpmxago7Z8fyLQD27FD2G0+nxb+/Ceadpy0QkxuV7Fc4nQWu2cTLrjibZyD6g/2rpBVfA8asZCLSFCxon6MfJvwJpkWHY9EyMLctefcDL20nQDcEavXIx89sA0tNwr9nQ5TYhzQPOFFqRsaS92eBht5J3waPIFiBj7eOp4xqtw=,iv:XEF8ZSRU1g2YBRkTO1mc0EBC7DKQtWJlmqL1vzxB754=,tag:+BZvgJJ1jU2NVXGp8FY2fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
