apiVersion: v1
kind: Secret
metadata:
    name: alloy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7I3pfb2/RhzMzJgCIe3sdzsYmcXyOf/Nqmff/HcsHn4hhgWMw7TGTe/OcRgTo0JwFOzlLu9v,iv:U9dUaT/9YQpLLu+fOhgqETday2t/tM7aIdgdcWlR3Sc=,tag:pE+USSo+0e8MpRq96WT7zg==,type:comment]
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:zAbNGPm5xi75iejgX8XyG8qg0QAihM2uXSpymgAPVxRkAAbkNhoiKMpgQBz8sMhvlUGM8WwF8qAmy5Gkt28mapMVVsmiCYoSkpYl8fA6vJMfXcI83ef7tcocfqydlfgXbDipHBAgmO/iPip/LCUecOI3+1wVvY41reyUulRVDGincP9wZd5zM9f9/HSaNAO8XkRMZQ==,iv:O/ukFXOtKox10mdmMu5JTGpdN9M8F/b2N/KemfbdY2w=,tag:AujE0tUTk+LMWVQhBw5jhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA4YkQ2
            MmlmY1k2VWxFVmw5bUNPc25KWEJIM3hsNGxveWhZZmtNNjdRL1NvCk96M3dwVUlr
            b2dqTDFkTDNZWnNBUzRhSWpRaGVLL09Oc0NRNUNmMzVTZWcKLS0tIHRjNUpTanRY
            ZUdCTjVUeUdZU1RCbGtSTXN1L1A3ejlaWUtlZVcwU216bjAKXgrrWTS2PJe8CBq7
            yfjXmTrrBTMsagbrq6SVpCz85b1DpXdDOj9cnxONqxNP25NLrygprIMNVte1JkF7
            PNADLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnpQRjdWR1Y0UFlwRm1r
            KzZLWWlXcXBGaWpkaHp3QTN3aTh4dHdhUjEwCkwvZXpqbVpOYTFXeTJhZ0RQOVNz
            cC9RbXc5R0ROemlDejV4MnFDRkhreXMKLS0tIHFXVmlqa2RQczRTOERHa2JZM3pS
            bEZHVEdqOWQxN2ZNdTZ3cENmaVV2WEUKuy88X3Bn3g6QrnZTopbMSf7LwvLR07FO
            gFcmuUhYs+pnJWHVzKpY5d4FfhtJZh4PalHfltMv9QFSXPXuaMPhcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBkNkNH
            OUc2VDJCNFBJMzhjWUZnM2RXbXhFYVBOS1Q4RkJRQTloYTd5OWxJClRCSWdJZzNH
            dVQ5Qzc0R3J0ZlJ4c0ppTHFPRGNyQlJUMjdBVThmVU9EeEUKLS0tIEszY1Y5enRB
            YnUyakk2enE2eTZCa3BiSXZmVzhMK1IwQmRCbkx6VVptcXcK2jzpbQI5tVq3esU/
            8n7pSKRj2gE75oOCK1UAWfSYjl7CSySX+VEvrfDjFoHC8rfaLRJ9ZeJDzGdHGmgs
            EjSIvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVmdrU0J6MzVLVnBVOUJG
            L0FjYWkyY1VibVFWNmMzMFlIUFUydzV2dFdFCnQ1cFZGSWlVdXM4amV2QkFyeWRL
            M3lqRzYzYncvUHRiOXp6VUgrZGtFSUUKLS0tIHBONEpmQnZ3RVNtT0oxR29aOGRE
            RGZYbXErS1RPWlZzOTFIa21Xam80TDAKc4lO15DzkP4MyUE2/C+h/nI6Paw/8w3a
            PUjlP9j1DywUDt9Wpsn6V9XskkY9o6lK2BLOP/AWPrNlo+iVcGY97w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T22:27:46Z"
    mac: ENC[AES256_GCM,data:iPsruIEHQFfIM1hf2oGk8nv4rNssFLAfjH8wWYfD+V3hXwjTGEmSh2BSXEjoPiLtQKA02KcRtPBjsN9BWwx1xtrIp7yh1GrenZt7+cuNcH+4QjXQFfqRlip0azTqgQ1BnOruEuhMaYkEr1t+vF2OawzWA7R0VRhToUTbwX9e7q4=,iv:1tLf0YwEbUGrGuOW+VnQifV71ck8Bet4YzYhXsVkG30=,tag:4AWJKDcM3mGawigCAHc/kg==,type:str]
    version: 3.13.1
