---
- name: Debian - Full system upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Debian - Ensure unattended_upgrades, debconf are present
  ansible.builtin.package:
    name:
      - debconf
      - debconf-utils
      - unattended-upgrades
    state: present

- name: Debian - Configure unattended-upgrades
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: 'true'
  notify: dpkg-reconfigure unattended-upgrades
