---
- name: Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Include RedHat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Import user_access tasks
  ansible.builtin.include_tasks: user_access.yml

# not important, only QoL packages, can fail due to different names in repos
- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  ignore_errors: true
