---
- name: Set SELinux to permissive
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Add repositories
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Full system upgrade RedHat
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest
