---
- name: RedHat - Add repositories
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: RedHat - Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: RedHat - Ensure dnf-automatic timer is enabled
  ansible.builtin.systemd_service:
    name: dnf-automatic-install.timer
    enabled: true

- name: RedHat - Full system upgrade
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest
