apiVersion: v1
kind: Secret
metadata:
    name: flux-sops
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:32N2CsKjxyYR3cwUPF2BE7am/GPvy8xvgwBiYk6RV1CMjAFj/lQLu99KrxL73zJzicNBnwkVbz0g5jqTVBNrzzoyAZAe/0J/wPQ=,iv:fbW1AvKja/rwvemaS6rKKme/TNRA7gxah97jFqQmi1U=,tag:+khddlB/g+Ta5+yvXQuHqQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSB1WFJX
            M0tjY2lHd2FQVUVvQm4vTC9Ea0RIbXdNN2FQREdZdVNqcCtVL1FNCnlZZEZHMHg5
            WElocVV3bDVwOFdBQ1ZHS3ZDTnlJV3BpUDdLRnY3WVpnZTAKLS0tIGNXTFRsR3Rh
            U1pndlc1ekw0TWo3V0d0bHdNQXVaOURpUnN5VUpRbG1ZUEEK4U78rsPxSWEe9iZi
            zdSpGn00LrqWewzyumWc/mbO9IeajgTtR6iAR0b7CBJmSkugeZYiOuO26zYMrnRk
            9Pj3xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNVlLSytScUt4c05nMWFp
            Q0RBbDBMbEM0THN3Q0ZMb3kwckxtTEJzOUYwCkxOajU1L0JhekozeVR6RmtSRVdK
            bzAzOHdoSWR2RTdPMTdWYzgrSW9wdDAKLS0tIDYyQzhZdjE0WlYvMVlYTzY1djFU
            Zks1VVgrWGl6bWtqVkhINTM3ZGNTUDAKscw6h94cnPmN5aW/VThTfXkYuexfZUho
            MjqeUGmJ5UqD/BbzyikBYujuiZ6EC/iaAxnZzYvqrjVtt1HNI/u2DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T14:15:16Z"
    mac: ENC[AES256_GCM,data:0Z84bL8C2I4Gma75CtsYq6z0kO70vlJGQywqvoeXwMyzKYbRPPyFCyeQ4NR56Dv66JeJQ6k6nqV4LzQ5kJ0xxrGHP7YZEDVZAu7AfGuoVAXQVPae3PnNAF8wKguYwRW75y1UpwpGD4jDkqpaGlRlEQaGmMyNSKOtYqyG6nT2zNg=,iv:Z5ixiy1SBYGFk6e0y/JnjZoO7suDO/KUJVfp+Wt5Xus=,tag:xsfHii9GqC/xoWNYCCq19Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
