dogs:
  hosts:
    dogs-local.home.parents-basement.win:
      clevis_bindings:
        device: /dev/vda3
        servers:
          - http://192.168.122.1:7500
      zpool:
        physical_disks:
          - /dev/vdb
          - /dev/vdc
          - /dev/vdd
          - /dev/vde
          - /dev/vdf
          - /dev/vdg
        tank_keyfile_contents: foobarbaz
      cluster_name: animals-local
      flux_secret_content: "{{ lookup('community.sops.sops', 'sops/animals-local/flux-secret.enc.yaml') }}"
echoes:
  hosts:
    echoes-local.home.parents-basement.win:
      clevis_bindings:
        device: /dev/vda3
        servers:
          - http://192.168.122.1:7500
      zpool:
        physical_disks:
          - /dev/vdb
          - /dev/vdc
          - /dev/vdd
          - /dev/vde
          - /dev/vdf
          - /dev/vdg
        tank_keyfile_contents: foobarbaz
      cluster_name: meddle-local
      flux_secret_content: "{{ lookup('community.sops.sops', 'sops/meddle-local/flux-secret.enc.yaml') }}"
