dogs:
  hosts:
    dogs.home.parents-basement.win:
#      clevis_bindings:
#        device: /dev/sda3
#        servers:
#          - http://192.168.122.1:7500
#      zpool:
#        physical_disks:
#          - /dev/vdb
#          - /dev/vdc
#          - /dev/vdd
#          - /dev/vde
#          - /dev/vdf
#          - /dev/vdg
#        tank_keyfile_contents: "{{ vault_dogs_tank_keyfile }}"
#      cluster_name: animals-local
#      flux_secret_content: "{{ lookup('community.sops.sops', 'sops/animals-local/flux-secret.enc.yaml') }}"
