apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs-zfslocalpv
spec:
  interval: 1h
  url: oci://ghcr.io/openebs/charts/zfs-localpv
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "2.11.1"
    digest: sha256:22ab0e976df35410314c4090b762ec0750b9aae85ae627436e8ca11aaf1eb74a
