apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs-zfslocalpv
spec:
  interval: 1h
  url: oci://ghcr.io/openebs/charts/zfs-localpv
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "2.10.1"
    digest: sha256:ab24c12ea33d0fccfe2db6f16d778f0fc213bf31f154f09f45732532c4143d71
