---
- name: Ensure wireguard and iptables-nft are installed
  ansible.builtin.package:
    name:
      - nftables
      - wireguard-tools
    state: present

- name: Ensure /etc/wireguard/ directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Check if wireguard interface configuration file exists
  ansible.builtin.stat:
    path: '/etc/wireguard/{{ wg_interface_name }}.conf'
  register: wg_interface_conf

- name: Generate wg interface config
  ansible.builtin.template:
    dest: '/etc/wireguard/{{ wg_interface_name }}.conf'
    force: false
    mode: '0755'
    src: wg0.conf.j2
  when: not wg_interface_conf.stat.exists

- name: Start and enable wireguard service
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    enabled: true
    state: started

- name: Start and enable wireguard service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: 'wg-quick@{{ wg_interface_name }}.service'
    enabled: true
    state: started
