apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../components/prod
patches:
  - target:
      kind: HTTPRoute
      name: copyparty-public
    patch: |-
      - op: remove
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1controller
