apiVersion: v1
kind: Secret
metadata:
    name: gitlab-agent-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3dNPfw8iFaISI/sS3zCzVZbEuewqSBGxYabSP4/GXASM/5GJIRP+w4YLBs27okuJC/0rejuKTTW9N/doTyl3pnQ=,iv:SF5FMeRszQcsGTGn4rFbzO0Tpv58tsA62IPoR5YZfaE=,tag:euZVM4EKLCMKjSNx8Xvcdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBsWURj
            ZkwxbFNQWi9FaWNVNHRGbVEyb3RHMHVyY3VkOXBEMzJzT3FQaG1VCmRneHkwNEcx
            c0VHYUlaQU5uYlRZaUtveTNISDVwMTJ3alRTQ21JZ3Vvc3cKLS0tIEVwNVI5dHVV
            VVVNTlNoRnBNaFhiZTFHc0NxcGdtQ1J3ekYzdGs3aXBIM1kKfkyu5kpSQjuIrhwV
            +3UxQeM48pU2Oxa5qkL96jpbgXEBKWZuf408BCCENEYM9SE1+VTiZs/AZQQO/GRy
            Ln7p8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXAydkhhL3dRQmdUYWNq
            Slo2NlluaGlLTnc0UlpLcFRLblg5c1lyVUZ3Ck9PWjZ3UHR2cU13Wm51cUlZSnVO
            YzZxMERsN1hndlpzZ21YS3N2Q0VzRDgKLS0tIEVtV1NFNTJjZ0plc0JsZTNiOFpi
            ZWlGS2FBa3RaalF1Z1REcWdtWVpSMkUKX4LP5pp60ApLQqB97Xy6sPS4Cb5XniWp
            vRZiXBi4LlSWCVqVPmZQCKBSK66X9ShuRIWofjtr4wW5epipmFV78A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA4OHp0
            TjZpUlBtbHkwcEtUYjdYYytLWllCYk9PNURhQWoxR0JKT1Z1WkhRCmprYWQrQ2Yw
            cjd4THFnMGtSSDFqbmd5Z2dvcU40UTNhbTQzejZPSXpoRGMKLS0tIElaVFlBMUph
            akpqZkEwdTVIV2FmTTE3SXNCUGxOamJ1N1U5UktaNEQ1WmcKbNAMAGG1BAFlES4N
            /S2nkM8UZet3lZWJvLXjxJemNbFc9CcGQ+11WpSFtm4oNI4YzTNPXS7YOuY+WYb0
            I3ZC/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ny9KY1dBNzNXZU42SmNN
            bzRRTWYrZHJDejE0dlVCR3lOUUhWVmZhMm1FCnJZM2U5cVp3Q0xlN3J0ekhUY21S
            TnVVZFJHUW9xaGF3K0UrV0Y3ZUpKcjAKLS0tIEZHazRaL0Y4YWpYUW9XTCtBS2M0
            OXNDSkxSQktpc1QzcGZ4Rml5QzY4WEEKR2QBolAJiHbUluTIDE5dtlgDdpI+2BcP
            wS0SWCSODydLLZz4uDNJUZaAJyafNWJikJ8CCW4MVQRPWYMdKjxZKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T00:33:40Z"
    mac: ENC[AES256_GCM,data:1xVXT+D6qczizkuGkPuovII6bI11L5gnpf/7TBe4T/mtZflI7WKhAJK8RBLXus/PFA6m8c79MaYrJ2t0f8uaPGegAMNVjamufF54k2XFfV5sblsL2IjwPf5w9LfKRqHQ9YXS0PlE+pmkQRMx/P3bNc482zjCFcJvqJfHTsXMloU=,iv:tUqBlYBZ2cRfQvCDzH4Vbt9IKag1lj58kPSG9qNxBwQ=,tag:9W1VMhwO4eIdxo0u4J3MUg==,type:str]
    version: 3.13.1
