---
- name: Create media-server group
  ansible.builtin.group:
    name: media-server
    gid: 2137
    state: present

- name: Create media directory structure
  ansible.builtin.file:
    path: /mnt/volume/{{ item.path }}
    state: directory
    mode: '775'
    owner: root
    group: media-server
  with_community.general.filetree: media-directory-structure/
  when: item.state == 'directory'
