---
- name: Ensure /mnt/volume exists
  ansible.builtin.file:
    path: /mnt/volume
    state: directory

- name: Mount an NFS volume
  block:
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: proxmox.{{ subdomain }}.{{ domain }}:/media
        path: /mnt/volume
        state: mounted
        fstype: nfs
  rescue:
    - name: Reboot the system before retrying NFS mount
      ansible.builtin.reboot:
        msg: "Rebooting to work around NFS mount issue"
        reboot_timeout: 600

    - name: Retry NFS mount after reboot
      ansible.posix.mount:
        src: proxmox.{{ subdomain }}.{{ domain }}:/mpool/media
        path: /mnt/volume
        state: mounted
        fstype: nfs

#- name: Create media directory structure
#  ansible.builtin.file:
#    path: '/mnt/volume/{{ item.path }}'
#    state: directory
#    mode: '777'
#    owner: root
#    group: root
#  with_community.general.filetree: media-directory-structure/
#  when: item.state == 'directory'
#  loop_control:
#    label: '{{ item.path }}'
