---
- name: Ensure jelly-pod users exist
  ansible.builtin.user:
    name: jelly-pod
    uid: 1111

- name: Ensure qbit-pod users exist
  ansible.builtin.user:
    name: qbit-pod
    uid: 2222

- name: Create media directory structure
  ansible.builtin.file:
    path: '/mnt/volume/{{ item.path }}'
    state: directory
    mode: '777'
    owner: root
    group: root
  with_community.general.filetree: media-directory-structure/
  when: item.state == 'directory'
  loop_control:
    label: '{{ item.path }}'
