apiVersion: v1
kind: Secret
metadata:
    name: centralized-oidc-secret
    namespace: envoy-gateway-system
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:rPWDDS5QAmRf5X+NMOE7k53Jy5VJPAfE51Zi7PtNBhRv+fFiOpo1X/1ub6OQZpdCDc54gk4ZAFyT1TEVZZ+6rQ==,iv:roFP31VV6VDgbRVDMkgCgE0lG7wrij0/RKruIeJggyc=,tag:mz4Cv9z2RZwstHsI82qxhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBmc1Vq
            NkI4dDBZZHNWQkptSHRWRWFXaStKZlYyZHB0RXRBL05TYldTOFhJCmxKYjFkRlND
            K3FrVGdXMzh4UWpVT3BYU2I0endzM1k1R3B5YmNzeTRySHcKLS0tIGVaaHhYNG1M
            ZHRDVlY1VzNFdmkrT0R4SmVPY0VSMHE5R1I3anVld29QWm8KEig2acjaSqfCIEK5
            giFFNi86F1oD3S+piagWHvBCRj2p7OJsnzI5Ag2iP+2U2TLU/Q5PgTBeBQqbIghC
            UZjbyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZkFBWHphTy9kbkZTYlRh
            V01aZFUrYTNtOEExbkVwdkVMQk9TVHpTeEVBCmJraS83N2crbXppanJCTUZMU3dY
            bTZlSnd1T1BWMHpaR2s4QW9pdU5KN2sKLS0tIG0yZFZVV3JsWlhBOXNvczdENWxS
            cXp2S2F2YkF2UG9Ham50TVozZzRuc1UKlN+Og48ketk1eRoWux3VbHr3iN03ynRK
            iP7fO4Lz1liFafePvsfG94oh3Ev2rE+KNEhIUC9saGKS2QlTHe4fpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBMRUhy
            WU5zZk52LytJNFlhWXRkZTA3ek9HcVkyN1g3MUZmeUk4a04xbGdjCndubDNaNjNs
            VVc3M1dQSnNnMHhFRGdrRDhhSnU5YlFQN1didkJWR1Y4UWcKLS0tIC9odlRlbzFt
            S3BwaGdTbU5LUW5lUndrNFhrWm9OdlBkcnBibENjUFg3OGsKePLjCjlr+WKFan5c
            8J/6oNcqpexR3mX1UAV4waAS2NJ7/7tOoNvLJXDSlgwlz4gezOCuwWXs/BoiKiZ6
            lVfQ3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T3M4ODVjS0FaYzBsRDA5
            d2xtbW9LSXNIN1VlSmt1QWNDa1FRRnIyanpVCkcyYkUrL21FRlZ0SkV2NStxbHpi
            Y2l2bVhZWDVGYTJaajRlc2xaRmNqd2cKLS0tIDY4NU95V3RsbkIvVjJLNEN1RFhz
            RFpPTGRDa1RwcUtESmxvdzZSemtrQ00KeuAQgNFuj6WY2xjbzWXHWnpmQ8nHHWqL
            0odypDPt4EFjQG3QqKBUrD8P9CCYwVo2upajVECVgpGtcLOSOtWf7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
    encrypted_regex: ^(data|stringData|secret|value)$
    lastmodified: "2026-05-16T15:55:20Z"
    mac: ENC[AES256_GCM,data:bFZSgEAH9YpK8mwvJBjHKLUQt/Kjq3AYV565fjKCpZOcThnzAPm4Pc7ea9CqJ+oBtFX0iSivKaf41Z1cTPVWCuwDYsLB0qnA/2x5YaCV4f4p+reisN8KGqzn+GIroQc4AlCFj/Rfgg/P874qr+1GoUMp5q+iXnQJ4/fNVDLZ9GA=,iv:35f+q/2gnxTc6o3u+O7PVpN8KSBUGsiH/lqniZNBJt8=,tag:3HU6Fq88nIyOkqotEi0BTQ==,type:str]
    version: 3.13.0
