apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/configs/cert-manager
  - ../../base/configs/envoy-gateway
  - ../../base/configs/openebs
  - ../../base/configs/keycloak
  - cloudflare-secret.enc.yaml
  - eg-sso-secret.enc.yaml
  - keycloak-pv.yaml
  - realm.enc.yaml

patches:
  - path: lets-encrypt.yaml
  - path: keycloak-httproute-patch.yaml
  - path: keycloak-cr-patch.yaml
