#ENC[AES256_GCM,data:tJeLDVkiuw==,iv:qm+Ahk6EKF+H6aKxlTcAKuYJgRDnZWAtm1+H54v5xFA=,tag:JFGIKPu/5frGOLgHZOYgNA==,type:comment]
vault_luks_emergency_passphrase: ENC[AES256_GCM,data:i45Ygkr4gykR5PPpF09z3RtpvImHTm5roAwX0+qewmVFCIk3IsDaLqeuV0eZCvK3HdrKtCRG/KeQ7l5sUpc=,iv:jvhSpttk/6kviKeQ/0PISR7zKAqNqr9YfBc8mpDpq34=,tag:zgnL25vpru+rhfBtpcg19A==,type:str]
vault_admin_username: ENC[AES256_GCM,data:bc9c72J2gWn6JFXplh8=,iv:MK6zuuti2k80nJb1dimoPWFi3ft/lIiROByeCpWiA+Y=,tag:kZ3C5ZNCm1K/IYTTaFDSwA==,type:str]
vault_admin_password: ENC[AES256_GCM,data:hTSGM5IHJPO9xpAquU7Y8A==,iv:Qzd7Tt8GLj2vZTkB+VW5b2gUiDlG5sXgkC6R2kbQnkU=,tag:YH2kXkTQCM9EXPfmn6LmqQ==,type:str]
vault_admin_password_hash: ENC[AES256_GCM,data:u9nGZ6iDU6JJm4NwGRkpRhRId5bUNPGF/ndVpvgvlxKjdaYMQo/c0xHmCQgVTl/F9Fr3ZMj5+BK/puE1nlDjAoFCB6E4vKZUUEr269BwKGyQ6u0ZNtsj8DT/OULd/R8pFuPdKV6nTKgWDw==,iv:L5CYe47Ebxc3gHbCYeOgki18EBpWcHaBPY1y7gje9V0=,tag:OYcBNDWnuf9d7hYvAuQKkw==,type:str]
vault_admin_public_key: ENC[AES256_GCM,data:sUR7QZozNvv/B6s7L6U2kdB4YqrHGcsWxw/85PwDS/EBnTKFRy54qlSM8/foz4VZrg1qbYldPaRNpswC0vlYkZ7rVPkrWfZOOJn189YG9ag=,iv:YiPnPX5k+95LnySrdgRVX4/yaxLLnUlMCdgOmM/4mOA=,tag:PJgzUyyfxa0dKsqV8ivmOg==,type:str]
vault_ansible_public_key: ENC[AES256_GCM,data:JrcQ9vmJY5Od7EFt1tyr4wehPKQDGJMyBq5dY1z2YQS0UuyoBJCYtjPMdUAZ0dwIEcRiJ+vCtiyj10c3hG4RNqYfvE21cJhA0PfBKlIC7tw=,iv:6ayEsji3uFcuDgyIRee2S8y4YioJhIhU2k3aa8LuY3g=,tag:HoIJzmQwIkHK6KuXu0PY8A==,type:str]
vault_ansible_private_key: ENC[AES256_GCM,data:6RdV2DxT9UejCsNFilRVjI3h8ps/p4f48/gSc8lfew7+PPepm6zmw5MCN/3QoPuCHECsf5OYGt+k7GVLYp6x2JRYqJlpJp8iV1hhDNI9UUIiYzo2T9Tos4MEok6WUJj6DXLOl/0l+rUXwKmvFja6/n4ZoTtnTTP18+heG/PJAzQLAfeqzEzGCOR8xz0Fh2IaGGtKwwJ5Rw1ZoM/PeVhfwJIp2a4tBMsWAibPZwxI6oaLCuGfO/RGucQJ7Hl9ShSCGZ7kO0ev6uXb1kSuDNpWLzXkcn/7TpBAjNWeVD+oypKWeB6oRuIZZGa28dyXw73C5/4i3Gy/cmbXjgcO/Ucj3AHxAPNVII35UNLQc9LYknPeesBasaC1KYfrhOM40CN+XNnws/BrZ9xKv477HsCDQwWKqYR3y75ATDycoVrGX+7H8LTXrjpPzbmKRqCVFjJYW6h53kg8i3ttqafeRqTaGApkYCPJVD4A+3jfsMSUwndwmxYD9K0V2yfRU9Dr/y1cMjC/QU3ib6rJmsemeio3wOKtb84sQ9BYl/BedNY5Vk1jLQ==,iv:pfwGC5dAkPOADWga/gXdopvPgTXX/AlDLKS1KZEhDKg=,tag:NwEOOx/xdRLyWudILC3iaA==,type:str]
#ENC[AES256_GCM,data:1HbfDFpXkkfEDXA9Otk=,iv:q3bQOSoRXOuqcOc8XWVyrZ/p/1+SQwBruDe1r2zqrZw=,tag:tlAmhA55bYRjj4BkeecMNA==,type:comment]
vault_dogs_tank_keyfile: ENC[AES256_GCM,data:0o6gNVNnAUYgtRSQyapkSvkbHThPiIHgqIQpWSL8Qvc=,iv:2HKG51C2aIliDLPPsPco/3ypjX/lr8SdbBWnXhN4TxI=,tag:pg8PxSfTVPsby2R/zJXHuQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBYeVNE
            SWg5YlJ6WnZscTF2Sy9DWUJUOXlsU0pMSnh1b21vM0NwblAvam5FCjBpSldBUlJQ
            dUVnenR2aWNNRUR4NVVlVTVobFhXMnJVMGsyRUpFcG9HZGsKLS0tIHRkSjZCdStC
            bzBMaW1zWHkyQWtRNnR6bHBJZGRXS1ZKUmVxbFpWSithN1EKpHTcqD4i+ZXLq9Sx
            /SUhTmIx1fwPXmfJwDLlEvTKZgKmGM00bCKxC5vhPMXJXbHVu9CX6aNqFqdoSlXA
            hZXpfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYXdIWnJ5ei9YSWw0d29R
            aEhDMHN3cm1mcXNNaWtvQTdMd2x3NmFwbkFFCk5Ob0R2VGVrRU9KcGF1UkVzdmc2
            OGdLaHc1MEwzbnF2QWNmVDZCVlB2c28KLS0tIE92Z3Z6R0tQcXp5eGZWNStPeTlF
            NENlYVlRR3NZckdEYW94YVhGS2dPZHcKvLPUPSwAvQX/Avm6x1X2COegyVcqsrmC
            RDGHgpa0HyphsAF9m74GSaoXpi6Pi61DiHOksg3HoZG3fDIt3G15Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBQT2Y3
            Y2ROeG5taTdCbEZYNFQ2a2tBQ25PVlpnOHUrRjJqNWc2Ny9lbENvCllUOTBBWFE2
            bnlNK1FyOCtiNjdNRGpOYldVcFVBallPa1hSYTlCWXExVm8KLS0tIHpldTljTjE1
            Rk1jT0FCZzlUVVVURDZCUXhKS2NEbWpEekxlMG0zM21jRDQKxw6hRSK6VR9z+r7h
            0HdJp9mIhM0zUBwOzLq9MYvQoIaOFLqZ9XIjYC/XB7NQDePx7kuAA1kD3PbwMEun
            /DYZow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T22:08:37Z"
    mac: ENC[AES256_GCM,data:x8ctJVBNbutfd4mXl6iaZ8AVbt3p+K/NVhIxCdIe62d4UByYGEjkSh1XyDEfgcTDvl7wW2x5HGY6tqEyllgGQyOJFjqzq41vBHcp5GVX6cUXnFUT3nAx3jdy1Z+7TAo5K0shSKCu06/B9oZNPEwrplNhT1EHb/Oqu4ylBSPKyyk=,iv:ZfPvZGbjJkQTVnCpRApT2pE/LGFj+0wG4YMZBjichSA=,tag:gGiYdeHrfEtWs2hZxf0IaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
