---
- name: List groups
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum group list"
  register: group_list
  changed_when: false

- name: Add admin group
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: pveum group add admin -comment "System Administrators" && pveum acl modify / -group admin -role Administrator
  when: "'admin' not in group_list.stdout"

- name: List users
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user list"
  register: user_list
  changed_when: false

- name: Add terraform user to PVE realm
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user add terraform@pve -password '{{ vault_terraform_pve_password }}' -group admin"
  when: "'terraform@pve' not in user_list.stdout"

- name: Ensure NOPASSWD for certain proxmox commands
  ansible.builtin.blockinfile:
    state: present
    path: "/etc/sudoers.d/terraform"
    validate: /usr/sbin/visudo -cf %s
    block: |
      terraform ALL=(root) NOPASSWD: /sbin/pvesm
      terraform ALL=(root) NOPASSWD: /sbin/qm
      terraform ALL=(root) NOPASSWD: /usr/bin/tee /var/lib/vz/*
  when: ansible_facts['distribution'] == 'Proxmox'
