---
- name: Configure notifications
  ansible.builtin.template:
    src: pve-notifications.cfg.j2
    dest: /etc/pve/notifications.cfg
    mode: '0640'
    owner: root
    group: www-data

- name: Configure notifications' secrets
  ansible.builtin.template:
    src: pve-priv-notifications.cfg.j2
    dest: /etc/pve/priv/notifications.cfg
    mode: '0600'
    owner: root
    group: www-data
