---
- name: List groups
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum group list"
  register: group_list
  changed_when: false

- name: Add admin group
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: pveum group add admin -comment "System Administrators" && pveum acl modify / -group admin -role Administrator
  when: "'admin' not in group_list.stdout"

- name: List users
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user list"
  register: user_list
  changed_when: false

- name: "Add user {{ vault_admin_username }}"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user add {{ vault_admin_username }}@pve -password {{ vault_admin_pve_password }} -group admin"
  when: 'vault_admin_username | string not in user_list.stdout'
  #when: "'{{ vault_admin_username }}@pve' not in user_list.stdout"
