---
- name: Touch file for realms definition
  ansible.builtin.file:
    state: touch
    path: /etc/pve/priv/realm/freeIPA.pw
    mode: '0600'

- name: Ensure secrets for the freeIPA realm are set
  ansible.builtin.template:
    src: pve-priv-realm-freeIPA.pw.j2
    dest: /etc/pve/priv/realm/freeIPA.pw
    mode: '0600'
    owner: root
    group: www-data

- name: Ensure authentication realms are set
  ansible.builtin.template:
    src: pve-domains.cfg.j2
    dest: /etc/pve/domains.cfg
    mode: '0640'
    owner: root
    group: www-data

- name: Sync freeIPA realm
  ansible.builtin.shell:
    cmd: "pveum realm sync freeIPA"
    executable: /bin/bash

- name: Ensure ACLs are set for the proxmox_admins-freeIPA Proxmox group
  ansible.builtin.shell:
    cmd: pveum acl modify / -group proxmox_admins-freeIPA -role Administrator
    executable: /bin/bash

- name: List tokens of terraform
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user token list terraform-functional@freeIPA"
  changed_when: false
  register: token_list

- name: Add API token for terraform
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "pveum user token add terraform-functional@freeIPA k8s"
  when: '"k8s" not in token_list.stdout'
  changed_when: true
  failed_when: false
