---
- name: Add standard proxmox repository
  ansible.builtin.lineinfile:
    line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    path: /etc/apt/sources.list

- name: Delete enterprise repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: 'enterprise'

- name: Delete sources.list.d directory
  ansible.builtin.file:
    path: '/etc/apt/sources.list.d'
    state: absent
