---
- name: Ensure archiver@pbs password is set
  ansible.builtin.template:
    src: pve-priv-storage-pbs-offline-backup.pw.j2
    dest: /etc/pve/priv/storage/pbs-offline-backup.pw
    mode: '0600'
    owner: root
    group: www-data

- name: Ensure storage configuration is set
  ansible.builtin.template:
    src: pve-storage.cfg.j2
    dest: /etc/pve/storage.cfg
    mode: '0640'
    owner: root
    group: www-data
