---
- name: Ensure archiver@pbs password is set
  ansible.builtin.template:
    src: pve-priv-storage-pbs-offline-backup.pw.j2
    dest: /etc/pve/priv/storage/pbs-offline-backup.pw
    mode: '0600'
    owner: root
    group: www-data

#- name: Ensure storage configuration is set
#  ansible.builtin.template:
#    src: pve-storage.cfg.j2
#    dest: /etc/pve/storage.cfg
#    mode: '0640'
#    owner: root
#    group: www-data
    #
- name: Ensure media dataset is set
  community.general.zfs:
    name: mpool/media
    state: present

- name: Ensure packets for NFS are installed
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
      - gssproxy
    state: present

- name: Ensure /etc/exports is configured
  ansible.builtin.copy:
    src: etc-exports
    dest: /etc/exports
    mode: '0644'
    owner: root
    group: root

- name: Ensure gssproxy is started and enabled
  ansible.builtin.systemd_service:
    name: gssproxy
    state: started
    enabled: true

- name: Get Kerberos ticket using keytab
  community.general.krb_ticket:
    keytab: true
    keytab_path: /etc/krb5.keytab

# nfs/proxmox_fqdn service must first be present in the idm domain
- name: Retrieve nfs service keytab
  ansible.builtin.shell: ipa-getkeytab -s money.{{ subdomain }}.{{ domain }} -p nfs/{{ node_name }}.{{ subdomain }}.{{ domain }} -k /etc/krb5.keytab
