---
- name: Add standard proxmox repository
  ansible.builtin.lineinfile:
    line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    path: /etc/apt/sources.list
- name: Delete enterprise repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: 'enterprise'
- name: Delete sources.list.d directory
  ansible.builtin.file:
    path: '/etc/apt/sources.list.d'
    state: absent
- name: Full system upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
- name: Ensure unattended-upgrades are present
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
- name: Configure unattended updates
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections && dpkg-reconfigure -f noninteractive unattended-upgrades"
    creates: /etc/apt/apt.conf.d/20auto-upgrades
