apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:iSXKUlBl7IGi7W5KweITPx3naTFdvxAmUr4acOd4lDcq0B0xSrDxsti3ceE=,iv:ZRAKq4aGHYeN4agCpGsjifjSBKw2o0Hlj9u/Txs3SDg=,tag:F+MEojMBUKAZAjDWngWLKQ==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:1jEpY3IpCMz6tmB70A1/rZ1p5dcqVohF67w9T1rcH3Fppj4yqLUUwhQ=,iv:4bfkWJ0Qtb9V1xfiyjA7SDah/N4I6wYykJVIqx4PjoU=,tag:1gs7KTyNafS62tqW6UyFww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBaaHJT
            M0hUcUFMWU5HMTE1OHBkU3I2NEdZMkJKNDJNakU3K2J3dGJvYXcwClI1emNqVktR
            am9OZGZIakV1RVd3TWpXNmdsZ1cyS1BIRVNnQlZnTGVIYjgKLS0tIDRwekxYZVNQ
            dWhzTFFaalpLY013aHNnNitKZWdFNWJyNXpxNzM2UVNUUE0KfnkAw0vq/0deZIoH
            XfGfl4vF9bWmK6h0eluQMr07nYUIsK23xgEAlvDMu0CcGhOihRzhae2A/FOd1n+i
            c5gU4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWkJnUEpVQ0s0eFVtNDBO
            aGVQeDc3YS9wSDBnemxxNUNlU3lySERHeUVzCmdCODFNTXpKYnYwWjFITktEVFlH
            bGlsTVJ1eW9vNHUxOFVKMjlOZ0QrUkEKLS0tIElNV0M0T0krZ1Z2ell5UmdRVVhm
            cTlJMFZvbC90cm1MZGtGZjYvRXhUZDAKVneqPagB/liNcVDdog8GyPTMZBZ47GQJ
            fvYBxSancb4XwZ9THRWoxjphoUDfLDyndZwTnyl5lRzzaaQavZO5Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSAvRElm
            ZnBFU1dHWlppRUVpckxDeWJiY1ZoakdseTdtL3ZUMDU2OUdnamtnCkp1M3hPSVdK
            WGw0WVZMdWlHbXN3SVl5aG1YVHZqbmFDeDkyRW82ZUZZZGcKLS0tIE5ubU9zNXhu
            TFhveE5Fdk9xWVZCd3g3c3FSbnFHb0VWeVJuTkZqMjRqaU0KKz4dkeg77CLEO0g+
            LvAorRb3O3hlGaZOMBYhPouNKOZqvsMRKK17gn8TwCtIDzeiOpSjVK8ZAiO1Geif
            rTt3Ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINVBwOFhaZ0hYV1VWR2xj
            Wk5YdkZzMVFBTUpkZlFXMWtqWE9QaVNuNm5nClIzS1pWSzlidVlqMTlibklCRlR6
            UWlsdXVyd2Y2NWZ2OW5hWmliT1VHUzAKLS0tIFR1Mi8rd05vektJcWxodHBJdjJU
            UU4wajFzbnBGekJFWm52cXVEOUg4SzQKnyhE80SMhVjXl6Ef0V6h1GXLjEsYQYAW
            5CZkagf4Sona9W7f4ZMxeaHr8xKMx/24yNfey3RPNG4XaWLXL027Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T20:03:09Z"
    mac: ENC[AES256_GCM,data:HIkCF84Rzu2MreHA5g0+csWudSDyijpY78KFWDbZVK55eeGXRcANiH6+V/2CEIQQ7XwrV2S62a2hccsu0xsNBzTuEfaAjSiYuu7mRxj4KFd1BGzDPD2C8AaPG4rp+ic6Caiv3AB99ZDHnXOtBzlQd3xOhLblktJgRLrUFq2PZus=,iv:3DMZNCq0Jx5UOiCkjYAgs+F1jamkYp8Zg7sQLwnMayI=,tag:qQRKnKusBj72+2gb/7UvUg==,type:str]
    version: 3.13.1
