apiVersion: v1
kind: Secret
metadata:
    name: homelab-s3-credentials
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:UQ9RKKjd+HXBL7O5AnGWBxOQAZXEuywtQfmtLWne6/yh91uOYHJBRl7uz4mNH6J7YpQb5VAeDZb5j+QGU8AYrA==,iv:qIGF4P+hvjGo9CI461wtFvsWeIWV0reNDsfSZRlPWZA=,tag:zH4RfSiIMMYVg8BbjiDmTA==,type:str]
    secretKey: ENC[AES256_GCM,data:7KM4xOvlY0KCZw8mz3ip4JZXtDtOae5k8eFfp/j0AsikYZ2R34cmbVe9H0Mm5zcNj+bzEsqGhMbCK3jdhRwYOQ==,iv:avjBsyKHTv9utcH037v4QaIfrJcADvw5xXKlW8c0FDg=,tag:sbsumzxR34vwWtL5DVpi2g==,type:str]
    cloud: ENC[AES256_GCM,data:99w6g+H+jYLGParakGdxMouDb9FMkgxHJ8iAY7DM8D3m+JnMeEQysArxoKHg2J3wNnMjjPUWkJeRpWtmY1BvvSaNtf5nXL6Kv6N+hmuCV6ZYHopvPAkqnryWS6VlFMk8/6/TJy9XGC1rA8vqsTzDG4cksVTo/Ck01IBaJuTbUEVTo+O68ngKLGbAdF8pQl8yvHPGymX3Zc0TTaBLwWxn3rcTF15sIap40kzT6TeM6bltzAYW,iv:bzFW9MdKG3DdKMFp22zlIMVN6Z6/dEIxKwH4PaIRodM=,tag:7yuQ8JB9j027Pj2S87RPAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBGVWE3
            cmJxajJ5R1pMa1VqMFZtd1RlajQvRkJyMW03TGVDR1hiOUpQZnlBCkpQZndGekpl
            TjAvYm5kcytJZVM5TmNQc3U3N1NpUVU3d3c1dCt4TlFkS1UKLS0tIFAzZlZtM1Rx
            Q2JzZUUzZGJnbUdaUXk5Q3hXbENEd3htRFZEWUMybzN0UlEKmZuRMPuQ5CO3IUPK
            h9OwMsZV0BePcADSwQrCITerxwvis2N+lUxY1prM8jDpvlcWV88aZr+NtWW/U9gD
            7MfGDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGFQcEU3N3FwalBEU3cz
            RmNmb0IyWlFIYjNEYzBESmVJdFBsd2RYb1U4CmE5a09IS1B6cU1XS2M3VTA5UHFY
            T1pscjRNeHdYMVFiM0tDWVVZTTJCVGcKLS0tIHlaWG1aQ1BqTnY2cHlpVjV5WkRa
            YkVCNEM0ZjdFSzgwdk5ISTQ1Q0lkamMKalTMRvqmxkOU408yP4VFCWXNdEVM5Lva
            6mFV8FMnuCkAaQmVovBxd8Acv2VV4/W0QXGl7vVRQhc8Of92fiBNWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBJTGdY
            cmhJZHE0Z2I5MDdNdnhMWDNrTm5kTWJYeU1hL21iYXRHZFhzN2swCk9haTcyMXBn
            QysvSkduWk9aWk03UTl3dEJnS2VVbU1nZHNyTmoxWjEvUDgKLS0tIHFUSjJFSUl6
            aFdIbXpESDcza1BZL3V5TXJQK0pNRkZVaDVISXRDT1Z0aFEKDW1u7y9a7k70TPyT
            9sZndf0tpqcFsWJHb7wAVDbylPH3JVLNG9bK5CCWk5yTBqgAI2CBDMcFugt0L7JT
            s/lZEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1oxb041cUZDeU1nbEhN
            Yk03THhyTmc0Q2NMSXRUck8wTzQ4UHJGVGxVCjZjMEtlUW1Xcy9XamF0WjR6b2Jy
            MTVSR2dxN1NBZThxRjQwdnArMkl0SUkKLS0tIG9PYUU4Y1VTQXF0ODN3UzdwWElL
            QjZRUW5PbEE5TEwxSVRzazlvbVF4dFUK0m9fagciAUPrPe7YWSkQq718RLL+/XFw
            z2QwrpoXe4mGC8RgcUQlmtjdOLJ9K4D6ezwetujHx60bkVaEX5rTPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZlM5N1ZNbTllQVQveEw3
            RE1mVVdsdDJpVzEzZTlERExzZ1ZWamhlQnhNCnpBSlZaaDFSTHZ5dlZ2eEFiUkVK
            RkFoR1lxbUlGWkpsQWZ3aHZyb0ZRbVUKLS0tIDlKam1zZUw0enR3YVdVdkRLQjlw
            eEhMblNXNEZSbDY4YndYQXVRL3oyRncKC33heetWlbFXEqXYD49SduP0KTDT6BTO
            hDTkOr3QRJphYBDiJNfGcrSUMbaeWiOuhZsxBYDqma0cotZydc6OfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T23:08:48Z"
    mac: ENC[AES256_GCM,data:jno1bxDkzI1bkgItOWy8VNgKMkFYmz8HGPlT0VNsNNt59QEsNssZiST5rWfTQ5z7kHtFE9UjDDrt/rQSjAtX/deA5u+OoFG0vCGvIypWfJKzg+5yFJT0DhbXsQVlSmQgcIkYzamCcRa5FdKmW5KU+8JWUiug266agvXQn2n+6jo=,iv:HkrykvsZNY89KOnvdTuTi4i+noGS9ApLaL4PgzzXRIc=,tag:T3CXee4K32vkJRPEscXv5A==,type:str]
    version: 3.13.3
