apiVersion: v1
kind: Secret
metadata:
    name: arr-secret
    namespace: arr
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:/6ql2ls6/tfqsUITXPyR4Kvb215fVFHRkmY4J6IM6/RPRr6Eh0KZz38YUa4=,iv:dLgfXJsEBaqrvC9XDDjQH5A661LxmMuM5pRIkva3LRU=,tag:qEQ63nB5pdg9OkCgc+bShQ==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:FGVnt62b1LIjQHX9hUIMZCd5E+Vd82o9YXqa2hZgffc=,iv:htgqgdCXz/YAUOTRVgbfXL2637FcUZv4TnnolPSm3ZU=,tag:kwYQFOMGiAzR+3yn6OrsEw==,type:str]
    #ENC[AES256_GCM,data:e80Vv0VsFGss4BXxl4MGap2FgwwdIRzb6Z4yTKkkaZDca+2czlaPPkTM+j2vrBwTVD17BU9e14xavkFuVI8E2U94S6V2oZNLYvcw12MGCsI/gUU=,iv:+exnJeUly7+haD5UQeT6sPmz7m292sochGfMVcr2b8s=,tag:YjWUXUgwVM8TE/Tt7hmL5A==,type:comment]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:ButdCzVDi8wpm8bDrMS9dvYy1K+Yl2xbYRcVhrmVMkDUfS+MKxwzpEzhP4w0psNg3IZKyNz4amEijfJVKfE6QP45EPw8apxr7y/ZhQ9zX8Jo/UDlaLB7NLYs7m2mBmqv06TzYexGw84KyIvGBtckGf4=,iv:oH6WAp8lm/fw94gKDVURqTDjcwfEdzuOyS5eTiZwnsc=,tag:EaHyYL7PBmRrDtDsHd+6jQ==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:MPTLMiGcwZiwL9RasHtNbhhVsjg6KTK8s2ueSACElpc=,iv:wgFHep+QNVuXG4DYdbrvyn2i0J/n1E4M23RgRl1uv+M=,tag:N2ELU+/pMwmnSptBqQrpAA==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:31Tmbp7Zgi5Y8YmQAv3GaceskpJNoAMxCQ3n1zY+ZtU=,iv:GQ4H5PuO50/WZlwEDIecml7jXaroUokvIUDAYo6xeHI=,tag:JajZFdh63vhgTPKqilCfTA==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:N8lDVVD939ftVjZgNBnssdNtj8eWDm2suohOySPbKfo=,iv:CXO+PRFtYeWAaQyXS6XuAFHJnHK3HpxW9SG/4kHggdA=,tag:CyhkxvEsSno/rYdeCAtW1A==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBLaDlJ
            YVZBVVZNV1d4WTZTSGMvalh0aXBmb0t3WUw5SEFkeTlPNjA3SlRNCkpPNVFaZlFi
            R3dQdkNOUVZrcDBVZVFYSGthUUxwbklUVmFRZWxKcVJTQmsKLS0tIFdkUXZzOHZN
            dWwxdlJHNWdNaVZFTFRjNEY0ektlOEduSXpmTEUzQ0ZYeWMKKsrwpQfKgSluVChQ
            8oa+dnWJGrulXr5ziuE565YrgzsXPjnZCo1LXgWRtMXP3VmBXto8pgyzDPM3tKmP
            Jt17Bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YkZUSWlnUnAwUXcraHha
            VGdIdFBEQ3plQUxJM0plb2xCaVBCUlJHZlNnCit1ZzVSLzZxOHJJRzh5L2crdFhH
            dE9oTXN5akVqQjdLS21DbE1EM3crYTAKLS0tIDRUY3BHWk93Rmt3cDdDbnUyWVZj
            eXErQ1Ntbjl4SEdYQWpaa244c3NENjAKn2rDSKKbwsmszT17WBMzXNxuqP3RpgwX
            Lmpz6rTvYBw/vbL89J8/NHcIEGUI39qqjt7AaCJaftDy6+DJTF9tFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBRcXpK
            TGVSL2lOa0xFYlFUZWk3bmZRREgxTkh0Nk82cmszQVJBbUQydUUwCmxUY1JHT05k
            aFBDdm1Ob0MzM2dreFJuVFNlSG9kWVRmdmNjM2FkcVpJUE0KLS0tIE03QVlXSzdm
            UERneEUwWWZrZ3Z1bGttK01wMzd4cmJpRE16cVYvK2cxcjgK163676WdohGk8JJ6
            pCuGLyY8GgV+lcvAiYnvPxQgvasmQf3YTL6qQUkzyRfIeQfk+ULoAWxfsd8KB00W
            TGVlSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWGtZdy9oTUpmN2lVdnVF
            aVg1MXczaUJrUkQzVFZXWG9ZMHZERzFFeFU0ClpWaElreVlINVUweEJ2ZHFhNjkv
            T2JDbzdvLzRpSkxYVDlhN1BvUmVCVW8KLS0tIHRtcytlMEE2elBORmlQMWh0aEha
            UGh3dVBQZUF4aWNodkkrcFJCOXpPcVEKEJaxVCklm22SCS9ZPHhTMaXUzm5cgj1q
            DtrbeExXTjx5+fssMAa/GUjxn2s2iYi/xx4d5dm5dWCX3FxSwIrdsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:24:49Z"
    mac: ENC[AES256_GCM,data:uCsdCkgGMQfqYlpFjL7C4pC2LZc0tK+K1uFYNQD7MpThVIfy+/uWgtA8D9LOQKco12f4N9zODu8I6OLkc+LTPi8KofJHy0uaZR0gogQIUA0/r6DROIZpbt9HwIqu6R26lJK+NhmqVOjFxItj4iOAzzdCJSg3qNP+RTSomTHpvn4=,iv:9Co/oImiOj6fv0tQXOO907b7gfqYDZlL/IhtjF7QYIg=,tag:DA22S9+maPWDx9MKO6bRMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
