apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: arr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - redmanager.animals-local.home.parents-basement.win
