apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
    namespace: redmanager
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7wVcvaDlpJ6GAvMYVARalyxesHFc4ECX7nljSlsPXeV4BH5Wsad3X/tuaWI=,iv:WH3XHAeVaCIH97ZhiOTneCG6kfQMRK1ZEc6tX2o2UbI=,tag:9ihqazj0sclwANb2mzdgHw==,type:str]
    TRANSMISSION_USER: ENC[AES256_GCM,data:2RWoipUjNXb7fA==,iv:jub1+iiUphEW/qEmP9N7DZDZZSjxCqGjmdiRj24vS4A=,tag:eYjt6LvYDirtVNphrW5kAg==,type:str]
    TRANSMISSION_PASS: ENC[AES256_GCM,data:QR31hukLX/a1WRi3di7rtbA7cni7IZX8GmtDWKvZ37w=,iv:rOYmC7P4WDpdI85gnlS6YhpwemBMymkF76DbLDqfiyI=,tag:u8Uvsqc6B6UBDJ4X27AnHw==,type:str]
    REDMANAGER_API_KEY: ENC[AES256_GCM,data:0aSH6hMUkaPBq+in2RCyYYtXxssFZsKgy1dYI+xPU7c=,iv:+7Ly7PEaqug+NjhG2frvCGdNMF72RlXWECTD+q+lj9Q=,tag:pjqyPsGo3CGeTZO1HmA0YQ==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:UQ8cVBUPmcGBsfyn5EzAiJucVptdMtaCblNbDk/ZdfAY85VK43kRzzQ=,iv:436HnvtdBV3n8X7o54dxEyFuW34oan1manXKLwzoGh0=,tag:rY+kY1W7qdoc5/ME5BC/+g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:q4TDELPEMWo2kWWW29wU6vwimTA8fkuQ/2SDwGDPnKk=,iv:a6LFCTM2AAz47FW+64HloETaWhxDuGLzn2ePhXklnkA=,tag:nh1LnoQ8eNATUoRbiqIb5w==,type:str]
    DB_USER: ENC[AES256_GCM,data:k4iI7oAYXncqUw==,iv:wDXBn/JgAtRytokDct7iKYa9Ajb2Olm8RP8s6I9LUAA=,tag:/LZCPtXIoJQo5be+vwrwkQ==,type:str]
    WRTAG_WEB_API_KEY: ENC[AES256_GCM,data:q/KE6wsHiBQB1cBgNwVQuY3ErKi19E8dwgQ3JGeDr+M=,iv:DjhszHGeTD9u/AK395bd3wXdyV3dJS4hKtjxZ7+ek1A=,tag:t1TaJUHm8RFC/Lgjhb6h8A==,type:str]
    ND_DEVAUTOCREATEADMINPASSWORD: ENC[AES256_GCM,data:GAQd1AcnQzOElBQ1AkuQP35im+5Ditq/ZTZ79l34buk=,iv:jW1FIa8mYi15o0RaHgM0Ozh2KJNwsoNIarTPHb1Nr00=,tag:75PsF1yQCcSOj4/LuLaGxg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBMWnl1
            eldSYWY3NExQcVpYTkw0MVR6YW5lb0lIOEhndWtvN1NDeG0xQkJrCm5MS3RZaWov
            bW1EWDVWSXBHMXJzZHBkVmk3emFZTUJrL0I1ejZ1SXRZcjQKLS0tIGZFU0V3emtZ
            R011RTNoVzRjRUw1Nzk0UEFyRDFBbnhHeTVTRDdaTk91T0kKcI7Yhp60RJIBj7fR
            pVIIaKEFhgpKkQUnP196rfFryLD/eofO+CrZTpxW77KdiINzKT9iQk9jXpEh/hqu
            x5aA3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdlU5YmJWWFpualN4eTJt
            MHJvWEdkUWJncFdJVG83OURraC8zWHdrTDI0CjFhMzRaNERtZ0FtVlk0bEhUT2Rw
            MU5CeVZUOHh4djBlZWlkVTNaaWVoOEEKLS0tIHg2aHQ2TnBDMjZOekdOcGJRcjFV
            bXRXSE0xVU1mKzlpWlV1VFZGcWQxcmcK7Se8uxsfcJy76JkTcOth+wmYgRae2lqY
            qAi27IP94mnlq8+A2RF70/FMTRjDFO/BFNF1cy/lll9ZB2Zzlis7NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSArcHlL
            MzZ1d1RaRVp4c2xqdzNTQW9Bd2tWRTdaZXVFaFdtNlVRUHAwV3dBCjZ4U296aFJS
            dmZLdmFRMFNDMzdqbGlaTlJJT2dtNXNwdThBdG81REZ5TmsKLS0tIHRiak8zT2pY
            VG13RjBzam80NGxjRGpHenl4YUFQd0lWZ1JNMnhtV0dnOEUKAfwPrXRYAkAQsTrr
            b4ef60ywF2ZeeT7ljERoCbwJoBLS7/a4tS+I+PMScnG8xKsCiHzIF8HGQOTVeFOu
            FikUxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRkgwdXplM3drdVczUEZq
            Q2dOUjUxeUhDRkNPUGZQVUZ1K2xDS1FKK1ZrCjlwNnlhOGZFZkVwdVVrckZvSTJ0
            dmpNRjBnTFhyZTdDVG13U25LUTJlYmsKLS0tIGduZlhjZm1IVTdNMUgwVmdDaWtw
            ODE3clU5RjdNZGsyeTVXcDBRcDhQUFkK+wL1QS8zce2g2XU09KjKISetBTHO11u3
            UR0QIo/srBRgUuIDimdpbLE+TCl9v0U8gvg82i1Z8xcGyjYBxhnCkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:44:53Z"
    mac: ENC[AES256_GCM,data:NpFX3O7EQ1f+7O8REVNmGpQNoiLfpH7JPv2YD+PwNc4GMEmyA56qfAJSsA+fhnyMq+c37JOKFjUY1jB6OhxBOAjAOunX2PAZQqGAkmAaKfynPfpn5b4rZBg94xvgEMGxpoIseOUd6p+vC11FaxK9M+5FkQp5wJguIsSxLsm3nxE=,iv:Rb99q8ALz3SbSZejt8rmr+58H2jf+4v6iNut0lgmBUA=,tag:Ag2mpLUu8kpmVNYgkfOouA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
