apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "envoy-public-lb-pool"
spec:
  blocks:
    - cidr: _
  serviceSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: public-eg
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
