apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - eg-announcement.yaml
  - ipam-eg.yaml
  - ipam-public-eg.yaml
  - ipam-sso-eg.yaml
  - public-eg-announcement.yaml
  - sso-eg-announcement.yaml
