apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wen/uPelvlxpR8wJmQddgVXrehjOlEXihU8zJ9TqkBGeoSAcCUt+pWbgKE8=,iv:OrLQYIP1bUQqsBpv1ZOYH4q4FYXlle0rddcSX33pA7Y=,tag:hx32xE3qKDV+G8hODi5y1A==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:KK++15nd2rXM7eMDyAk8Tr1gbLarVVpKTzL3sceO+Ms=,iv:G3fJAzAf2qJqXTqcwEJBVFMxsdJN1nEGP88Twthqeig=,tag:vuz/GigT8d5SKCUP6LIq4Q==,type:str]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:AAxLfpc1jWcOuLOtKBbjwxYB6D5FfV+vLzhYlpPz6Nsbj3/X7ENTgr8vueRE6TrcYznbufHLzD6L98jrWD5ByycsKYoUjqyDq8m+KtV/PjfVzgxUwQi0BIzLfpk5UUFf0D73myeFBNa07Ys794PGfvY=,iv:BF1YpX7pQTOKkDq7HeggoERtWuXUGsYKHci7i+2uIKo=,tag:PsaTy4yQPgr+E6SpVHlEJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBKNVlM
            MXpaWFQ1dC9pSWtDQkhZZngyeWIvWGhNSjJHc3F0OThCR0tPRGljCkNTUitUb3NW
            YmVkTWRvTGJHOCtSNnFvK2V5U29jYWRHUHZsdDVtR1ErMkUKLS0tIGhWRlhMWXA1
            UE8zVVhEUHNDaDI0VU1DYnp0ZklJMlA2OHhueVoyZ2ZMTFEKKD53JWWlWZC43JYp
            AlsYh1vG9F6Fay13CmAwcvlw5LdNo7jozStLXwLRN6aMcxSDoXbiEbZfOin60hTV
            XTplyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRlFXbDF4QmVjSUZRZjZt
            V0liZTNZQjJTYU9kODVzRFFNMVUzTXN2bXpRClhwNStOUVAzUGJuTmYyK1pFbjhY
            QmpZTkw1dHUxVTlvU2dJeDVRaXJGd1EKLS0tIEZVay9zd0p3NVJ2Z1RrTmV5ODdi
            RFFPbGlVLzQ2dFRwQ1BXVG9ESDVINkkKo7J43h8+v5dftV1RNVLp6tjqnFl2d5Hr
            Chx3uR4oTSOuiP9Rt2Y1jFLTzNpztu4kMy5hzv44/SXKXML30SHR7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBjNUxD
            bVdHUDV6R0ZFbUZZRHBQWHNWdmdmeG90bFpMZDhNaEY3Z0F2UlFjCndPN2tST2JI
            cUVxMjljamZnM0w5dVlOclBYRWRXa3p3N2pJelIrSmxmNXcKLS0tIEM3NHJMdHNT
            Z2FBMW9TRW8wOFVMWTJFRVZiKzRmQkp4b3h0VGhhYlZJV0UKK8B2wPO+3rLRaelo
            KEfzBHjnStYiYmTk173X0IUr692ilZ2SYcW3fvOLNHA2Ten6k4bYPrDOZU1KeDc8
            hj+geA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWk43K2ZDL2QyVzBGZ2RM
            UW1aK0h6VUpvOUVTWmV6YXVaMEF6WHlSU0VzCmFweVAxSDBqOGE5T1UvYmtvdGZB
            QVpPeFdZNGt6cXErQ0NUOHlBbEtMZ1UKLS0tIHpiREo2VXNwYXhYZlVZM2NKUHl3
            bUZXYWRwc3N6TmN3ZHhPMXQxQzZRUUEKqqXZUPgWRKAnR6sTjwAsFSnnq5p3Xr4Y
            tucyc1mvfUsdEYEaXgUSOLngkaKwZRhErJoTedqeMGpvy9YzERdJGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ui9QbkhJdk8xY1IyUEty
            S2h2WkhBeU9zY0FzWVdta2VYRm5acUl2S0d3CitRSFlVL2p5QzRvL2tpRk94N3NK
            OWROUE5HQmcwNC9USW1xLzJya21hTXMKLS0tIGJpTjJyakdGekIvTFNTbWZyMkpr
            VTFjU3I0TU4rK3JZSGdWZk4yelozV1UKPvV5RNvAg0gg1lviHL+9yz/3f1zMbAae
            m6BGwkASMGf7PApfutK6PjDzNziz4Wi84GH6XZEwRcn60iPQeBfzvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T20:38:17Z"
    mac: ENC[AES256_GCM,data:wDLcoG3PRafLMpOBsOt6p8vXOuNMTRaaeHNnhMBeBTx8v2kawjkM1E1AzxiLPenZsoJEEMNYAfgSAfOWM6Xgc9iDiU3fScn61D/+RCUkFzE8FaoA1auMZ26APiGFJIzLMU8EdSMxz5Dn4aKVyaHNNpNLOhtM3+XzcIOObQF7eDU=,iv:4+1n4JEC1kHPbXTMoyHKmT1ZxFvg0TB4uh6yR+n+mp8=,tag:mDdjDfOH4Jd0GW8dQKr2Zg==,type:str]
    version: 3.13.1
