apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ca-deployment.yaml
  - ca-service.yaml
  - certificate.yaml
  - deployment.yaml
  - httproute.yaml
  - issuer.yaml
  - pvc.yaml
  - service.yaml
