apiVersion: v1
kind: Secret
metadata:
    name: arr-secret
    namespace: arr
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wen/uPelvlxpR8wJmQddgVXrehjOlEXihU8zJ9TqkBGeoSAcCUt+pWbgKE8=,iv:OrLQYIP1bUQqsBpv1ZOYH4q4FYXlle0rddcSX33pA7Y=,tag:hx32xE3qKDV+G8hODi5y1A==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:KK++15nd2rXM7eMDyAk8Tr1gbLarVVpKTzL3sceO+Ms=,iv:G3fJAzAf2qJqXTqcwEJBVFMxsdJN1nEGP88Twthqeig=,tag:vuz/GigT8d5SKCUP6LIq4Q==,type:str]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:AAxLfpc1jWcOuLOtKBbjwxYB6D5FfV+vLzhYlpPz6Nsbj3/X7ENTgr8vueRE6TrcYznbufHLzD6L98jrWD5ByycsKYoUjqyDq8m+KtV/PjfVzgxUwQi0BIzLfpk5UUFf0D73myeFBNa07Ys794PGfvY=,iv:BF1YpX7pQTOKkDq7HeggoERtWuXUGsYKHci7i+2uIKo=,tag:PsaTy4yQPgr+E6SpVHlEJw==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:mTaghaPqXtINsxobh6BZJTz3UKtzgV8p6cbPbLcpYQ1ItN9PGKNtInuQXtnI+0v37jW4RsImBNr2hWHml14lMbKcSQU4bOVJltXo8yRF1u6KYi6zbVFY95pK3OWDoFsFdKE3uB5l7i6HfJqwnq3nxe82lYRStF8+7mP0U0bzG5g=,iv:29D6l6UqUqlhg+NmJd+Z6D/ApP1844dQkFJmW6+1inI=,tag:qrkK+wY/S9UkX1Ri8qU7Hg==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:vyJoopPuphM5MRR1Q4KUjc9a0o5TeLmmQnkgz9ByDUWrVGgkr+NOnum1aapwuxkAFxaNu9DELCJhHJwyZ4b1KdVHhA52nDHWCpSQrvcEmlM/yJ+bemxfAk7SDbb7TG086MwK41IaKr5OrLUGVMqdzIH5/wIOhncC9Qt51/vhG5s=,iv:73/pU46OtdloNkDwbItywts8E65xBzg0VO77WMcyvyw=,tag:Ez2Cy4dul7JLEtM9WfSkaQ==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:JWWQ3x4eT0e0gKYo8iIMfkVxs5I9oGXwApfDbiUm0hOgiem0iauHKwCReDaGqD3cez2I8hkjJpLBbzVS+gjPeyItlIZq5l6IipAf3ApVSKK8qHNr+/oOysgTQwrEimPpRozIpqvgXh6pw9z6qzByP1QI7qyW5W74MzuUVkkFDiU=,iv:RaITZ+m9i2Oza1zyKIoPkZlRynOd2TMO4SWWyWpP8Y4=,tag:vNZDigIZNDENcdDPZnE5gw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyAvRmQ1
            RFNUVkJ2a1pTdFJxM0pkTlpaMzQ5OHVYN0JFWTRqeVFHYUdtY3hrClVETk56bWhI
            U2FDaFExUXdMbU45ZmFMQ1RHTDlIbndibG0xMm41ejVGZ0UKLS0tIEpOVElCNWx1
            Y2J5NXFJclVPNFhlWm44dzhsMDAwM2dNUGVuc09uTzNGVjAK9is93kaXHEz+NHUR
            IcvAR1EEMAh3WoAKT0Y99NcdThuAR0m6qQRWlzmkFguubVGnC3KOgrDUO6V/fYyj
            TBtPLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZUI1R21lQ1RJOWMyWTVr
            K0d4cndIVG51ZVV5dTl4VEM2NVBrdWU4VlF3Ck1jMlRObVBFMU5rekJjMElYcnRh
            OEhybWxDUEhCNTRpTWswVHAzdE54b0EKLS0tIHY4ZXNDUTdEbEwxWnJ6YUJEOVQx
            V1lQcWNRYkxyUlFqeWw3d0xHTG5CNjQKgsiWRAIqQeS6MBJHPNnAtL3jv9lIcnt2
            8YLG9RwJR5bq+QX8oq0RUIoa8I0MeVDcXZwlTOKT57LS+Dbr60KC7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBIK0Nz
            b1hnVjRMT21LOVdoQi9INnhEZ3RmSlN1U3J4ZFQ5WU0wSGE3V2gwCnlvUlpRUUs3
            ZlZrbG9sRlR3SkxBSFVtd016VlJHcHM5R0lKTDRtYXl6VVkKLS0tIGVJckdCVTkv
            by9lVE51Mm5ZYXpRRVRlTHN6bEFaalRGN2hzdysycFlXRTQKtAyp2lK60bO+Joi1
            uZOcRgPkp8KeEqdLpfDrzwat96/7zISZ1Oy5ZoOzCZpXeTENz2pS4UiEkE4VI0/h
            0BbhLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYzlzblM3c25uSm9qSmhu
            V3FwSlh3VU0vQ0xOd0N0UHFCYmlRajZQb0ZVCk52RzF6VktrSkdZejBNMXBJdXFT
            NlkrU3BZbVRUQWFOdGFjdHdsSTluMjAKLS0tIGhiVkFTOEZtMkFsbkk5cVMxUmpj
            Yjh2WWNGREhRSjVjWnlSOHplTzBGZW8K/jxIozK9J6OtjTIJPTZd93kdXOy6/sUY
            Q/+sFn6RlGSXt5lJpqDH3JsUeoXLK8JMh+9kbvTQiUXO7Db1sNx8qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T18:05:13Z"
    mac: ENC[AES256_GCM,data:jHcWucFHfZXjwbNH9O7ISfoJtMgBaetg/jz8leVmz6RhPxN/j92BC96YDmSfmxhHJk91SQzr+3LFv1JDUouScQGNbV0g5hCDKfMiOVgaTrHX3PNaiaugXyha0e8CPwtP+Elx4CMN7vI7+9NaDYNjZxhl9zqq/Ah7gOGnm5frCbI=,iv:Qtyv/mNmflcx8WBFmR3tfBhDEwiSiEXIiiqp2jctlho=,tag:on7QiNKy4K5rnn10KVC6ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
