apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
    namespace: redmanager
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ggN2WosWKzqwhkSLA+kCPQXLWTIGfP6gSUyfrVCh+SCDMDRcWJnpqmZWeoA=,iv:yvAY6X/st4ToKHqFWbI6VqXqjbw21AozBUMp8xZmRWM=,tag:FssaOFKJb1QnLkr2y6lxFg==,type:str]
    TRANSMISSION_USER: ENC[AES256_GCM,data:2RWoipUjNXb7fA==,iv:jub1+iiUphEW/qEmP9N7DZDZZSjxCqGjmdiRj24vS4A=,tag:eYjt6LvYDirtVNphrW5kAg==,type:str]
    TRANSMISSION_PASS: ENC[AES256_GCM,data:HlDbn+Gf/Kxz8lOF3TgikA==,iv:jKbWa2HVyFJAXyVap5uHu7/0cDTHGdHzzCJNzkG4yCo=,tag:it/iVG/REWMx00hmlpjeZA==,type:str]
    REDMANAGER_API_KEY: ENC[AES256_GCM,data:KJKYMxsrogDi0GQhsRA1GA==,iv:puVwDfu7w+2zJtYKOCp5WJoS8n13w6xJjdrH7XBDjhQ=,tag:EGfkwbUSvuf6QX8Fs2DgiQ==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:9//Tz+3epS41C8NOzzXA30tzA+nw8Lis+7kU9h48DN7UDXfymsetdAw=,iv:pbueGMIdjzPe0fcMov9jZYFAXI2sEEedtKBb1vAvHRc=,tag:jPGffdR12Xi4MgScMuSllw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:s/j60W3PzUbzpAaYB1LCdw==,iv:IBid7WtpgkB5BeQ/I5uqN6uSDiLtq0anD/9LxQydqAs=,tag:bb6/MhvTBsd3R+b5jTGiew==,type:str]
    DB_USER: ENC[AES256_GCM,data:k4iI7oAYXncqUw==,iv:wDXBn/JgAtRytokDct7iKYa9Ajb2Olm8RP8s6I9LUAA=,tag:/LZCPtXIoJQo5be+vwrwkQ==,type:str]
    WRTAG_WEB_API_KEY: ENC[AES256_GCM,data:KMdp6vhOADX0Nk7JGduOLQ==,iv:9KtorYKV7/L48P/Art8dzZE0EO0meOIFtYXe1MmZu7U=,tag:/MxDwLTiGhQOXQWFHaUOPw==,type:str]
    ND_DEVAUTOCREATEADMINPASSWORD: ENC[AES256_GCM,data:nXO6BIdak/KKKbIWMHEu7A==,iv:klInZ2AXOxQ9xsLOkzro0G5lpkipFqXWk4rA0lQiRvI=,tag:WCfgdSkejbRicEQcOTYuaw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBReDlr
            Y0U1Q3FncS9SaVdoR21EL3doa3R0Zy9Eb21JYVpDZTRRR05SK25VCkVRcG90WVhm
            SzFOb3YrZjVqdmNTRmdraGxCaVdGWGZkME5KT0VBTFZEYVUKLS0tIHJqV2FZakJz
            ZVByZlJRSlJmMzc4cHVUTitXMDBMZzFwcGM4bldhekwxRlkKktIgull7sCYycyqR
            tGSfvOS43Pcyn6zCDZR38z9oglrophejsluQr4kXmP84ntaoSdnwIp5swXkUOoWo
            INCoHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQW1SM0VCMjJvQ1IvOHJw
            Z1BrY1VHSXNJZEp5NDc5SVhoaENhRXllY2dJCmFFZlpWZEhOd0ZFTmpHZEk1T1RU
            T1VkTVhtSG5nekQyeGxBOVlBYzNqYm8KLS0tIHNnS0NFVTc4V3kyd1hKQzdCbjNr
            djZSM3lqdjJFNUMxYlZvUWpHQXNrRTgKCzC2aE6ep7vXygALccLRHAfLS1ZBq1lh
            pHpqlAvsG4HvlBdjxKjTXVF82eb1Syjp6Rd1RwFWaj4NmfVfxWr7TQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBnaVRr
            eTJ0LzNtMkc5QWtRbFNwZTdJbklIb043V1dPdzNFNVh1Y0VkSnhjCmpiVWZYRUpt
            Yyt6QkJUUDREdmNoNEUybFJUZERCNDdxVzViQUxmeW1RTVUKLS0tIHByUkpVY29l
            c0xNeTdlZlVILzNaNkhKQko4T0x2NWNlaWdERU1lOWtVU1kK3+10Q8I3mUxSnlN2
            tV3HCJJFzdB14EuRk/SAT3qLFZo85gToSsg+qOk1G3LF1U0sqrwq4OKBKAevSCIf
            jd+Egw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjBtRXZUNURRL2V5WUZF
            RFcxYVBFUmxUdFNxZ2t5di9kZU4zejBjTlI0CisyYkVIS3ZMbXdwQnBFR3ZiN1h5
            VVVGcytjQUtuN080WjVaUVUybHRjTlUKLS0tIGwxc0JLeVRqNzNHM0p0cy9YNnNX
            cjdMWis4c20vWW5oQUFZaVZLVW9UbUkKn8XnuujjvoFAUTFGWvAU6KugL5NZz40/
            jhRgbPUKThg9xaxS+96HkuzrvMr5Hdxji7zYakirmpmv49rt1msbAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T20:01:41Z"
    mac: ENC[AES256_GCM,data:DRFaWGX3lC3QGRtMq9qQ5yTgnGV/7kOMy8POjM/VOXJf222IVasbnntigv30diPpCn/rIwOrIIzmx9NMVv60EfrwyxEZpfD+0TfU71Zvt/kxfdMH3sOVliR4JRiKlllwbYsr61TWMoEkgWd+O0igkx2QKf0Zj58+WkbW34pfbCQ=,iv:5qF/LvprvXvmeAPujnFrLmoPmvvV5JD1fTut4eGfAsE=,tag:6jq3Q7jJb2y9IdMqIa+FEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
