- op: replace
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: pgdata
      mountPath: /var/lib/postgresql
    - name: pg-run
      mountPath: /var/run/postgresql

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: pg-run
    emptyDir: {}

- op: replace
  path: /spec/template/spec/securityContext/runAsUser
  value: 70
- op: replace
  path: /spec/template/spec/securityContext/runAsGroup
  value: 70
- op: replace
  path: /spec/template/spec/securityContext/fsGroup
  value: 70
