---
- name: Full system upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
- name: Ensure unattended_upgrades are present
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
- name: Configure unattended updates
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections && dpkg-reconfigure -f noninteractive unattended-upgrades"
    creates: /etc/apt/apt.conf.d/20auto-upgrades
