apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-seaweedfs-to-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "seaweed.seaweedfs.com"
    resources:
      - "buckets"
      - "s3identities"
      - "s3credentials"
    verbs:
      - "*"
