apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:HsIsxHTww972luATpoEmzIkcjE09VU385VXLvcdvVMTEG6sR0u+5B10o7iceHztZ94ALo2o=,iv:njRsdBS03eMtWS90KfQAOQ6zLmzmTxqZnY4XbmRxC3Q=,tag:Fn4Ietczn5ZyegLxvfxdsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBsWURj
            ZkwxbFNQWi9FaWNVNHRGbVEyb3RHMHVyY3VkOXBEMzJzT3FQaG1VCmRneHkwNEcx
            c0VHYUlaQU5uYlRZaUtveTNISDVwMTJ3alRTQ21JZ3Vvc3cKLS0tIEVwNVI5dHVV
            VVVNTlNoRnBNaFhiZTFHc0NxcGdtQ1J3ekYzdGs3aXBIM1kKfkyu5kpSQjuIrhwV
            +3UxQeM48pU2Oxa5qkL96jpbgXEBKWZuf408BCCENEYM9SE1+VTiZs/AZQQO/GRy
            Ln7p8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXAydkhhL3dRQmdUYWNq
            Slo2NlluaGlLTnc0UlpLcFRLblg5c1lyVUZ3Ck9PWjZ3UHR2cU13Wm51cUlZSnVO
            YzZxMERsN1hndlpzZ21YS3N2Q0VzRDgKLS0tIEVtV1NFNTJjZ0plc0JsZTNiOFpi
            ZWlGS2FBa3RaalF1Z1REcWdtWVpSMkUKX4LP5pp60ApLQqB97Xy6sPS4Cb5XniWp
            vRZiXBi4LlSWCVqVPmZQCKBSK66X9ShuRIWofjtr4wW5epipmFV78A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA4OHp0
            TjZpUlBtbHkwcEtUYjdYYytLWllCYk9PNURhQWoxR0JKT1Z1WkhRCmprYWQrQ2Yw
            cjd4THFnMGtSSDFqbmd5Z2dvcU40UTNhbTQzejZPSXpoRGMKLS0tIElaVFlBMUph
            akpqZkEwdTVIV2FmTTE3SXNCUGxOamJ1N1U5UktaNEQ1WmcKbNAMAGG1BAFlES4N
            /S2nkM8UZet3lZWJvLXjxJemNbFc9CcGQ+11WpSFtm4oNI4YzTNPXS7YOuY+WYb0
            I3ZC/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ny9KY1dBNzNXZU42SmNN
            bzRRTWYrZHJDejE0dlVCR3lOUUhWVmZhMm1FCnJZM2U5cVp3Q0xlN3J0ekhUY21S
            TnVVZFJHUW9xaGF3K0UrV0Y3ZUpKcjAKLS0tIEZHazRaL0Y4YWpYUW9XTCtBS2M0
            OXNDSkxSQktpc1QzcGZ4Rml5QzY4WEEKR2QBolAJiHbUluTIDE5dtlgDdpI+2BcP
            wS0SWCSODydLLZz4uDNJUZaAJyafNWJikJ8CCW4MVQRPWYMdKjxZKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:26:37Z"
    mac: ENC[AES256_GCM,data:GVAt5V1U44gTGi0tQC2oUTu2/dPQjcjpbNxjsrLnddb2nCYBYUwZ6I0p1PAad7m1pNMz02GhJDBVSq7Ul2u+2xDtSApHxQvsX9SA7yjMmkhAfPhn8//jsdYFaQUDfh/1rgBXpOYqtXqj03F0CGe+UDTzsMKO1j4k/Mpj1oDVp70=,iv:Rym9/xW9FNhDcLPKO1Ek8x++u7i9u4UQAk2p+/CQdPM=,tag:6igo7duv5uuuT8GPUaUHqw==,type:str]
    version: 3.13.0
