apiVersion: v1
kind: Secret
metadata:
    name: alloy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:aPvhdQKLK5M66I25RYOOuxWIO6UTNjw7iYeLXjVJHBG/otynfCdjBvp0PYlzceHEV8FeuaF0,iv:E9xTDKPv3Va7X87rkksn5WJD8RMZted9vo9Yh+PNARc=,tag:3SADPrfMJ5oMj5Y/0Fhz0Q==,type:comment]
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:Vp9Rg4THVrMFk95X6SzBcGZYF0lP8+8jADD2ZP90mf+o8unk+iIEqivz+pZ+yv0vvCpHcD7JMnhDHirzvLLgz+jZBG/sJrtBogmj2+kG0WaxR6ZYcMcMIf4GrsFgWyntFxTqeQIPRgqc4f3z0Xl3ggjvzn9ptegGVg0ju7gKO3BB+O/UNiWProl4qnbtQ4WD,iv:clVYgX4Onk4hUcmxpvmlnVtkEk7+32dvKZ7pEXqrUFg=,tag:FKGIZIcnt2joo/cvWBhl1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBsWURj
            ZkwxbFNQWi9FaWNVNHRGbVEyb3RHMHVyY3VkOXBEMzJzT3FQaG1VCmRneHkwNEcx
            c0VHYUlaQU5uYlRZaUtveTNISDVwMTJ3alRTQ21JZ3Vvc3cKLS0tIEVwNVI5dHVV
            VVVNTlNoRnBNaFhiZTFHc0NxcGdtQ1J3ekYzdGs3aXBIM1kKfkyu5kpSQjuIrhwV
            +3UxQeM48pU2Oxa5qkL96jpbgXEBKWZuf408BCCENEYM9SE1+VTiZs/AZQQO/GRy
            Ln7p8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eXAydkhhL3dRQmdUYWNq
            Slo2NlluaGlLTnc0UlpLcFRLblg5c1lyVUZ3Ck9PWjZ3UHR2cU13Wm51cUlZSnVO
            YzZxMERsN1hndlpzZ21YS3N2Q0VzRDgKLS0tIEVtV1NFNTJjZ0plc0JsZTNiOFpi
            ZWlGS2FBa3RaalF1Z1REcWdtWVpSMkUKX4LP5pp60ApLQqB97Xy6sPS4Cb5XniWp
            vRZiXBi4LlSWCVqVPmZQCKBSK66X9ShuRIWofjtr4wW5epipmFV78A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA4OHp0
            TjZpUlBtbHkwcEtUYjdYYytLWllCYk9PNURhQWoxR0JKT1Z1WkhRCmprYWQrQ2Yw
            cjd4THFnMGtSSDFqbmd5Z2dvcU40UTNhbTQzejZPSXpoRGMKLS0tIElaVFlBMUph
            akpqZkEwdTVIV2FmTTE3SXNCUGxOamJ1N1U5UktaNEQ1WmcKbNAMAGG1BAFlES4N
            /S2nkM8UZet3lZWJvLXjxJemNbFc9CcGQ+11WpSFtm4oNI4YzTNPXS7YOuY+WYb0
            I3ZC/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ny9KY1dBNzNXZU42SmNN
            bzRRTWYrZHJDejE0dlVCR3lOUUhWVmZhMm1FCnJZM2U5cVp3Q0xlN3J0ekhUY21S
            TnVVZFJHUW9xaGF3K0UrV0Y3ZUpKcjAKLS0tIEZHazRaL0Y4YWpYUW9XTCtBS2M0
            OXNDSkxSQktpc1QzcGZ4Rml5QzY4WEEKR2QBolAJiHbUluTIDE5dtlgDdpI+2BcP
            wS0SWCSODydLLZz4uDNJUZaAJyafNWJikJ8CCW4MVQRPWYMdKjxZKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T22:27:22Z"
    mac: ENC[AES256_GCM,data:tm7DhnS4qh8EOKnhG0HJq3uNcKMm/Qm7phwHSFDV8d0yKWEClEMY2Ywcfhxz59Rqzr77PNFUdUmX87czOzDXdFcciwch/Ru30j7zYohvtnmrMdL6pQf8PMukBFdijqgTtaqEjkuU/4BcnSGts02Vzf0AjSJo4+AMpm9eRVPwpSY=,iv:Se9bL+BcZ++MI2OQwXSw6z9bYlC2InKVxHaxKyfmI9s=,tag:+Mki2oV4Xi70oAZqlNqjQQ==,type:str]
    version: 3.13.1
