apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XEUfK4e/VYk05c7pW8+qcV1xZhALPy636f8xly4AyAd+ZtkqW6qqEA==,iv:w1po3B5S1gv/FVMg4scfxWwvC6vr1FJC9NnOUkwGTpc=,tag:cVpbOvbszRX8utc376YpbQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyAzR0lQ
            cTR6dWhGYjl2Y0hvM2Y3SFVMMG1BaHBMSFpPV1plZjNWdG9VM1FnCkw1cVRGd0gr
            Rkt5ZFBwcmFqS0ZPSGhaTVZYSDdDUnlRemF0ZUZCMGNvYm8KLS0tIGhFSWpvUUQ4
            ZU50ZlJ3dFVJQm5HQy96RkFmOEE2c3psTmhiUnNyK09TbXcKOC4moWtsHvAjza3n
            7Z5efhqRx42sTEHeAVqDwSzdBRkitN+O65kBdPW3sZir6VOJPCMQpTunjlWDNt4v
            t7GQwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTFVwMmpaZW5wbzNSanZo
            MnBzS0pEcWVKRXVwVVFYODNsb2FYL2NITm5JCkJVVWhRd1VKdm1OM2YxMnc0d2l4
            VDFwTFpLczhnM2c2N2RoNWJ3V2hKeFkKLS0tIGpFd3lnQjliRnB5ejMwRjVDRGk5
            c3I1NDRQcFcwdnBlZXpzS3hLSWxndmcKnZJForyFRd9LdxwuzuqON6I8oYEPITMU
            alHZgS70kg4qBix42K/s69OtYTjnotW3MFHi4VTE+xdmcnwGkWS3cQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBvanQv
            WVY4blp1eDlTZ1J4NkU2NWZGbWlOQzN1Znd1WnUxcnpiZTg2bUJRClpRYW5xZHRV
            aGhtUWxod2wyc01XQTNGTld6Z0dreTB3amhYTkk4WFRVUTQKLS0tIEdMc094bWNC
            TUdNejkxL284SjJvN2dBYU8ydGJDNTVmRlBrcHIxa0JJaTAKU5y6JJ6IfYNE3IKm
            kFsckgCwZWPiMhzAeezRBMBD5off4iQXnvOgoellb1Ymfjky77sVF5LXF2mutvGJ
            3lEGeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeVB6STZKdk8zMm52ajFa
            RnRvMGIwWkJ2TjI3Q2lKbklvS3BMc2xNd2lVCmJ4VjFncEVabjQvd2VkWFIzYmFS
            RGxZTEtWbHR1M3poVTJVT0hoYXhENUUKLS0tIHU0RW1CMEt1alhwY3JybnhRSE1L
            RGpacWdQZEtZc1RGSnFBODFnbXgwUUEKHS8ukayxP9UX4uIbT2eQ5M1nivLQ5ZEB
            ZTkXguxvqTYuZy+ttZ28KeDedZPwqYFmkZ688XPj4Ac2g6McMQLxbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T18:44:36Z"
    mac: ENC[AES256_GCM,data:aVv4vQWWZlaK/ck7ROE5fLllbRcovUgMj43O3fVWlgUYYrKnpe+K2dlt1SWpQDwfwnZskYlfGtF0Cb3e3ddn8CZZP/bq3iGXc8mYk6z2s/k5FTSftOeHYInpx44sHPBCjuyWT8Kn4ppNa6n3TmtbeI9ok7Axf74yiZ/6PDM0jyI=,iv:/v2HfhxwEh/kx34Yt0csCBbLxHIQyJ67xAt66C4L7JQ=,tag:JrRmlp6WrdjBLGEkbNPD2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
