apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
stringData:
    GRAFANA_CLOUD_PROMETHEUS_URL: ENC[AES256_GCM,data:bQ9xHlToeLWr1XoLoIEXCay2V2lvrVqXcO8glmnG1mFjGk+bo2AcBqToKrQ5/jBSRGb2JDY75YhHz45evLcoUQCYuQ==,iv:cbOzoMKAjMn44wCjZEL1UI1CzU8aVeLEsaI+oDOsvXY=,tag:8vBqfq58b1Ig3dGhvCPHlA==,type:str]
    GRAFANA_CLOUD_PROMETHEUS_USER: ENC[AES256_GCM,data:v4ybrxEozA==,iv:t4RaG/u/8Fy5uQEfOmjiRnEdsOdOS/ZRS+TQjUgGm38=,tag:yWxK9ACxGKBQ+GjK+JQe5w==,type:str]
    GRAFANA_CLOUD_LOKI_URL: ENC[AES256_GCM,data:UyG5VBzqbb+2aVHZuxfsRrjy1eWad5IgzjlF1vbvNMBAIUdM1n+5pQjA3ULbgyODMsk=,iv:hUiXZCo+k8PnXBBpRZS7/pujditF55eE7kiNCnXwZYk=,tag:kOUaoWRh6rNy90qXuwIhwg==,type:str]
    GRAFANA_CLOUD_LOKI_USER: ENC[AES256_GCM,data:fkN10z8C9A==,iv:BTVJMaPaC+hBWgyrAArp7JdSoBkVkyU7wXw/buoiOh0=,tag:m0ZhOSDfQmMfdBI/LEiqPw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyB2SXly
            cWJBclF5OW5ZN0xpYzg3eFViQnBwV1N0RkQwYTc3ZGpYM2hVYlJBCi8yS0kxb2xG
            L2Jhdk54cENoWjVlSW5KNlJOK1pLOURlOFBGdEUwYjdSMmsKLS0tIDFSd2QwSkNS
            ZmtDd1RpN0lEV3A0dVVQaDh2TzJlcGV0M3hUM1U3c0ZXdTgK3jFXpDBEb90I/WcA
            qstsXicjo5zzmEdhkdm6FVJB+lt7+rYSnWNTOi3Zi+ABa957hosCYIzu37WpjBhY
            q+nH9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUUd6VjJhOXYwb1JmNTNn
            WmJoZUU4ZzYwWWJkMTRVa2srczhNYUZQMVNzCkFGVmduSmFmbmFvYmk1eTN4Y0Fw
            OTBkS2FNN1MvWFVNUUhmSHE2eEVSOW8KLS0tIEtRbGhLNkR6d29jcVdqb2JZYWM5
            Sk5YbnlpYVpNZGtjcHNNSTl0OGpZeUEKg1xAKZr+XG+K58F8aVgucl5WT8BddbSe
            ciM989jRneor917ZkaSm6n7Lw7xYTK0D0ScdqLYKlDroKfJRIZGM1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBJbVVl
            SnVMRUlEVE5ac2pwbWxpTWZEcktzaVRaQmpDdWY4SlVFV2g2QkRNCjJ0WmZVdStq
            MThOcUxKZzRkLytqSVU4VVE0dTVjaTZ1QXZvYUdJYklsS1EKLS0tIHJ3RFRkOXJC
            TWMwQVlwSzV6cENPTUY1RjBTNWJJUmxjQVc4T1YvdkFyUm8KhOlQ16oEJRMf0VMO
            +xNqZFEg4U/Rirq+gxWBq1dVXzc30Sm0eih8rRBCCFZTRVUK6PImDsyVdYcdgvch
            6dIxRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMVluL2xHdmxKRTVUMnRZ
            MXVNYko1dHNpN1N5Z05IVDBqUmVra212alNRCkV6c205TXZTYUhGM1IreEdzbXE4
            clFYaGtLT0paa3NFVkNFZEdDOEk1aTgKLS0tIDUxV1d4dWtuc3NTeFBiVFpVdTQy
            bnNSNk5JOHdPbGZsVkNuNW9WRTVaSmcKU9Gy/trDFKl8YQBa5bWC9BcxyX5/uZII
            uNTwn5Zl4Ghz7n3js/psyCuqGxypmdl/wmVd7aTr3VFznxBc0fd2rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd3NXaXFGTklCaG5yaVZB
            WDlZeWNWWUlKRDZmUWlUeGxvZHFydHplNVJnCnpyTjJtY2w1ejhaa0RoVXNzNlFD
            RkYvdURtQ3JYQ0ttYUN0MDNNb0NYNVUKLS0tIFZ3UG1vbnl5MFIvNitoazVsZi9i
            ZWM4VTlwbWd5Q09mam1wamZxd1NGNjAKJ9o6p/75UqhoSeXY2cqugMolsgkeVVVR
            g7uqVo33VpSkQy1NTbh6i+IC4j+nopAugIFD7TGZ1rkjOmZB5Rlc7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YVpBbUV1aFJYMUtHcTdk
            NEdvY21ud2s3TUVVbG00SnZuVjRHVlFZdjNzCjBvWEFVTUFsM1V5WWdZV04rZUFh
            RlEwcUtTLy9ITHZNcWkycDJrMVpYSzAKLS0tIGFQMFlwYVlWUE1zQXdHNU9GSWdv
            dSthTHNqTkFWRkxwYjRtdEhlQjhONjAKB3zm1jpP8w+GZaCXcwEWPsLT3sFTEZFm
            DkYHemY8jZN8v8I1tuYP2RTTs2kGgOzD6rEE0S0MaxOb7mVYZ8TDRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVERhcVBRN0IyWnkzWldE
            UnIzSDFseVl4VDNaVUVwaEgyZjRJRm9tSUVrCmFaU092UlBjakxDZXlnejRabExV
            MUYxRHpmVkpjaWlrbFc0UmJTVDArQncKLS0tIHZoQWh0U1l4aU02ckI0SFo5V0JD
            ek5QV01xMnBUOGNwSWZOUDZCNkRFNW8Kbkjik7brfYymxkP8d6gowwS8mWNh2N11
            PEpUuayXO1eMvO3HKYZW+ep6iDsgwVlqlpFnZpZOFEc16WjcyYM3fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T00:51:09Z"
    mac: ENC[AES256_GCM,data:Phzeg2Qx6pVYQN0o9KaOuGOWFKMB/7QoKZXk7DQfxwNz1D6XlV2qy6uSseYT6ywh5k79O5+lsEIBHqUqvI0amxuYqZQDQmxyLM0tOjBTO5WoWDMXDSObJbloruIPb7Z6ez8r2TL1kzFyZjXix8/0Qj/2jg9xmqOMk6nykzGBQtQ=,iv:k+abo+4psCrFoZg+x9THvJdEx3KsAruEdBsLV26QaOE=,tag:saExDaTPUikIrCToWKt68A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
