apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ei7aN+f/bH4YZhChJs9IAPhs8O6qEN+9tHIW/U9w5LY3fTa4hntdmw==,iv:3XwUNJ5+4DKORSQiTQPCxUdzd94SQ9L6Hvnkq0cFS+o=,tag:dLCAYhZOivcyvGEoMx4osQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA4Kzdj
            aVE2OW1DNHlvVGJjQzBBTVpaTklNZzNXemNVMHhDYlNmcDRvUlV3CldicS9wZjdQ
            bTRoWjVXdXVLeHE0bjRmTG1vbDBSeUtMT1BwUjZ1b1dqMTgKLS0tIFRnZVRCNzdG
            S3FjaHo5Vldva1ZHWEZ6TGk2NGpXeFlPVjE3WUF3SUV4bDQK6mphAPsoWMbqkX4r
            5LlLfi6rxcZkafhfkp1EzuDtnCaT2cB767pqSdq+BOFp6HUZMpVsDyXwbq1n3IKG
            aPyc5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVEVZWGZIOVV6MzFCOWUv
            TytGUHg0eUVNNzFVeTJ0VnUzUWVvclIwTEV3CkdZNUc2R3JHOXhIRDR2THNKeDJD
            a3FpT2x6dmRXb3FFb3pKTWJTNi9PMEkKLS0tIDBGMTkrN1VqeEU2WjdyOUlFUWQ2
            dXM2VVJGd3dQK0RsbEg5UDAvRVBMMnMKQdjBep3ffrM+trm9qbkIYVqERUIhyEsb
            agRuoVXbJHj1p2RWqAIhcBobrq8wvnXYpiNZlTKA4fa1TsnEZOTfLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBnR3BY
            UDVuNWJoZXZDSUw2RkdlUnNFNGt1SzBJYWNqdG5nTmNuSStmb1hVCnB5L09KazMr
            N0ZxNkswTW42S1FOZzFZSDFGWnRQSHJUcXJBMUY1MHp6M0EKLS0tIGFPK21KTU8v
            TkxPVVB6eFM2bHJvdmJGQmJmTjlpN2tpekN4bXdDOWoyeVkKC0qKqhw6eUiB87ox
            oZae+hkp5Bsm/bFLNukquKOeM5C8oBs6qBvFhXWjEXZ7/LrgcfPyAcGN3llzAcbh
            Ww1V4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWGVRRjZBV2FSL1JETXlJ
            M2dpb2tPVUtkdjB1NXd1RVMra3lWQ1JOdkZzCnVod3FtcFhiRlhJM2ZIQjZYaWRq
            cW80SlZWZGRySVptbThsSGJXVVdhdjAKLS0tIEF6aHIvMXEzMGVBWTY5ZGtZREov
            MmI0ci9rZmJQNkxkWUY5cU1lUlo5bk0KAudzjH4SDSPiYxkWmDaCpI6gguBHw/3p
            mLjCdE8AZssfRZXPFBskXYiCr+auPy0DllcKkNxmBPdwmQlq1rEr0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:04:33Z"
    mac: ENC[AES256_GCM,data:HaLWgoZXEB1kCNC5VJ3ZLEPaivEGq+efjAOHI8ZTFYISR2pyuKnhtjVaz5pFURz2Y7foeB5st7AWazM5YL1Zufy+/eGbju8x/DvYeR36YlfvcxnrSrH62Y97nsu+w1SBaI2UEKXhelRFKiazFMMp7mVheZqMLx30PIXFD9bciUM=,iv:OTUNTDPZsA3e807ceApEx/lWxXM+EXGesnuapyPFIAQ=,tag:klZMWpxz1V0gN++dBOX+cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
