- name: Restart zfs-load-key
  ansible.builtin.systemd:
    name: zfs-load-key.service
    state: restarted
  notify: Restart zfs-mount

- name: Restart zfs-mount
  ansible.builtin.systemd:
    name: zfs-mount.service
    state: restarted
