---
#- name: Primary node tasks
#  when: zfs_host_type == 'primary'
#  block:
#    - name: Gracefully drain all workloads
#      ansible.builtin.command: >
#        /var/lib/rancher/rke2/bin/kubectl drain {{ ansible_hostname }}
#        --ignore-daemonsets
#        --delete-emptydir-data
#        --force
#        --grace-period=30
#      environment:
#        KUBECONFIG: "{{ rke2_kubeconfig_path }}"
#
#    - name: Ensure RKE2 is stopped
#      ansible.builtin.systemd:
#        name: rke2-server.service
#        state: stopped
#
#    - name: Demote active dataset to passive
#      ansible.builtin.command: zfs rename {{ zfs_active_dataset }} {{ zfs_passive_dataset }}
#      register: zfs_demote
#      changed_when: true

- name: Secondary node tasks
  when: zfs_host_type == 'secondary'
  block:
    - name: Gracefully drain all workloads
      ansible.builtin.command: >
        /var/lib/rancher/rke2/bin/kubectl drain {{ ansible_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        --grace-period=30
      environment:
        KUBECONFIG: "{{ rke2_kubeconfig_path }}"

    - name: Stop RKE2
      ansible.builtin.systemd:
        name: rke2-server.service
        state: stopped

    - name: Ensure Syncoid timer is stopped on the Secondary node
      ansible.builtin.systemd:
        name: syncoid-pull.timer
        state: stopped

    - name: Push final delta sync from Secondary back to Primary
      ansible.builtin.command: >
        syncoid --no-privilege-elevation --no-sync-snap {{ zfs_active_dataset }} zfsbackup@{{ zfs_primary_host_fqdn }}:{{ zfs_passive_dataset }}
      register: final_sync
      changed_when: "'sent' in final_sync.stdout"

- name: Primary node tasks
  when: zfs_host_type == 'primary'
  block:
    - name: Enable and start RKE2 server on the primary host
      ansible.builtin.systemd:
        name: rke2-server.service
        state: started
        enabled: true

    - name: Execute dr_promote.py on the primary host
      ansible.builtin.command: /usr/local/bin/dr_promote.py
      environment:
        ZFS_PASSIVE_DATASET: "{{ zfs_passive_dataset }}"
        ZFS_ACTIVE_DATASET: "{{ zfs_active_dataset }}"
        ZFS_PASSIVE_OPENEBS_DATASET: "{{ zfs_passive_openebs_dataset }}"
        ZFS_ACTIVE_OPENEBS_DATASET: "{{ zfs_active_openebs_dataset }}"
        RKE2_KUBECONFIG_PATH: "{{ rke2_kubeconfig_path }}"
      register: failback_script
      changed_when: true

- name: Secondary node tasks
  when: zfs_host_type == 'secondary'
  block:
    - name: Enable and start Syncoid Timer on Secondary node
      ansible.builtin.systemd:
        name: syncoid-pull.timer
        enabled: true
        state: started
