---
- name: Disable and stop Syncoid timer
  ansible.builtin.systemd:
    name: syncoid-pull.timer
    state: stopped
    enabled: false

- name: Enable and start RKE2 server
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started
    enabled: true

- name: Execute dr_promote.py on the secondary host
  ansible.builtin.command: /usr/local/bin/dr_promote.py
  environment:
    ZFS_PASSIVE_DATASET: "{{ zfs_passive_dataset }}"
    ZFS_ACTIVE_DATASET: "{{ zfs_active_dataset }}"
    ZFS_PASSIVE_OPENEBS_DATASET: "{{ zfs_passive_openebs_dataset }}"
    ZFS_ACTIVE_OPENEBS_DATASET: "{{ zfs_active_openebs_dataset }}"
    RKE2_KUBECONFIG_PATH: "{{ rke2_kubeconfig_path }}"
  register: failover_script
  changed_when: true
