---
- name: Configure Debian repos
  deb822_repository:
    name: debian
    types: deb
    uris: http://deb.debian.org/debian
    suites: '{{ ansible_facts["distribution_release"] }}'
    components:
      - main
      - contrib
      - non-free

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Ensure zfs packages are installed
  ansible.builtin.apt:
    name:
      - dpkg-dev
      - linux-headers-generic
      - linux-image-generic
      - zfs-dkms
      - zfsutils-linux
    state: present

- name: Ensure keyfile file exists
  ansible.builtin.template:
    dest: /root/tank_keyfile
    src: tank_keyfile.j2
    owner: root
    group: root
    mode: '0400'

- name: Create zfs-load-key systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/zfs-load-key.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Load encryption keys
      DefaultDependencies=no
      After=zfs-import.target
      Before=zfs-mount.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/sbin/zfs load-key -a

      [Install]
      WantedBy=zfs-mount.service
  notify: Restart zfs-load-key

- name: Enable zfs-load-key systemd service
  ansible.builtin.systemd:
    name: zfs-load-key.service
    enabled: true
    daemon_reload: true
  notify: Restart zfs-load-key

- name: Flush handlers
  meta: flush_handlers

- name: Setup tank zpool
  block:
  - name: Create zpool
    community.general.zpool:
      name: tank
      state: present
      pool_properties:
        ashift: 12
      filesystem_properties:
        compression: lz4
        encryption: aes-256-gcm
        keyformat: passphrase
        keylocation: file:///root/tank_keyfile
      vdevs:
        - type: raidz2
          disks: "{{ zpool.physical_disks }}"
  rescue:
  - name: Rescue task by trying to import the tank zpool
    ansible.builtin.command: 'zpool import tank'
