apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redmanager-secret.enc.yaml
  - redmanager-pv.yaml
  - redmanager-pvc.yaml
  - ../base/redmanager
  - arr-secret.enc.yaml
  - arr-pv.yaml
  - arr-pvc.yaml
  - ../base/arr

patches:
  - path: redmanager-httproute-patch.yaml
  - path: redmanager-navidrome-httproute-patch.yaml
  - path: arr-jellyfin-httproute-patch.yaml
  - path: arr-jellyfin-transcoding.yaml
