apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-credentials
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:NlsaDe4mcUYPS4yp+xvHdlDXZo2o3pOA0tjnkiPDucB++EjRGFhn4pfqJrmneB5Fm9N53YH/ripS9X57MrB4Qw==,iv:slFbjyxnwDF6TzqyclT2V+W3pCJTRiU179uffqWhDSE=,tag:YPtjBGXcrmAlbprQDaTwZA==,type:str]
    secretKey: ENC[AES256_GCM,data:Y32sVnFn9DP/4cepemx+Wqdr6nbjzvwZGOAZ/fm7j4s85+1qsSKji/KJkd0c6UAXPpRBvpLsU33ZeCMUh7ISxg==,iv:hpesI61dtgLsKqiv9sdTE6hnHvxkArqeKgO2r8UILA0=,tag:g4G2cad6P3WzMN8990lA8A==,type:str]
    cloud: ENC[AES256_GCM,data:ZGAwXpUJhME6T8yvWxJ5D9P8aaKowfdTDe0Zuw/1wuxh+z4fjUossOPwQoK4bc7sVFkHKWmYs4nxPfVZwqsiRaPHqbFxf30kGyzacFxMkstXwXmEw9yZfUVgvEbh80E7AFLDy7whWZmZcTZreiNIaDIJ64xfqCX1C073cY4Mm4BoIXwNtgknOsSaCBdJ4pHKNiUgTP30DLeoit5GQhbvoGlJ/ogFV9kBN4jqzU5/woRFQG5H,iv:nfypY0jtJWPB6ytwAQQhQH9pN6V9ha6kf5QCdjzXmY4=,tag:BUiaGIJ7KhJOXwyGZ1wQrw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3xN53mZSfvOrp5P7cVRdlNGZdNi1AygUIClf6/ZMi9CVNOSDsFQll9MInp7zJTGLsaUXaclk7hjiCydw5kneCw==,iv:ay66irlg0a4VWd6VzoDKvBr1fEthKEhFY7xzR2qwMbM=,tag:LSpbdkH8dNSzyCOx70Q+8g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GdOz8wyCoOAf6GTgsTaFc9cNVt5Bhz0M4V3wJwkcIM6MeXW8lkybRYOd8mLQNJ+vpt/CWhF4pt2OqAKCdIhoMA==,iv:iKDhY0VPiFF4KP9H+4I98tLghLTQrPHbXG4/+fj4Kjc=,tag:yJh8REGym5rQUiALKrXtaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyA2RCtP
            aEN0SUtVcmJJL21hcTZBNFBXN3QxTFpQbVVyenB1aGdJYU12WVRzCkpZNWNJOExT
            ZFdGWmVzM0RwSnRSVmxXYks4SG9vTnV3M3ZUZ1g0ZlBOeFEKLS0tIFNtMU0vS2ZS
            NzhUeWFnY0J4OHliRzZMY3lFSStxakdvSkVxOG03R1g3Tk0KfXf02LKLyydnUqHB
            +PCO0jVMIu6FUfZ19t+Bh0X7o/9KeSx8rKRjPDdyek/ZnwBpqXVwLwJRsx0MD+NR
            31QcvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUnp0YkUzZ2NKZWhsY0E4
            NzY0NXVyVjF4OCtBUHBEYXlyendHTFE2VHlzCmFSVWNnTDNLMzhuajh1bUtFeWU4
            YldKUkNTeFN4WGxxYWtqT2hwSTZETFUKLS0tIGdEU3JjZ1oxS2lnczgzbzJxRVF3
            RHNBd0RSQVlwOS9TeXUvQ1Zhb1BuRUUKaa6cJb8/Yj/jG9GeWIWH7EAmykXLuwFc
            dcNOAb/jzA/BFVF1E5mc7jVCPMXKCGGz1qpXn5JZUEtG/ZoN2Qv2Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBsTnYw
            K29uVVBpeDdqUEs2V2Mxc2R6R3JDbzRjQTJ0U0M3RGpZYWFJMGpBCjZhRGVKN05B
            SE8rYlZPSm44K1JaMm8rSzVJQ1h4bDR5SThFQWQvemJnb28KLS0tIHJaaFJzZzY2
            RkE2dkZlMXhvaUVZUEZsSUZkME90bWpueTVBNnhuc1ErRFUKxY0NKfYNZlxH6f9q
            eZ5B1RSYOYXCCwAEeXnJ2cX0pn1Ik99uuHCKDqnrxHZP2GqyEloSqJ9X+qzWGkUv
            WJM8QQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL0s4SFRGQ3pRRG9KVnVp
            THJXbk8zKzk3cjBxSWxMUDBLNjZpa2JzSjNjCkNDek9leS9YTWxHeUU1cGkyKzN0
            Um9YdTdFSk81VEE0WG1OL21GSjJOSmsKLS0tIDY3aVRtUTJ2b2s2bk50QmpTYTNC
            Tmg0WUo2S2xLSGRCdTlsaHhTbWljU2sK034d3uXey45PlQmPjZjvPbJZAaeSgn4n
            NJ1pg3MJYboAZdRJ9sknLypjlnBAJIuFP3zLqWHU5Sihdtdnoj66uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3ZLNlpCZ2ZiWHBPMnRH
            eDZIVDBhdVRoeVp2RFRiVDlHR3U5Z0tsMFM4CnlPOGRJWk54NVk4eHlGdjZuNm8r
            V2x5Q3ZxNmF2eExIOHYvT2tiYWxXOTgKLS0tIDdmblplM0gxVVZZZDM4c2VSUFo1
            M0NkU2d1cWY1RmFVYUhJSDBJRWdqZmsKBHx7EqOpupo5sW1TJPE1cdceb5iBEidZ
            p9vdp65VKv96Yo+lm/zA3DEveDW2VLdpT49sbLn13SCbJasSHK3xDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:11:17Z"
    mac: ENC[AES256_GCM,data:sLQGQbeDGThiOVMxOLn6VEQiQreHs+gla1wBmkkowp92OkUkVe41ht2+3BdYOvUo924bg2c/JF94G8oo5rXoFIQQcZe/Ch66GOxLvnqAoTtg0OxE8qmkA7leztdiT9Cu1DLEZ2+cqEosVp+EFYhLvbe834YkxboeMHLScxrZKEc=,iv:RwiaMioWEKoUhHXtvj65qClbgMXTZn4akx4usQkJJnc=,tag:A6XLBv01GCxkWD+TeITVNA==,type:str]
    version: 3.13.3
