---
rke2_kubectl_path: /var/lib/rancher/rke2/bin/kubectl
rke2_kubeconfig_path: /etc/rancher/rke2/rke2.yaml
zfs_zpool: tank
zfs_active_dataset: "{{ zfs_zpool }}/active"
zfs_active_openebs_dataset: "{{ zfs_active_dataset }}/openebs"
zfs_passive_dataset: "{{ zfs_zpool }}/passive"
zfs_passive_openebs_dataset: "{{ zfs_passive_dataset }}/openebs"
sanoid_conf: |
  # Filesystem Backups
  [{{ zfs_active_dataset }}]
    use_template = active
    recursive = yes

  # Templates
  [template_active]
    frequently = 0
    hourly = 24
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes
