apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-credentials
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:AsjBKM2jKwwigdVfl58U3/RmFHnEGFRaYoQYy8A+sazfScGPATzJNxqZHqRjnwYwQFluvZVFm1t02++i2vDsQw==,iv:CuPRepF68vWQQHpIaSU/6BWqCn28tSowZWK0Yc/9BP8=,tag:paCGmn5ycvuNhTIxB/GDKQ==,type:str]
    secretKey: ENC[AES256_GCM,data:7QEmCdeE0J6enax9WYAcA6mnRgyzMbzeevL1D0SvZZoRxIfzS9gspwRYV1ygUuxgfyo/MVITY0aSU9hYkGuJ0A==,iv:X7w3p3ayVEDEtDJWb928d47EY0fCXjerxi6TjTu7czs=,tag:2B4upQzlaHEaudilCHETcg==,type:str]
    cloud: ENC[AES256_GCM,data:jSBNaGWK+O/rLzFoZutk4sMvTHQYXH3aAXePr9uPtZqZFjC4SCZPmpEwcwK4p7ykOMIKObnQh1E5mg0qojNEnWvI4L2BRPLVLgr/5WaFQyr5t8Kur6j+Nlx1HInpEESijjQ2X2LkATNVbVTyw3jceDcTS4HF9F/F6KdhO89xmfRgSb7jctmTwHuG1kWoGXqTK5cic0jE0kUVkcAfvEKydkJPgDEOjaq3e5/oJeXEptMBL/9u,iv:RYJ0R1LvQkfrvQvEVvV7KMk8ivyO18FR+zpqsBJoLfU=,tag:AhttilhgiEJog6MdJj6tZw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WtCrC+gEGulBHwTv03IC9t5bD2k75IBgLWoJ0z8lAdvml8/m0bmJIRU5NLpvLiPP79U89Zkb5ELe/i5CZ5A0lQ==,iv:KD0mJLWwIsZWmbWtwFhh51cp+mUApU+9ad+FJEW49Vo=,tag:8KN41g2B8V1igER7IVUHOw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oAYXeDKHrLhgo0MBRIvwb+qs+ywDJ3+pRl127BT0mKn/OseowkgjlNPXJDcMwL12ahQ8sOnWrtHfjTDAUzCN4g==,iv:35bwDZo5/KA+ot0HNRbe9qsMasSHJHX8q2QrUxbrqI0=,tag:i1LF8fsr8sDy61muK/HiOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBGVWE3
            cmJxajJ5R1pMa1VqMFZtd1RlajQvRkJyMW03TGVDR1hiOUpQZnlBCkpQZndGekpl
            TjAvYm5kcytJZVM5TmNQc3U3N1NpUVU3d3c1dCt4TlFkS1UKLS0tIFAzZlZtM1Rx
            Q2JzZUUzZGJnbUdaUXk5Q3hXbENEd3htRFZEWUMybzN0UlEKmZuRMPuQ5CO3IUPK
            h9OwMsZV0BePcADSwQrCITerxwvis2N+lUxY1prM8jDpvlcWV88aZr+NtWW/U9gD
            7MfGDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGFQcEU3N3FwalBEU3cz
            RmNmb0IyWlFIYjNEYzBESmVJdFBsd2RYb1U4CmE5a09IS1B6cU1XS2M3VTA5UHFY
            T1pscjRNeHdYMVFiM0tDWVVZTTJCVGcKLS0tIHlaWG1aQ1BqTnY2cHlpVjV5WkRa
            YkVCNEM0ZjdFSzgwdk5ISTQ1Q0lkamMKalTMRvqmxkOU408yP4VFCWXNdEVM5Lva
            6mFV8FMnuCkAaQmVovBxd8Acv2VV4/W0QXGl7vVRQhc8Of92fiBNWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBJTGdY
            cmhJZHE0Z2I5MDdNdnhMWDNrTm5kTWJYeU1hL21iYXRHZFhzN2swCk9haTcyMXBn
            QysvSkduWk9aWk03UTl3dEJnS2VVbU1nZHNyTmoxWjEvUDgKLS0tIHFUSjJFSUl6
            aFdIbXpESDcza1BZL3V5TXJQK0pNRkZVaDVISXRDT1Z0aFEKDW1u7y9a7k70TPyT
            9sZndf0tpqcFsWJHb7wAVDbylPH3JVLNG9bK5CCWk5yTBqgAI2CBDMcFugt0L7JT
            s/lZEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1oxb041cUZDeU1nbEhN
            Yk03THhyTmc0Q2NMSXRUck8wTzQ4UHJGVGxVCjZjMEtlUW1Xcy9XamF0WjR6b2Jy
            MTVSR2dxN1NBZThxRjQwdnArMkl0SUkKLS0tIG9PYUU4Y1VTQXF0ODN3UzdwWElL
            QjZRUW5PbEE5TEwxSVRzazlvbVF4dFUK0m9fagciAUPrPe7YWSkQq718RLL+/XFw
            z2QwrpoXe4mGC8RgcUQlmtjdOLJ9K4D6ezwetujHx60bkVaEX5rTPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZlM5N1ZNbTllQVQveEw3
            RE1mVVdsdDJpVzEzZTlERExzZ1ZWamhlQnhNCnpBSlZaaDFSTHZ5dlZ2eEFiUkVK
            RkFoR1lxbUlGWkpsQWZ3aHZyb0ZRbVUKLS0tIDlKam1zZUw0enR3YVdVdkRLQjlw
            eEhMblNXNEZSbDY4YndYQXVRL3oyRncKC33heetWlbFXEqXYD49SduP0KTDT6BTO
            hDTkOr3QRJphYBDiJNfGcrSUMbaeWiOuhZsxBYDqma0cotZydc6OfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:10:05Z"
    mac: ENC[AES256_GCM,data:DFyN9Ecp00aT/CP39bLObZ7pq8Dn/rezaWcDRfKsOEjO/XHYipHq6qTalnRB9kQvgAWYbUXYMhCrJuhJDlYdxdqqxuxF+AanZG6yAHn/XiNrqA8UuPtl7WgjvWSvLRrYPl1h3lgiChcdXi827BRPn41xll6nGJ8XgMGNDDfnL64=,iv:NgBnffp8LaWtj3kguzwqrvJZfKaglDAnbS7ZujGHfbU=,tag:yO0Fz6F+/vAS9UzANZFfmA==,type:str]
    version: 3.13.3
