---
- name: Install podman packages
  ansible.builtin.package:
    name:
      - podman
      - slirp4netns
      - systemd-container
    state: present

- name: Create user {{ service }}
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true

- name: Enable lingering for user {{ service }}
  ansible.builtin.shell:
    cmd: "loginctl enable-linger {{ service }}"
    executable: /bin/bash
    creates: '/var/lib/systemd/linger/{{ service }}'

- name: Copy config files for {{ service }}
  ansible.builtin.copy:
    src: '{{ config_files_directory }}'
    dest: '/home/{{ service }}/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Rootful - include tasks
  ansible.builtin.include_tasks: rootful.yml
  when: rootful

- name: Rootless - include tasks
  ansible.builtin.include_tasks: rootless.yml
  when: not rootful
