---
- name: Install podman packages - {{ service }}
  ansible.builtin.package:
    name:
      - podman
      - slirp4netns
      - systemd-container
    state: present
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'

- name: Create user - {{ service }}
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'

- name: Add user to groups - {{ service }}
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true
    groups: '{{ quadlet_append_groups }}'
    append: true
  when: quadlet_append_groups is defined
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'

- name: Enable lingering - {{ service }}
  ansible.builtin.shell:
    cmd: "loginctl enable-linger {{ service }}"
    executable: /bin/bash
    creates: '/var/lib/systemd/linger/{{ service }}'
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'

- name: Copy config files - {{ service }}
  ansible.builtin.copy:
    src: '{{ config_files_directory }}'
    dest: '/home/{{ service }}/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'

- name: Template config files - {{ service }}
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/home/{{ service }}/{{ item.path | splitext | first }}'
    mode: '0644'
  with_community.general.filetree: '{{ template_config_files_directory }}/'
  notify: 'Restart {{ "rootful" if rootful else "rootless" }} container'
  loop_control:
    label: '{{ item.path }}'
  when:
    - template_config_files_directory is defined
    - item.state == 'file'

- name: Rootful - include tasks - {{ service }}
  ansible.builtin.include_tasks: rootful.yml
  when: rootful

- name: Rootless - include tasks - {{ service }}
  ansible.builtin.include_tasks: rootless.yml
  when: not rootful

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  changed_when: false
