---
- name: Install podman packages
  ansible.builtin.package:
    name:
      - podman
      - slirp4netns
      - systemd-container
    state: present

- name: 'Create user {{ service }}'
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true

- name: 'Enable lingering for user {{ service }}'
  ansible.builtin.shell:
    cmd: "loginctl enable-linger {{ service }}"
    executable: /bin/bash
    creates: '/var/lib/systemd/linger/{{ service }}'

- name: 'Create necessary directories for {{ service }}'
  ansible.builtin.file:
    dest: '/home/{{ service }}/{{ item.path }}'
    state: directory
    owner: '{{ service }}'
    group: '{{ service }}'
    mode: '0700'
  with_community.general.filetree:
    - '{{ config_files_directory }}'
  when: item.state == 'directory'

- name: 'Copy container config files for {{ service }}'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/home/{{ service }}/{{ item.path }}'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'
  with_community.general.filetree:
    - '{{ config_files_directory }}'
  when: item.state == 'file'

- name: Include tasks for rootful container
  ansible.builtin.include_tasks: rootful.yml
  when: rootful

- name: Include tasks for rootless container
  ansible.builtin.include_tasks: rootless.yml
  when: not rootful
