---
- name: Install podman packages - {{ service }}
  ansible.builtin.package:
    name:
      - podman
      - slirp4netns
      - systemd-container
    state: present

- name: Create user - {{ service }}
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true

- name: Add user to groups - {{ service }}
  ansible.builtin.user:
    name: '{{ service }}'
    shell: /bin/bash
    create_home: true
    groups: '{{ quadlet_append_groups }}'
    append: true
  when: quadlet_append_groups is defined

- name: Copy config files - {{ service }}
  ansible.builtin.copy:
    src: './{{ node_name }}/{{ service }}/copy_config_files/'
    dest: '/home/{{ service }}/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Template config files - {{ service }}
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/home/{{ service }}/{{ item.path | splitext | first }}'
    mode: '0644'
  with_community.general.filetree: './{{ node_name }}/{{ service }}/template_config_files/'
  loop_control:
    label: '{{ item.path }}'
  when:
    - template_config_files_directory is defined
    - item.state == 'file'

- name: Rootful - include tasks - {{ service }}
  ansible.builtin.include_tasks: rootful.yml
  when: rootful

- name: Rootless - include tasks - {{ service }}
  ansible.builtin.include_tasks: rootless.yml
  when: not rootful
