---
- name: Rootful - Ensure /etc/containers/systemd directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: Rootful - Copy systemd unit files for {{ service }}
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/etc/containers/systemd/{{ item.path }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_community.general.filetree: '{{ config_files_directory }}/containers_systemd'
  when: item.state == 'file'
  notify: Restart container

- name: Rootful - Create podman secrets for {{ service }}
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.dict', podman_secrets, wantlist=True) }}"
  no_log: true
  when: podman_secrets is defined
  notify: Restart container

- name: Rootful - Start systemd unit {{ service }}
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: started
