---
- name: Rootless - Ensure /home/<service>/.config/containers/systemd exists for {{ service }}
  ansible.builtin.file:
    path: '/home/{{ service }}/.config/containers/systemd/'
    state: directory
    mode: '0700'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Rootless - Template systemd unit files for {{ service }}
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/home/{{ service }}/.config/containers/systemd/{{ item.path }}'
    owner: '{{ service }}'
    group: '{{ service }}'
    mode: '0644'
  with_community.general.filetree: '{{ config_files_directory }}/containers_systemd'
  when: item.state == 'file'
  notify: Restart container

- name: Rootless - Ensure a polkit rule exists for user 'ansible'
  ansible.builtin.copy:
    dest: /etc/polkit-1/rules.d/48-machinectl-fast-user-auth.rules
    src: 48-machinectl-fast-user-auth.rules
    mode: '0644'

- name: Rootless - Create podman secrets for {{ service }}
  become: true
  become_user: '{{ service }}'
  become_method: community.general.machinectl
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.dict', podman_secrets, wantlist=True) }}"
  no_log: true
  when: podman_secrets is defined
  notify: Restart container

- name: Rootless - Start systemd unit {{ service }}
  become: true
  become_user: '{{ service }}'
  become_method: community.general.machinectl
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: started
    scope: user
