---
- name: Rootful - Enable lingering for root - {{ service }}
  ansible.builtin.shell:
    cmd: "loginctl enable-linger root"
    executable: /bin/bash
    creates: '/var/lib/systemd/linger/root'

- name: Rootful - Copy systemd unit files - {{ service }}
  ansible.builtin.copy:
    src: './{{ node_name }}/{{ service }}/containers_systemd/'
    dest: '/etc/containers/systemd/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Rootful - Create podman secrets - {{ service }}
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.dict', podman_secrets, wantlist=True) }}"
  no_log: true
  when: podman_secrets is defined

- name: Restart rootful container - {{ service }}
  become: true
  become_user: root
  become_method: community.general.machinectl
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: restarted
