---
- name: Rootless - Enable lingering - {{ service }}
  ansible.builtin.shell:
    cmd: "loginctl enable-linger {{ service }}"
    executable: /bin/bash
    creates: '/var/lib/systemd/linger/{{ service }}'

- name: Rootless - Copy systemd unit files - {{ service }}
  ansible.builtin.copy:
    src: './{{ node_name }}/{{ service }}/containers_systemd/'
    dest: '/home/{{ service }}/.config/containers/systemd/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Rootless - Create podman secrets - {{ service }}
  become: true
  become_user: '{{ service }}'
  become_method: community.general.machinectl
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.dict', podman_secrets, wantlist=True) }}"
  #no_log: true
  when: podman_secrets is defined

- name: Restart rootless container - {{ service }}
  become: true
  become_user: '{{ service }}'
  become_method: community.general.machinectl
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: restarted
    scope: user
