---
- name: Copy systemd unit files
  ansible.builtin.copy:
    src: '{{ containers_systemd_directory }}'
    dest: '/etc/containers/systemd/'
    mode: '0644'
    owner: '{{ service }}'
    group: '{{ service }}'

- name: Create podman secrets for rootful
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.dict', podman_secrets, wantlist=True) }}"
  no_log: true
  when: podman_secrets is defined
  notify: Restart container

- name: Start systemd unit
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: started
