apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bootstrap-client-secret-password.yaml
- bootstrap-externalsecret.yaml
- httproute.yaml
- keycloak.yaml
- postgres.yaml
- terraform-client-secret-password.yaml
- terraform-externalsecret.yaml
- keycloakrealmimport.yaml
