apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 1
  enablePDB: false
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: zfstank-non-failover
      resources:
        requests:
          storage: 10Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
