apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-rw
    database: keycloak
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: keycloak-base.home.parents-basement.win
  proxy:
    headers: xforwarded
  bootstrapAdmin:
    service:
      secret: terraform-bootstrap-admin
