apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
  name: velero-backups
spec:
  clusterRef:
    name: seaweed
    namespace: seaweedfs-operator
  adoptExisting: false
  anonymousRead: false
  objectLock: true
  reclaimPolicy: Retain
  versioning: Enabled
  owner: velero
  access:
    - user: velero
      actions: [Read, Write, List, Admin]
