apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: velero-creds
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-operator
  identityRef:
    name: velero
  secretRef:
    name: velero-s3-credentials
