apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wen/uPelvlxpR8wJmQddgVXrehjOlEXihU8zJ9TqkBGeoSAcCUt+pWbgKE8=,iv:OrLQYIP1bUQqsBpv1ZOYH4q4FYXlle0rddcSX33pA7Y=,tag:hx32xE3qKDV+G8hODi5y1A==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:KK++15nd2rXM7eMDyAk8Tr1gbLarVVpKTzL3sceO+Ms=,iv:G3fJAzAf2qJqXTqcwEJBVFMxsdJN1nEGP88Twthqeig=,tag:vuz/GigT8d5SKCUP6LIq4Q==,type:str]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:AAxLfpc1jWcOuLOtKBbjwxYB6D5FfV+vLzhYlpPz6Nsbj3/X7ENTgr8vueRE6TrcYznbufHLzD6L98jrWD5ByycsKYoUjqyDq8m+KtV/PjfVzgxUwQi0BIzLfpk5UUFf0D73myeFBNa07Ys794PGfvY=,iv:BF1YpX7pQTOKkDq7HeggoERtWuXUGsYKHci7i+2uIKo=,tag:PsaTy4yQPgr+E6SpVHlEJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyAvRmQ1
            RFNUVkJ2a1pTdFJxM0pkTlpaMzQ5OHVYN0JFWTRqeVFHYUdtY3hrClVETk56bWhI
            U2FDaFExUXdMbU45ZmFMQ1RHTDlIbndibG0xMm41ejVGZ0UKLS0tIEpOVElCNWx1
            Y2J5NXFJclVPNFhlWm44dzhsMDAwM2dNUGVuc09uTzNGVjAK9is93kaXHEz+NHUR
            IcvAR1EEMAh3WoAKT0Y99NcdThuAR0m6qQRWlzmkFguubVGnC3KOgrDUO6V/fYyj
            TBtPLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZUI1R21lQ1RJOWMyWTVr
            K0d4cndIVG51ZVV5dTl4VEM2NVBrdWU4VlF3Ck1jMlRObVBFMU5rekJjMElYcnRh
            OEhybWxDUEhCNTRpTWswVHAzdE54b0EKLS0tIHY4ZXNDUTdEbEwxWnJ6YUJEOVQx
            V1lQcWNRYkxyUlFqeWw3d0xHTG5CNjQKgsiWRAIqQeS6MBJHPNnAtL3jv9lIcnt2
            8YLG9RwJR5bq+QX8oq0RUIoa8I0MeVDcXZwlTOKT57LS+Dbr60KC7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBIK0Nz
            b1hnVjRMT21LOVdoQi9INnhEZ3RmSlN1U3J4ZFQ5WU0wSGE3V2gwCnlvUlpRUUs3
            ZlZrbG9sRlR3SkxBSFVtd016VlJHcHM5R0lKTDRtYXl6VVkKLS0tIGVJckdCVTkv
            by9lVE51Mm5ZYXpRRVRlTHN6bEFaalRGN2hzdysycFlXRTQKtAyp2lK60bO+Joi1
            uZOcRgPkp8KeEqdLpfDrzwat96/7zISZ1Oy5ZoOzCZpXeTENz2pS4UiEkE4VI0/h
            0BbhLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYzlzblM3c25uSm9qSmhu
            V3FwSlh3VU0vQ0xOd0N0UHFCYmlRajZQb0ZVCk52RzF6VktrSkdZejBNMXBJdXFT
            NlkrU3BZbVRUQWFOdGFjdHdsSTluMjAKLS0tIGhiVkFTOEZtMkFsbkk5cVMxUmpj
            Yjh2WWNGREhRSjVjWnlSOHplTzBGZW8K/jxIozK9J6OtjTIJPTZd93kdXOy6/sUY
            Q/+sFn6RlGSXt5lJpqDH3JsUeoXLK8JMh+9kbvTQiUXO7Db1sNx8qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T20:38:17Z"
    mac: ENC[AES256_GCM,data:wDLcoG3PRafLMpOBsOt6p8vXOuNMTRaaeHNnhMBeBTx8v2kawjkM1E1AzxiLPenZsoJEEMNYAfgSAfOWM6Xgc9iDiU3fScn61D/+RCUkFzE8FaoA1auMZ26APiGFJIzLMU8EdSMxz5Dn4aKVyaHNNpNLOhtM3+XzcIOObQF7eDU=,iv:4+1n4JEC1kHPbXTMoyHKmT1ZxFvg0TB4uh6yR+n+mp8=,tag:mDdjDfOH4Jd0GW8dQKr2Zg==,type:str]
    version: 3.13.1
