apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/configs/cert-manager
  - ../../base/configs/envoy-gateway
  - ../../base/configs/openebs
  - ../../base/configs/keycloak
  - cloudflare-secret.enc.yaml
  - eg-sso-secret.enc.yaml
  - keycloak-pv.yaml
  - keycloak-terraform-admin.enc.yaml
  - keycloak-terraform-bootstrap-admin.enc.yaml

patches:
  - path: patch-keycloak-cr.yaml
  - path: patch-keycloak-httproute.yaml
  - path: patch-lets-encrypt.yaml
