apiVersion: v1
kind: Secret
metadata:
    name: arr-secret
    namespace: arr
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HZXWRZq79n0DyGw+XzBSnVFMsMNiV6IWWPYT7iuzme/YKAjVl5oZnEV0Qt0=,iv:2xpWM1S2HTG/AK46xfxVZMN/aFDHnCkHGDVpTH8iI5Y=,tag:0cR9PoPvNw1Fju0541cU/A==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:rOBoY9SouCCJidvO4h30kmQiS0ePEuQvig619wQaCdk=,iv:Tc9pyqgJ3HARCDB5UoIuwsGnF5KYEgS7RWBVAWfrHZg=,tag:ixLF3TkFqnL4qPwZp0nZ3g==,type:str]
    #ENC[AES256_GCM,data:e80Vv0VsFGss4BXxl4MGap2FgwwdIRzb6Z4yTKkkaZDca+2czlaPPkTM+j2vrBwTVD17BU9e14xavkFuVI8E2U94S6V2oZNLYvcw12MGCsI/gUU=,iv:+exnJeUly7+haD5UQeT6sPmz7m292sochGfMVcr2b8s=,tag:YjWUXUgwVM8TE/Tt7hmL5A==,type:comment]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:OOZa,iv:5TgDcXnGRRH+uI6A1xMbq0485UzTPsTDCAPBlgu5gLQ=,tag:H6QHxUFTfdw1wEJAxQxeHw==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:G4ZgFEE1EdA0ERPD/a5EYNUqlWEgr2uFKJnDbmbC6Ow=,iv:3lPusfAt7jLhtSVjwCrwYRMvbwNslW0ieOc816dOrX0=,tag:0l3UKxCGSS6W/4WNuH3y6Q==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:FdpSPoN0prVXTsYImiMaX20xOzJEhWj8x7W4SXjnMjw=,iv:VVbjcDA2C3JSlpn7Dgb6wNb5B0sywX1pXLrGtSBM0Po=,tag:XC8+zkfJ5kzZEu8tsOJHWQ==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:23puUuk0c7Wrf1m77RaVRioRlIsEVbzz/8vA6hxcKzM=,iv:iJXHEfSQlknZFwVZI3eCdENdPH3CQFqhyrWQNAFJpbE=,tag:cqiI7vsWP+MzbJ6llulR2A==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBXUHNV
            S2QyM3M5Ulh5QndsNFlzUzJVOG03aVhqdHhjV0FsVUFjZXVqVlNjCk1Qa05ZMUlu
            NmZzSFlqZmZCMGlpOGpyaG83Qnhxd1pEVW05UFNiS3IyZmMKLS0tIEF0aDVhM0t0
            SVA4c21aRHJrcWViVUc3dmRiTjlxRnF4aVdaNDAzVzBIekEKMBVj9ggp2kc0uAsY
            3E9DJcleenXq8i4DUaBzRSNg9Cy3FOD+yBSbAGT3KG2JpWI/7UjiQ3eQZV7yk0J2
            O+H3Ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWXFhRC9IOG1DZGVJNE0y
            M0toZXBVTXl3T1ovS3NRbG5NKzNOaDZ0OG4wCkFsTnJzUzlyQ2ptWURJbjFleTEy
            TUorUTFucU5hZXc3c0NzRGRyd0V3YTQKLS0tIEszMkJXUGluUThmUUFiTnhrbGl5
            Y3d5QzVCNWQxamRXeTRPbHhPaGM2azQKLyxjiVgMuBPBxgveOjHTNVavBvbdtCZd
            Jub07+vv7Yy37tXQG3Fb4G4TZoVisDcQnlhzO+Gqb46xNYqA0QIacQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBBeFlP
            VzdDRDlXSlNMWUpTR3o0TnhGVHh2TUszYlZkc2lkZjQrQ1MxSnlZCnRUa0IyeEli
            bE5LSkU5bmEyckZmU0hxTHNwRGg4dGFzOEpRdWtNRW9HL0kKLS0tIDJnNTk4UkZ6
            QXluVG5JSlBEOS9PNmxLNUR6QnVPZ0x2bUVoalpmSHo5ZGMKfYcMNpzbPMchlxvE
            FWPzOTqtXZ8CVQb3QpANvyFRMR/kwXof0YL2yqIkzQeN58ehyKub2wQ/6ERHVdG2
            7/Q8gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdjlkNUNhS2IwZDEvaVl4
            YnNlSGF3SGRodlVIaE1GNmhTVmVYbDh1OEhzCmkyaVRtYnk4Q21nM0dtN3BvalQr
            K0VBMURwNm90M0k3cG16a2M2cWY0VGMKLS0tIFl4RndIcnNaeEZBditQOXRuR0hZ
            SXQvRXR6KzhidU5vRXo2azkwNFBHYlUKv1luVhj81UtCCj3ZHWwtu5egT/QmH/06
            9pjx3r28oUv1MN80vkl9m4JVrN70BCX+MUANxifBltvD16MfjyhzwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:14:39Z"
    mac: ENC[AES256_GCM,data:asbauo/Gix63VD3GeHdDxh/UxRBM+klUH4Vd5EaE0tKPz7lcFv/45HSKutUanYW5BXb8++qDrmFa8xvabVoPDZCqxs+ao33PcmWzn4r9X9I/NMZKQlxrKIJemtuQouPLMRt6W5urPmGZnoBVT+LoBvteOQBOhge2e0BKqBdHn5g=,iv:ZCai2w/VCunTKqHyH/Lhwq8FEqJZD+go/HuZGU97RQY=,tag:2KPMofonloHA7rJpfhTd/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
