apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
    namespace: redmanager
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:iSXKUlBl7IGi7W5KweITPx3naTFdvxAmUr4acOd4lDcq0B0xSrDxsti3ceE=,iv:ZRAKq4aGHYeN4agCpGsjifjSBKw2o0Hlj9u/Txs3SDg=,tag:F+MEojMBUKAZAjDWngWLKQ==,type:str]
    TRANSMISSION_USER: ENC[AES256_GCM,data:2RWoipUjNXb7fA==,iv:jub1+iiUphEW/qEmP9N7DZDZZSjxCqGjmdiRj24vS4A=,tag:eYjt6LvYDirtVNphrW5kAg==,type:str]
    TRANSMISSION_PASS: ENC[AES256_GCM,data:tgvcrQMlR6ILKYvUG3mx4tgmQpaaJ25HmzYwswXa7JY=,iv:TWIvbBMpR8gFer4y+SUGOwu1AbG+DxT97GXZJ1g2QeY=,tag:gPwN10w7yZzLVC2oUKRO9g==,type:str]
    REDMANAGER_API_KEY: ENC[AES256_GCM,data:mnZRAPUqbhxJDpGWhLnkYxC39HyfIN1evjC0vuHo51s=,iv:HUlHCIc+DvnnfMCXiTRM9eOfPvNlZT1VD1a/lQza8TU=,tag:Q/bQ8fkyangNiK6N+OFCAw==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:1jEpY3IpCMz6tmB70A1/rZ1p5dcqVohF67w9T1rcH3Fppj4yqLUUwhQ=,iv:4bfkWJ0Qtb9V1xfiyjA7SDah/N4I6wYykJVIqx4PjoU=,tag:1gs7KTyNafS62tqW6UyFww==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:tEN+I1CO6xCtAOjjZjvFUT9s/Yy+fRNUnponnx4E8PM=,iv:uC2c+jmB45DRuAh0ko5TdB9vqc05AEvovRXrpOYOxY0=,tag:xaDSAmPJLCMqFtGVFxQ+bA==,type:str]
    DB_USER: ENC[AES256_GCM,data:k4iI7oAYXncqUw==,iv:wDXBn/JgAtRytokDct7iKYa9Ajb2Olm8RP8s6I9LUAA=,tag:/LZCPtXIoJQo5be+vwrwkQ==,type:str]
    WRTAG_WEB_API_KEY: ENC[AES256_GCM,data:Sj1o7zXKngFyowlL4kCpR+puJf0yBq/PgNyjldsICb0=,iv:1dvwc0me8CqwNVq5Mla9cON8uZ4Rz2yR2lNZEfJuryg=,tag:/xeeuVM2NOF/dfhRxsKwWA==,type:str]
    ND_DEVAUTOCREATEADMINPASSWORD: ENC[AES256_GCM,data:fkFlHIOfJHPS6mNfwnTkU5mS4oM/nL5dljIvvQIW5Js=,iv:/OdO8+EB78YHKw3AhmyOjvDNwedlWHkus4AUfmviiGQ=,tag:hg83GrFP5yF40wgZeuy3HQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBaaHJT
            M0hUcUFMWU5HMTE1OHBkU3I2NEdZMkJKNDJNakU3K2J3dGJvYXcwClI1emNqVktR
            am9OZGZIakV1RVd3TWpXNmdsZ1cyS1BIRVNnQlZnTGVIYjgKLS0tIDRwekxYZVNQ
            dWhzTFFaalpLY013aHNnNitKZWdFNWJyNXpxNzM2UVNUUE0KfnkAw0vq/0deZIoH
            XfGfl4vF9bWmK6h0eluQMr07nYUIsK23xgEAlvDMu0CcGhOihRzhae2A/FOd1n+i
            c5gU4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWkJnUEpVQ0s0eFVtNDBO
            aGVQeDc3YS9wSDBnemxxNUNlU3lySERHeUVzCmdCODFNTXpKYnYwWjFITktEVFlH
            bGlsTVJ1eW9vNHUxOFVKMjlOZ0QrUkEKLS0tIElNV0M0T0krZ1Z2ell5UmdRVVhm
            cTlJMFZvbC90cm1MZGtGZjYvRXhUZDAKVneqPagB/liNcVDdog8GyPTMZBZ47GQJ
            fvYBxSancb4XwZ9THRWoxjphoUDfLDyndZwTnyl5lRzzaaQavZO5Ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSAvRElm
            ZnBFU1dHWlppRUVpckxDeWJiY1ZoakdseTdtL3ZUMDU2OUdnamtnCkp1M3hPSVdK
            WGw0WVZMdWlHbXN3SVl5aG1YVHZqbmFDeDkyRW82ZUZZZGcKLS0tIE5ubU9zNXhu
            TFhveE5Fdk9xWVZCd3g3c3FSbnFHb0VWeVJuTkZqMjRqaU0KKz4dkeg77CLEO0g+
            LvAorRb3O3hlGaZOMBYhPouNKOZqvsMRKK17gn8TwCtIDzeiOpSjVK8ZAiO1Geif
            rTt3Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINVBwOFhaZ0hYV1VWR2xj
            Wk5YdkZzMVFBTUpkZlFXMWtqWE9QaVNuNm5nClIzS1pWSzlidVlqMTlibklCRlR6
            UWlsdXVyd2Y2NWZ2OW5hWmliT1VHUzAKLS0tIFR1Mi8rd05vektJcWxodHBJdjJU
            UU4wajFzbnBGekJFWm52cXVEOUg4SzQKnyhE80SMhVjXl6Ef0V6h1GXLjEsYQYAW
            5CZkagf4Sona9W7f4ZMxeaHr8xKMx/24yNfey3RPNG4XaWLXL027Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:51:36Z"
    mac: ENC[AES256_GCM,data:UB4S3DtV5fmzyJFEFSa3+Gxu7ATdj1AkHI2ZuGqWKgoJ9oWl1OQlDmwbFeaOYO2zjdQH+T5SJRhl4vd7h9OfsjgVJ2ip212lIsqqzE1KVLi45hoNfkPzQsyhIpPRUe34URyywSESrIxuBtnYyVi7TaFMyX7NsIQec74/DYg7OOg=,iv:52cZu1oCBDP2yJAs2BRuLOG6ztYrDZ/YedU0fnyT7hA=,tag:smFovrpj277d948S/8MerQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
