---
- name: Configure Alma Linux VM
  # ansible-playbook --extra-vars "tags=<tag>" alma-linux-9.yml
  vars:
    subdomain: home
    domain: parents-basement.win
  hosts: 'alma.{{ environment_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  pre_tasks:
    - name: Disable systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false
      when: ansible_facts['distribution'] == 'Debian'
  roles:
    - common
    - vm
    - ansible_managed
    - wireguard_server
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/alma-linux-9/nginx/
        domains:
          - '{{ subdomain }}.{{ domain }}'
          - '*.{{ subdomain }}.{{ domain }}'
      tags: nginx_reverse_proxy

    - role: quadlet
      vars:
        service: pihole
        config_files_directory: './config_files/alma-linux-9/pihole'
        rootful: true
        podman_secrets:
          WEBPASSWORD: "{{ vault_pihole_web_password }}"
      tags: pihole

    - role: quadlet
      vars:
        service: ddclient
        config_files_directory: './config_files/alma-linux-9/ddclient'
        rootful: false
        podman_secrets:
          DDCLIENT_PASSWORD: "{{ vault_ddclient_cloudflare_token }}"
      tags: ddclient

    - role: quadlet
      vars:
        service: glance
        config_files_directory: './config_files/alma-linux-9/glance'
        rootful: false
      tags: glance

    - role: quadlet
      vars:
        service: monitoring-pod
        config_files_directory: './config_files/alma-linux-9/monitoring-pod/'
        rootful: false
      tags: monitoring-pod
