---
- name: Configure Alma Linux VM
  # ansible-playbook --extra-vars "tags=<tag>" alma-linux-9.yml
  vars:
    subdomain: home
    domain: parents-basement.win
  hosts: 'alma.{{ environment_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  pre_tasks:
    - name: Partition media disk
      community.general.parted:
        device: /dev/vdb
        number: 1
        state: present

    - name: Create an xfs filesystem on /dev/vdb1
      community.general.filesystem:
        fstype: xfs
        state: present
        dev: /dev/vdb1

    - name: Perform the mounting on the mount device
      ansible.builtin.mount:
        fstype: xfs
        src: /dev/vdb1
        path: /mnt/volume
        state: mounted
  roles:
    - common
    - vm
    - ansible_managed
    - wireguard_server
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/alma-linux-9/nginx/
        domains:
          - '{{ subdomain }}.{{ domain }}'
          - '*.{{ subdomain }}.{{ domain }}'
      tags: nginx_reverse_proxy

    - role: quadlet
      vars:
        service: pihole
        containers_systemd_directory: './config_files/alma-linux-9/pihole/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/pihole/config_files/'
        rootful: true
        podman_secrets:
          WEBPASSWORD: "{{ vault_pihole_web_password }}"
      tags: pihole

    - role: quadlet
      vars:
        service: ddclient
        containers_systemd_directory: './config_files/alma-linux-9/ddclient/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/ddclient/config_files/'
        rootful: false
        podman_secrets:
          DDCLIENT_PASSWORD: "{{ vault_ddclient_cloudflare_token }}"
      tags: ddclient

    - role: quadlet
      vars:
        service: glance
        containers_systemd_directory: './config_files/alma-linux-9/glance/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/glance/config_files/'
        rootful: false
      tags: glance

    - role: media_server
      tags: media_server

    - role: quadlet
      vars:
        service: jellyfin
        containers_systemd_directory: './config_files/alma-linux-9/jellyfin/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/jellyfin/config_files/'
        rootful: false
        quadlet_append_groups: media-server
      tags: jellyfin

    - role: quadlet
      vars:
        service: sonarr
        containers_systemd_directory: './config_files/alma-linux-9/sonarr/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/sonarr/config_files/'
        rootful: false
        quadlet_append_groups: media-server
      tags: sonarr

    - role: quadlet
      vars:
        service: jellyseerr
        containers_systemd_directory: './config_files/alma-linux-9/jellyseerr/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/jellyseerr/config_files/'
        rootful: false
        quadlet_append_groups: media-server
      tags: jellyseerr

    - role: quadlet
      vars:
        service: qbit-pod
        containers_systemd_directory: './config_files/alma-linux-9/qbit-pod/containers_systemd/'
        config_files_directory: './config_files/alma-linux-9/qbit-pod/config_files/'
        rootful: true
        quadlet_append_groups: media-server
        podman_secrets:
          WIREGUARD_PRIVATE_KEY: "{{ vault_vpn_private_key }}"
          WIREGUARD_PRESHARED_KEY: "{{ vault_vpn_preshared_key }}"
          WIREGUARD_ADDRESSES: "{{ vault_vpn_addresses }}"
          SERVER_COUNTRIES: "{{ vault_vpn_server_countries }}"
          FIREWALL_VPN_INPUT_PORTS: "{{ vault_vpn_input_ports }}"
        template_config_files_directory: './config_files/alma-linux-9/qbit-pod/template_config_files/'
      tags: qbit-pod
