---
- name: Backup VMs and ZFS datasets
  vars:
    node_name: proxmox
    subdomain: home
    domain: parents-basement.win
  hosts: "{{ node_name }}.{{ subdomain }}.{{ domain }}"
  become: true
  tasks:
    - name: Backup all vms in the Proxmox cluster except FreeIPA because it sucks ass
      ansible.builtin.shell:
        cmd: "vzdump --all --mode snapshot --compress zstd --storage pbs-offline-backup"
      tags: vm

    - name: Backup /mpool/media
      ansible.builtin.shell:
        cmd: "proxmox-backup-client backup media.pxar:/mpool/media"
      environment:
        PBS_PASSWORD: "{{ vault_pbs_archiver_password }}"
        PBS_REPOSITORY: "{{ vault_pbs_archiver_username }}@pbs@pbs.{{ subdomain }}.{{ domain }}:443:zpool"
      tags: media
