---
- name: Backup VMs and ZFS datasets
  vars:
    node_name: proxmox
    subdomain: home
    domain: parents-basement.win
  hosts: "{{ node_name }}.{{ subdomain }}.{{ domain }}"
  become: true
  tasks:
    #    - name: Backup all vms in the Proxmox cluster
    #      community.general.proxmox_backup:
    #        api_user: "{{ vault_pbs_archiver_username }}@pve"
    #        api_password: "{{ vault_pbs_archiver_password }}"
    #        api_host: proxmox
    #        storage: pbs-offline-backup
    #        mode: all

    - name: Backup /mpool/media
      ansible.builtin.shell:
        cmd: "proxmox-backup-client backup media.pxar:/mpool/media"
      environment:
        PBS_PASSWORD: "{{ vault_pbs_archiver_password }}"
        PBS_REPOSITORY: "{{ vault_pbs_archiver_username }}@pbs@pbs.{{ subdomain }}.{{ domain }}:443:zpool"
