---
- name: Configure Breathe VM
  vars:
    node_name: breathe
    subdomain: home
    domain: parents-basement.win
  hosts: "{{ node_name }}.{{ environment_name }}.{{ subdomain }}.{{ domain }}"
  become: true
  roles:
    - common
    - vm
    - ansible_managed

    - role: ipa_client_install
      vars:
        password: "{{ ipaadmin_password }}"
        principal: admin
      tags: ipa_client_install

    #    - role: freeipa.ansible_freeipa.ipaclient
    #      vars:
    #        state: present
    #        ipaclient_domain: "{{ subdomain }}.{{ domain }}"
    #        ipaclient_all_ip_addresses: true
    #        ipasssd_enable_dns_updates: true
    #        ipaclient_force_join: yes
    #      tags: freeipa

    - role: nginx_reverse_proxy
      vars:
        domains:
          - "{{ subdomain }}.{{ domain }}"
          - "*.{{ subdomain }}.{{ domain }}"
      tags: nginx_reverse_proxy

    - role: media_server
      tags: media_server

    - role: wireguard_client
      vars:
        address1: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_address1') }}"
        address2: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_address2') }}"
        private_key: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_private_key') }}"
        dns1: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_dns1') }}"
        dns2: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_dns2') }}"
        public_key: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_public_key') }}"
        preshared_key: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_preshared_key') }}"
        endpoint: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_endpoint') }}"
        wg_interface_name: AirVPN
      tags: wireguard_client

    - role: quadlet
      vars:
        service: qbittorrent
        rootful: true
        podman_secrets:
          QBT_TORRENTING_PORT: "{{ lookup('vars', 'vault_' ~ environment_name ~ '_vpn_input_ports') }}"
        wg_interface_name: AirVPN
      tags: qbittorrent

    - role: quadlet
      vars:
        service: jelly-pod
        rootful: true
      tags: jelly-pod
