---
- name: Configure Debian VM
  hosts: '{{ target | default("debian") }}'
  become: true
  pre_tasks:
    - name: Disable systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false
  roles:
    - debian
    - common
    - vm
    - wireguard_server
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/debian-vm-1/etc/nginx/
        domains:
          - home.parents-basement.win
          - '*.home.parents-basement.win'
        sites_to_enable:
          - home.parents-basement.win
    - role: quadlet
      vars:
        service: glance
        containers_systemd_directory: './config_files/debian-vm-1/glance/containers_systemd/'
        config_files_directory: './config_files/debian-vm-1/glance/config_files/'
        rootless: true
      tags:
        - glance
  tasks:
    # Pi-hole
    - name: Run Pi-hole container
      containers.podman.podman_container:
        name: pihole
        image: docker.io/pihole/pihole:latest
        hostname: pi-hole
        state: started
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "50001:80/tcp"
        volumes:
          - "/home/pihole/etc/pihole:/etc/pihole"
          - "/home/pihole/etc/dnsmasq.d:/etc/dnsmasq.d"
        env:
          TZ: "Europe/Warsaw"
          WEBPASSWORD: "{{ vault_pihole_web_password }}"
    # ddclient
    - name: Copy ddclient file
      ansible.builtin.copy:
        src: ./config_files/debian-vm-1/home/ddclient/config/ddclient.conf 
        dest: /home/ddclient/config/ddclient.conf
        owner: ddclient
        group: ddclient
        mode: '0644'
    - name: Run ddclient container
      containers.podman.podman_container:
        name: ddclient
        image: docker.io/linuxserver/ddclient:latest
        hostname: ddclient
        state: started
        volumes:
          - "/home/ddclient/config:/config"
        env:
          TZ: "Europe/Warsaw"
          DDCLIENT_PASSWORD: "{{ vault_ddclient_cloudflare_token }}"
  post_tasks:
    - name: Set resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: nameserver 10.2.137.1
