---
# TODO
# move wireguard_server here
# move debian here instead of being a role
- name: Configure Debian VM
  become: true
  #  hosts: "{{ variable_host | default('debian') }}"
  hosts: '{{ target | default("default") }}'
  #  hosts: default
  remote_user: root
  roles:
    - debian
    - common
    - vm
    - wireguard_server
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/debian-vm-1/etc/nginx/
        domains:
          - home.parents-basement.win
          - '*.home.parents-basement.win'
        sites_to_enable:
          - home.parents-basement.win
  tasks:
    - name: Install Podman
      ansible.builtin.package:
        name: podman
        state: present
    # 
    # Pi-hole
    - name: Create Pi-Hole user
      ansible.builtin.user:
        name: pihole
        shell: '/bin/bash'
        create_home: true
    - name: Ensure directory for pihole is present
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: pihole
        mode: '0755'
      loop:
        - '/home/pihole/etc/pihole'
        - '/home/pihole/etc/dnsmasq.d'
    - name: Disable systemd-resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        enabled: false
    - name: Run Pi-hole container
      become: true
      become_user: root
      containers.podman.podman_container:
        name: pihole
        image: docker.io/pihole/pihole:latest
        hostname: pi-hole
        state: started
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "50001:80/tcp"
        volumes:
          - "/home/pihole/etc/pihole:/etc/pihole"
          - "/home/pihole/etc/dnsmasq.d:/etc/dnsmasq.d"
        env:
          TZ: "Europe/Warsaw"
          WEBPASSWORD: "{{ vault_pihole_web_password }}"
  post_tasks:
    - name: Set resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: nameserver 10.2.137.1
