---
- name: Configure host echoes
  hosts: echoes
  become: true
  roles:
    - clevis
    - common
    - ansible_managed
    - zfs
    - syncoid
    - rke2
    - dac
    - alloy
  tasks:
    - name: Ensure packages for transcoding are present
      ansible.builtin.apt:
        name:
          - firmware-misc-nonfree
          - intel-media-va-driver-non-free
          - intel-gpu-tools
        state: present
  vars:
    sanoid_conf: |
      # Filesystem Backups
      [tank/static]
        use_template = primary
        recursive = yes

      # Templates
      [template_primary]
        frequently = 0
        hourly = 24
        daily = 30
        weekly = 4
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes
    syncoid_type: source
