---
- name: Configure GitLab Debian VM
  vars:
    node_name: gitlab
    subdomain: home
    domain: parents-basement.win
  hosts: '{{ node_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  roles:
    - common
    - vm
    - role: geerlingguy.swap
      vars:
        swap_file_size_mb: '2048'

    - role: nginx_reverse_proxy
      vars:
        domains:
          - '*.gitlab.home.parents-basement.win'
          - gitlab.home.parents-basement.win
      tags: nginx_reverse_proxy
  tasks:
    - name: Install packages needed for GitLab
      ansible.builtin.apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - perl
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Setup Gitlab repositories
      ansible.builtin.shell:
        cmd: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | /bin/bash'
        executable: /bin/bash 

    - name: Install GitLab
      ansible.builtin.apt:
        name: gitlab-ce
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Set GitLab external_url
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?external_url.*"
        line: "external_url 'https://gitlab.home.parents-basement.win'"
      notify: reconfigure gitlab

    - name: Set GitLab Registry external_url
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?registry_external_url.*"
        line: "registry_external_url 'https://registry.gitlab.home.parents-basement.win'"
      notify: reconfigure gitlab

    - name: Disable Let's encrypt
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?letsencrypt\\['enable'\\].*"
        line: "letsencrypt['enable'] = false"
      notify: reconfigure gitlab

    - name: Disable bundled NGINX
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?nginx\\['enable'\\].*"
        line: "nginx['enable'] = false"
      notify: reconfigure gitlab

    - name: Add 'www-data' user to GitLab external users
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?web_server\\['external_users'\\].*"
        line: "web_server['external_users'] = ['www-data']"
      when: ansible_facts['os_family'] == 'Debian'
      notify: reconfigure gitlab

    - name: Add 'nginx' user to GitLab external users
      ansible.builtin.lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^(# )?web_server\\['external_users'\\].*"
        line: "web_server['external_users'] = ['nginx']"
      when: ansible_facts['os_family'] == 'RedHat'
      notify: reconfigure gitlab

  post_tasks:
    - name: Set resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: nameserver 10.2.137.1
  handlers:
    - name: Reconfigure GitLab
      ansible.builtin.shell:
        cmd: gitlab-ctl reconfigure
        executable: /bin/bash
      listen: reconfigure gitlab
      environment:
        GITLAB_ROOT_PASSWORD: "{{ vault_gitlab_root_password }}"
