proxmox:
  hosts:
    proxmox.home.parents-basement.win
homeassistant:
  hosts:
    homeassistant.home.parents-basement.win
gitlab:
  hosts:
    gitlab.home.parents-basement.win
gitlab-runner:
  hosts:
    gitlab-runner.home.parents-basement.win
alma:
  hosts:
    alma.home.parents-basement.win
