---
- name: Configure FreeIPA VM
  vars:
    node_name: keycloak
    subdomain: home
    domain: parents-basement.win
  hosts: '{{ node_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  roles:
    - common
    - vm
    - ansible_managed
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        state: present
        ipaclient_domain: '{{ subdomain }}.{{ domain }}'
        ipaclient_force_join: true

    - role: quadlet
      vars:
        service: keycloak
        rootful: true
        podman_secrets:
          KC_BOOTSTRAP_ADMIN_USERNAME: "{{ vault_keycloak_username }}"
          KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ vault_keycloak_password }}"
      tags: keycloak
