---
- name: Configure Proxmox Node
  vars:
    node_name: pbs
    subdomain: home
    domain: parents-basement.win
  hosts: '{{ node_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  roles:
    - proxmox_backup_server
    - role: common
      vars:
        root_password_hash: "{{ vault_pbs_root_password_hash }}"
    - ansible_managed
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        state: present
        ipaclient_domain: '{{ subdomain }}.{{ domain }}'
        ipaclient_all_ip_addresses: true
        ipasssd_enable_dns_updates: true
        ipaclient_force_join: yes

    - role: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: pbs-ssl
            ca: ipa
            dns: "{{ inventory_hostname }}"
            principal: HTTP/{{ inventory_hostname }}@HOME.PARENTS-BASEMENT.WIN

    - role: nginx
      tags: nginx
  tasks:
    - name: Copy certificate
      ansible.builtin.copy:
        remote_src: true
        src: /etc/ssl/certs/pbs-ssl.crt
        dest: /etc/proxmox-backup/proxy.pem
        owner: root
        group: backup
        mode: '640'

    - name: Copy private key
      ansible.builtin.copy:
        remote_src: true
        src: /etc/ssl/private/pbs-ssl.key
        dest: /etc/proxmox-backup/proxy.key
        owner: root
        group: backup
        mode: '640'

    - name: Reload proxmox-backup-proxy service
      ansible.builtin.systemd_service:
        name: proxmox-backup-proxy
        state: reloaded
