---
- name: Configure Proxmox Node
  vars:
    node_name: proxmox
    subdomain: home
    domain: parents-basement.win
  hosts: "{{ node_name }}.{{ subdomain }}.{{ domain }}"
  become: true
  roles:
    - proxmox
    - role: common
      vars:
        root_password_hash: "{{ vault_proxmox_root_password_hash }}"
    - terraform_managed
    - ansible_managed
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        state: present
        ipaclient_domain: "{{ subdomain }}.{{ domain }}"
        ipaclient_all_ip_addresses: true
        ipasssd_enable_dns_updates: true
        ipaclient_force_join: yes

    - role: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: proxmox-ssl
            ca: ipa
            dns: "{{ inventory_hostname }}"
            principal: HTTP/{{ inventory_hostname }}@HOME.PARENTS-BASEMENT.WIN

    - role: nginx
      tags: nginx
  tasks:
    - name: Install externally provided certificate
      ansible.builtin.shell: pvenode cert set /etc/ssl/certs/proxmox-ssl.crt /etc/ssl/private/proxmox-ssl.key --force --restart

    - name: Get Kerberos ticket using keytab
      community.general.krb_ticket:
        keytab: true
        keytab_path: /etc/krb5.keytab

    - name: Retrieve nfs service keytab
      ansible.builtin.shell: ipa-getkeytab -s freeipa.{{ subdomain }}.{{ domain }} -p nfs/{{ node_name }}.{{ subdomain }}.{{ domain }} -k /etc/krb5.keytab
