---
- name: Configure Proxmox Node
  vars:
    subdomain: home
    domain: parents-basement.win
  hosts: 'proxmox.{{ subdomain }}.{{ domain }}'
  become: true
  roles:
    - proxmox
    - common
    - terraform_managed
    - ansible_managed
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/proxmox/nginx/
        domains:
          - 'proxmox.{{ subdomain }}.{{ domain }}'
