---
- name: Configure Proxmox Node
  vars:
    node_name: proxmox
    subdomain: home
    domain: parents-basement.win
  hosts: '{{ node_name }}.{{ subdomain }}.{{ domain }}'
  become: true
  roles:
    - proxmox
    - common
    - terraform_managed
    - ansible_managed
    - role: nginx_reverse_proxy
      vars:
        domains:
          - '{{ node_name }}.{{ subdomain }}.{{ domain }}'
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        state: present
        ipaclient_domain: '{{ subdomain }}.{{ domain }}'
