---
- name: Configure Proxmox Node
  become: true
  hosts: proxmox
  remote_user: root
  roles:
    - proxmox
    - common
    - terraform_managed
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/proxmox/etc/nginx/
        domains:
          - proxmox.home.parents-basement.win
        sites_to_enable:
          - proxmox.home.parents-basement.win
