---
- name: Configure Proxmox Node
  hosts: '{{ target | default("proxmox") }}' # this lets you override hosts by specifying variable 'target'. Otherwise it targets group 'proxmox'
  become: true
  roles:
    - proxmox
    - common
    - terraform_managed
    - ansible_managed
    - role: nginx_reverse_proxy
      vars:
        nginx_config_files_directory: ./config_files/proxmox/etc/nginx/
        domains:
          - proxmox.home.parents-basement.win
        sites_to_enable:
          - proxmox.home.parents-basement.win
