---
- name: Configure us-and-them VM
  vars:
    node_name: us-and-them
    subdomain: home
    domain: parents-basement.win
  hosts: "{{ node_name }}.{{ subdomain }}.{{ domain }}"
  become: true
  roles:
    - common
    - vm
    - ansible_managed
    - role: freeipa.ansible_freeipa.ipareplica
      vars:
        ipareplica_firewalld_zone: public
        ipaclient_force_join: true
        ipareplica_setup_dns: true
        ipareplica_setup_ca: true
        ipareplica_auto_forwarders: true
        state: present
