apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7wVcvaDlpJ6GAvMYVARalyxesHFc4ECX7nljSlsPXeV4BH5Wsad3X/tuaWI=,iv:WH3XHAeVaCIH97ZhiOTneCG6kfQMRK1ZEc6tX2o2UbI=,tag:9ihqazj0sclwANb2mzdgHw==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:UQ8cVBUPmcGBsfyn5EzAiJucVptdMtaCblNbDk/ZdfAY85VK43kRzzQ=,iv:436HnvtdBV3n8X7o54dxEyFuW34oan1manXKLwzoGh0=,tag:rY+kY1W7qdoc5/ME5BC/+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBMWnl1
            eldSYWY3NExQcVpYTkw0MVR6YW5lb0lIOEhndWtvN1NDeG0xQkJrCm5MS3RZaWov
            bW1EWDVWSXBHMXJzZHBkVmk3emFZTUJrL0I1ejZ1SXRZcjQKLS0tIGZFU0V3emtZ
            R011RTNoVzRjRUw1Nzk0UEFyRDFBbnhHeTVTRDdaTk91T0kKcI7Yhp60RJIBj7fR
            pVIIaKEFhgpKkQUnP196rfFryLD/eofO+CrZTpxW77KdiINzKT9iQk9jXpEh/hqu
            x5aA3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdlU5YmJWWFpualN4eTJt
            MHJvWEdkUWJncFdJVG83OURraC8zWHdrTDI0CjFhMzRaNERtZ0FtVlk0bEhUT2Rw
            MU5CeVZUOHh4djBlZWlkVTNaaWVoOEEKLS0tIHg2aHQ2TnBDMjZOekdOcGJRcjFV
            bXRXSE0xVU1mKzlpWlV1VFZGcWQxcmcK7Se8uxsfcJy76JkTcOth+wmYgRae2lqY
            qAi27IP94mnlq8+A2RF70/FMTRjDFO/BFNF1cy/lll9ZB2Zzlis7NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSArcHlL
            MzZ1d1RaRVp4c2xqdzNTQW9Bd2tWRTdaZXVFaFdtNlVRUHAwV3dBCjZ4U296aFJS
            dmZLdmFRMFNDMzdqbGlaTlJJT2dtNXNwdThBdG81REZ5TmsKLS0tIHRiak8zT2pY
            VG13RjBzam80NGxjRGpHenl4YUFQd0lWZ1JNMnhtV0dnOEUKAfwPrXRYAkAQsTrr
            b4ef60ywF2ZeeT7ljERoCbwJoBLS7/a4tS+I+PMScnG8xKsCiHzIF8HGQOTVeFOu
            FikUxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRkgwdXplM3drdVczUEZq
            Q2dOUjUxeUhDRkNPUGZQVUZ1K2xDS1FKK1ZrCjlwNnlhOGZFZkVwdVVrckZvSTJ0
            dmpNRjBnTFhyZTdDVG13U25LUTJlYmsKLS0tIGduZlhjZm1IVTdNMUgwVmdDaWtw
            ODE3clU5RjdNZGsyeTVXcDBRcDhQUFkK+wL1QS8zce2g2XU09KjKISetBTHO11u3
            UR0QIo/srBRgUuIDimdpbLE+TCl9v0U8gvg82i1Z8xcGyjYBxhnCkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T20:04:36Z"
    mac: ENC[AES256_GCM,data:ofNcaLCviPrd2ISKQ41SwxLYzCA4tSyjinwdMOPywCzVmlCvTtNymWlzBsVUZIy20UVlPPc7AJKPmjfEhxOFPzMLTqSjUyIwT6ys98ibeZMtXv8ZlvhL9Mid0LLc+ftgVeRgZ2a7qmQajlNz51RbI4hdFYGHx1tvY2sEIlRCFo8=,iv:YpWaJKNq+Wg8tNUQQ7bc8parjWpWtPPflEf9zHopMxA=,tag:TuP8K9NmfMsTIjrPzxQtsw==,type:str]
    version: 3.13.1
