apiVersion: ENC[AES256_GCM,data:Wgg=,iv:zB3iuhwoysh8o4EfnFVjkQUWFODjxTLKO++aBbUK7zY=,tag:IXDARzY4obDiFV48+zanBw==,type:str]
kind: ENC[AES256_GCM,data:j0CAbgDi,iv:v2tTuwqSZJUHYVTNX2rxxa+GgIQpYLllF+2NO+sAXZU=,tag:0Us03PNZV6ZM4A3YenWEvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kSKVhYnnQ0Pw,iv:fUe8F5XSlFK7Qfk27v9Z3VeNMZqhCrTUuhgTQ1uJxAk=,tag:XjjSvu6UeQTV8S9QevVuZw==,type:str]
    namespace: ENC[AES256_GCM,data:xGdChJBsoozYXpM=,iv:oedYSTqKYRSFSZVdWOlsjjZwYbvOsryifH7ktBUEWx4=,tag:Zctt6OefREbs57bz0u97SQ==,type:str]
type: ENC[AES256_GCM,data:2Sey7MQx,iv:ciYVG5dwC8/PD/kyk/AotLL/IaPNoL59InyLaxDwcTY=,tag:yLehXGr3TfrG9ER8gFxIaQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:7gKgVGTRHi08CZUahuiQVPSI2mwIc96usy9OOmptVL82bE2ZSrYZBZ4FnBE7seEHonNr8KRKLUZg2U0CJ4glYxDy/DPhp2aMTuw=,iv:3c9PH0AVA5bTJaoAVLOgYw0AE19MT36JQOcDB2qHXvQ=,tag:DC+NRcK43kx29S1D9W+ijQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBQOGU0
            bFB6eW9tVGxsckRNWlpvRGtxRGVxYThTUTFvcFV6VkpEUGRYNGdzCnBGeE9jVWdE
            aDltRzhEeS9RU0lOcGtjMEN5RmVNN2MwYmtBWjVUM1Qvb1kKLS0tIFFDZXN6Q0xY
            SlExYVhhbVhDRlpPcTR1RDBsMWhweEE4TDNYUUF3WVd4bk0KB7owGdagTYLK4w1x
            GI8GdbNjPUmNboxyYqi/nA3h1z4/K9Q1smzBnF20IJHyfgGr4QLTP19Izcr854Kr
            Ph9ycA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZlBrK2VuMk5zcERLSmww
            MXIzK1RnTHBzdEIyTVM3dEg5M2o0cUFEYmdJCjREbXFaZmJDS1VrOExqRkp3Vnln
            WEVIV3VIMllFSFlaRzBTSTYwSWFGelUKLS0tIGNIRldkcG1ydlZqc0dScXBwelpO
            TFBHL21VQUNHQnFPNlRuRy81dzMxTG8KCX3MO2TWUtptlcymoexQtL9i4aUqlJ90
            gjmWZo5LIh0ajUmktfzICKl7wujPDvcPT7od+sulPwrLpkv6iRi0YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T17:51:16Z"
    mac: ENC[AES256_GCM,data:M9UYmncG36R8rhlZn7on1id7W07LdRhsI+ceb/UOqKZReuCNlqvJTAOkhcmKNTQS1mn8Rbixz/Y8Mfai/hVO9UKXIXUaBZK4q1zcvxX2WrRRiut7A7sFhKvc8r4fbJs8Msj96DN405MqQqKE7IblKRKSNNcckF9DJzW01EvA1w8=,iv:Fx+L7dD0IUTcL4WyPoh3RL21keRi8xCJJZTGabuKvxw=,tag:jx+dAQdNceuxhH7R/h9YBw==,type:str]
    encrypted_regex: .*
    version: 3.11.0
