apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:bmaED+OJ7EoyAFPSJSiv1Y/BYFNx/HcVG77FNBLsTxorPLpFfGY2xg+ZzAt9UTKR2OGLZ2A=,iv:7cmhHgsTW0vesjwFwFDn046Ei+dLgraX1naz/BKeInE=,tag:jOuiecfrUEpuRgO8SPWPKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyB2Znlr
            SmYxVkd3czQ2VDBjN1QzYjVBTkIxeWF2WmpCZ0FmTmRGQlhSMXdzCnVFR2hxZmt3
            UTN6eEJpVWQ3SXFXUytjQ3A1dy9uR2s5ZGVpWkk0WDdyNDgKLS0tIHg3YVduclFj
            YzI5WEQyYmtXQ3dOQkwyWmdZSkgvUGk1SUpqaDRrdlRKU28K0CZGQS6aM/KPi6oc
            jB7F6FObURt298yuyE7x1wv3f/vqc6oIM24QRb2x3GtGUX9rwG4UbYnddklCZWnT
            25/bHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMzM3WXhTM0U3b1JuOGoz
            b2R4cS81SFBkY0tMSnFqTTRXYW05K3QraWhVClhQR282NEVRN2ZSazE1eDNlcGNm
            dWo5UVQ3T0U5SHMrRnEvZ0VzWVZhOG8KLS0tIC9FNE5UTXlWSXZ5VnA3YXUwQXhF
            cDd4QkFFWDAycGhvMjRpK1VOaW95RkUK2+VbC2UH8lZfbR+E2C7CkqC43lVxNSqb
            9Fn/b4bFPksQcBpyeK3LshqchKgJGq608YFWMBAV0ygnuLjg8v4Row==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSA0ZkY5
            bjlockF6dTFKT3ZxYzdYNHNOdVJFaVh2Unl1YjlXMkRjWFJZTTJvCnd6MGIzS3Ju
            SlZGUGdxT201SkpSL0NaeHZ5VHhvN2lGUnNxdmUrQjFEQncKLS0tIGZRdWZERVVG
            dkpFY1ZyQkdVbklFc0ZQeHp6dytEbnRnbE9xNVZGdzU0UFkKISf8d/PRCjHxqDGF
            JndQPP9dJ5P6t1hjDCggbsEdLqsmuKoo6PuO/fe7T996bymn1gAZqRAszHCpY1mJ
            MYbSCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWitlbDJSOU8zWGllaUxn
            dTdrVXFXQmRxYVhCSXphUXV2VXR4K3ZhOEc0ClpYRm5zOUkrVUNHcmllSldmT0tQ
            NFJrbVB4UllrbHBWb0o4TXcrWUpiQVEKLS0tIHRnazRRV0tRSEZxNWNEMVNEL05P
            Q2xRMm9YSlFiNnZoa0pZalNmKzZOOG8KGqAPAuvYNQGzFu2BhegplPhBNAw8E5G8
            rC2hGNL4Apw6aSnqAp6tNCEOfDPG/y6QS4I8OOCvaiXTeQV8gP3ddg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T14:35:44Z"
    mac: ENC[AES256_GCM,data:Nl+7Rt4aktGr0WIonfvQGQbn4wnti+Xs8x8nGZZn5/C0xVptlIhg1Yggp3lwPXVU1VIeO6TZOkVtzMwKC9h2JxLxHhBDhEjjWmPlYYUyOqVli1h6NZ/hrobgi6Plu+4Sp5jo2N+wGZjFHYRDKCmdSB5ttoDPgO4lysiUdCLBAFc=,iv:aOnbXI5JM9seUltS3UZMpKojjb+kFI7GvAOZixh1Z0s=,tag:bI8D0z8E2gJMx3qqnmu5SQ==,type:str]
    version: 3.13.1
