apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr
  labels:
    app: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr
  template:
    metadata:
      labels:
        app: arr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: init-directories
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/torrents/radarr /data/media/movies /data/torrents/tv-sonarr /data/media/tv",
            ]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: radarr
          image: ghcr.io/home-operations/radarr:rolling@sha256:9967e56263a3c67eeaede5824103ee4c1c1f1511abd5965ac1e294bfd9b76dbb
          env:
            - name: RADARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: RADARR__AUTH__APIKEY
            - name: RADARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: RADARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 7878
              name: radarr
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: radarr-config
              mountPath: /config

        - name: sonarr
          image: ghcr.io/home-operations/sonarr:rolling@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c
          env:
            - name: SONARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: SONARR__AUTH__APIKEY
            - name: SONARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: SONARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8989
              name: sonarr
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: sonarr-config
              mountPath: /config

        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:rolling@sha256:fc87e9af2f175ef19610fdcf1fcdcc84d5099127211cc6733f826409b2733237
          env:
            - name: PROWLARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: PROWLARR__AUTH__APIKEY
            - name: PROWLARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: PROWLARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9696
              name: prowlarr
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
