apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      #dnsPolicy: Default
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: gluetun-sidecar
          image: ghcr.io/qdm12/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
          restartPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: "/usr/local/bin/qbittorrent-port-update.sh --port {{PORT}} --iface {{VPN_INTERFACE}}"
            - name: VPN_PORT_FORWARDING_DOWN_COMMAND
              value: "/usr/local/bin/qbittorrent-port-update.sh --port 0 --iface lo"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: SERVER_COUNTRIES
              value: Poland
            - name: PORT_FORWARD_ONLY
              value: on
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_PORT_FORWARDING
              value: on
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: WIREGUARD_PRIVATE_KEY
            - name: LOG_LEVEL
              value: info
            - name: BLOCK_MALICIOUS
              value: off
            - name: BLOCK_SURVEILLANCE
              value: off
            - name: BLOCK_ADS
              value: off
            - name: HEALTH_RESTART_VPN
              value: on
            - name: DNS_UPSTREAM_IPV6
              value: on
            - name: DNS_SERVER
              value: off
          volumeMounts:
            - name: qbittorrent-scripts
              mountPath: /usr/local/bin/qbittorrent-port-update.sh
              subPath: qbittorrent-port-update.sh
            - name: qbittorrent-scripts
              mountPath: /usr/local/bin/healthcheck.sh
              subPath: healthcheck.sh
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck.sh
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck.sh
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

        - name: gomplate-qbittorrent-config
          image: hairyhenderson/gomplate:alpine@sha256:0551ea7fa4a3d2977b62ddb700dff5368901481a4be59ae47b9a75cbbed82cad
          env:
            - name: QBITTORRENT_PASS_HASH
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: QBITTORRENT_PASS_HASH
            - name: QBITTORRENT_USER
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: QBITTORRENT_USER
          command:
            - /bin/gomplate
            - -f
            - /tmp/qBittorrent.conf.tmpl
            - -o
            - /config/qBittorrent/qBittorrent.conf
          volumeMounts:
            - name: config-map-tmpl
              mountPath: /tmp/qBittorrent.conf.tmpl
              subPath: qBittorrent.conf.tmpl
            - name: qbittorrent-config
              mountPath: /config

      containers:
        - name: qbittorrent
          image: ghcr.io/home-operations/qbittorrent:5.2.0@sha256:788796013c3da75f2dba568c5319975a5c41f555586dfd13987be4631181e00e
          volumeMounts:
            - name: data
              mountPath: /data
            - name: qbittorrent-config
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: config-map-tmpl
          configMap:
            name: qbittorrent-config-tmpl
        - name: qbittorrent-scripts
          configMap:
            name: qbittorrent-scripts
            defaultMode: 0744
