apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:7xmBryeUafxCR44mmykBeSc13ob6m21lzzjd5+sjSpbpybgDg5x/AuDCm18iRPk+KqGHN7g=,iv:174ttxK4R74sAoaWulOxHWfjsS4bYSMvambs9Kt53Zo=,tag:Wq6TxxpWoUeU6bGVbjBvXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyB2d2FW
            dnhJT3l0a1Z2UnJQQWZXVUp1M0Urb3l4ay8xemJodDdWQkF4c3pzCjAxUFgxK2Ir
            Z1NjbGFnT2tYLzl3SmtPaVVIeUZFdmFZd3V3Zm85dDdtSTAKLS0tIGN3VUoxY1hr
            enVnaEFxd2FUOXZLdFF4QkR5a0QyelRpNldKTG16OGR5Z3MKqjQhGMj5wT1aITmR
            ODO+3DLHzvgwnCJBJA7q3lGQaeGvUHVJIb491iV9MprsYBhqzNWi6XBMWNSCOME0
            7Oz2Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNWtFNzhybXpLL2RzalIx
            dVJ1OFZzRkNsNUM0YjI3d1BBQzA0VmdBRDNJCnlzZzAxd3Q4alA2U2srancxUzVD
            NnlwOEFWckxqMUU2Q1d4NGRrSktSRTQKLS0tIGI1ckFCcHBtUWVHdVBNZFZkZjkz
            Zk9mWjhzbmw2UHNFNTcyK3U0T2pidTQKigxpwMj68zKzMU1g4EAeweCpfJ6MHknl
            GTbtOWB2ZPCbue4GUN+7KFX0PkF4LjQsi8d5qiglkSyut01hQMh4JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBNWUlV
            V1dBckpQWGU0SnNQbHQ5NHg2YnYrRXJxeDNBY3F4QklLOUdTbm1rCkFEVmdIQ1JZ
            ZVFFdy9TOVU5T1lzQWhNZ0dFZ054bzl0TnhGTjVPWFEwbWsKLS0tIGZjQ2cxZ3Nn
            dFRwWkRpUTE5TFVpd1ZZeDBOQ3djTDBZZUpodTlJTU83ZHMK5Cr4WXil4b/fQqr8
            9iZs8MJwx+re26l0hsBx+U8ossJrfJVI6T+Er/FQhAzw3a6wNOw9eqgF+ljSqGcX
            TznNaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0dBVmtRaXN1MnVqQzhy
            WDNDNy9wZWtxSVcxc1lFTXhycDBuMXRHSTJVCnBsYy92dituYy9vQzlwbnpxSWMy
            Y29nSnd6S2dkSmU1aXR4Si9JNmZFWTQKLS0tIGRQL3lvbGV4cy9Xc2Yzd0h1Y0p0
            cnlvdThzcldqaDB2QnZjZFRreFR2eGcK9ZAJxbHIx+bH3TkYA8A8UTfqcV2dkqii
            kfzskV355SSxsd4uOVARjtTFZjIO6cqG5p6igDNJNFzqUu0I1HW7JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T16:23:52Z"
    mac: ENC[AES256_GCM,data:f3BP3MM88dK9Y1Kp4jZVEVpmUnMKSJ1V36kHB94ApJ9V7flTDM4EbmU10XOV34j2zFJXchpx5oAveWxUClYEAfZc2EKgEEabuqqMz0b6oRv3/mYh5WpCjY0DNfId2/4mPAimbg+je/4N0ZEQmyYagFQgyJfagv6kVIAbll6MEo4=,iv:3rEcc1NOH/DS9nCVPkoT3mFMabzlw2EYN5vQ14bxqdg=,tag:oSKByjfrXEovEtcyWyPtuA==,type:str]
    version: 3.13.1
