apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-credentials
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:CinBre9LjNfWK43c04zMCu69ZvRQEqO77OpO7juh/uD0oJkmbXtcNB/3t5wyE7qVfSex5+EbzC1h+Ul7G/RSWw==,iv:z04Y78kjwnZK8a3indR0rjQl7jLevFw/kxR6KXJMlAg=,tag:H5d/9LLXFGNiG6DGMtrGRg==,type:str]
    secretKey: ENC[AES256_GCM,data:/M6Zul0ltPf7ULY1CLGUWWHS54r90zXo3Q1f0kicc9rG8UOoMTKG156TRb0SHq+65xVwE9KtQRYNlM4ToLZo5Q==,iv:b7/w6Qqven7sUQsxjGPGoCu3yG12psMs3wfX/QOhJFo=,tag:qrT+yrkSQpfMKfIUWiBw/g==,type:str]
    cloud: ENC[AES256_GCM,data:WJ01SqRW0IhdV2k39Qr3AC+2BXPvDWiTrTn9NQHxFetk5n1cKi56SBtjCfJU2xiFFPCR9gllyzi4iKbxr/uAQpjF8VnIDKUiCPos3k4Tf83uohGHNK2g0V4Kk85xDhIbMGT7q8h9lOfq3ZGRK3cw7kdOsjrM9ssV68Wg3JzOkOs/Aw5fNHQZZy3kMm3YDKyB//iUxplRupGAhG6vyzUP5rtKvR1DS2Uz9SveDVLlvdHRwhe+,iv:ArT9/T8YzXzyA2QIdUaHLaOM1SJr9MDC7kKR7ci5Dug=,tag:lsTxmxEzNGMhaRftbiMx+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBGVWE3
            cmJxajJ5R1pMa1VqMFZtd1RlajQvRkJyMW03TGVDR1hiOUpQZnlBCkpQZndGekpl
            TjAvYm5kcytJZVM5TmNQc3U3N1NpUVU3d3c1dCt4TlFkS1UKLS0tIFAzZlZtM1Rx
            Q2JzZUUzZGJnbUdaUXk5Q3hXbENEd3htRFZEWUMybzN0UlEKmZuRMPuQ5CO3IUPK
            h9OwMsZV0BePcADSwQrCITerxwvis2N+lUxY1prM8jDpvlcWV88aZr+NtWW/U9gD
            7MfGDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGFQcEU3N3FwalBEU3cz
            RmNmb0IyWlFIYjNEYzBESmVJdFBsd2RYb1U4CmE5a09IS1B6cU1XS2M3VTA5UHFY
            T1pscjRNeHdYMVFiM0tDWVVZTTJCVGcKLS0tIHlaWG1aQ1BqTnY2cHlpVjV5WkRa
            YkVCNEM0ZjdFSzgwdk5ISTQ1Q0lkamMKalTMRvqmxkOU408yP4VFCWXNdEVM5Lva
            6mFV8FMnuCkAaQmVovBxd8Acv2VV4/W0QXGl7vVRQhc8Of92fiBNWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBJTGdY
            cmhJZHE0Z2I5MDdNdnhMWDNrTm5kTWJYeU1hL21iYXRHZFhzN2swCk9haTcyMXBn
            QysvSkduWk9aWk03UTl3dEJnS2VVbU1nZHNyTmoxWjEvUDgKLS0tIHFUSjJFSUl6
            aFdIbXpESDcza1BZL3V5TXJQK0pNRkZVaDVISXRDT1Z0aFEKDW1u7y9a7k70TPyT
            9sZndf0tpqcFsWJHb7wAVDbylPH3JVLNG9bK5CCWk5yTBqgAI2CBDMcFugt0L7JT
            s/lZEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1oxb041cUZDeU1nbEhN
            Yk03THhyTmc0Q2NMSXRUck8wTzQ4UHJGVGxVCjZjMEtlUW1Xcy9XamF0WjR6b2Jy
            MTVSR2dxN1NBZThxRjQwdnArMkl0SUkKLS0tIG9PYUU4Y1VTQXF0ODN3UzdwWElL
            QjZRUW5PbEE5TEwxSVRzazlvbVF4dFUK0m9fagciAUPrPe7YWSkQq718RLL+/XFw
            z2QwrpoXe4mGC8RgcUQlmtjdOLJ9K4D6ezwetujHx60bkVaEX5rTPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZlM5N1ZNbTllQVQveEw3
            RE1mVVdsdDJpVzEzZTlERExzZ1ZWamhlQnhNCnpBSlZaaDFSTHZ5dlZ2eEFiUkVK
            RkFoR1lxbUlGWkpsQWZ3aHZyb0ZRbVUKLS0tIDlKam1zZUw0enR3YVdVdkRLQjlw
            eEhMblNXNEZSbDY4YndYQXVRL3oyRncKC33heetWlbFXEqXYD49SduP0KTDT6BTO
            hDTkOr3QRJphYBDiJNfGcrSUMbaeWiOuhZsxBYDqma0cotZydc6OfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T23:20:07Z"
    mac: ENC[AES256_GCM,data:C0mGxBPr7JKgxKdSYYQVgYP/F9fqD4uqkmJs3CY8CkLWjMOEt4c4SRLDqrwJlWHXxrULPWpXgoQUc2BKJRdep7UGtugaPFHy+vxNAx/C6OaCVHnfBFXerte3l5bxsSf8fyKhq/ckfbVlYG9/HzbFIK85On6sKfOumdJb8Wf8n8M=,iv:34VuMsjcvj4rrhbkZmBjSpdVxnaQ2aW3EmLwvbPJvv4=,tag:+BLWobo5dxLjBNaPzDV6PQ==,type:str]
    version: 3.13.3
