apiVersion: v1
kind: Secret
metadata:
    name: arr-stack-static-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:hHaZL+7AFtWAmlK3guQGixZHoYNYS4NAy5ag982EO+HqOTU4OvnjXGswIhocFvGh2hPXgp4Rrgoyopx9kJjCOA==,iv:vLe5+rGHbViqhFQU6FjfKreahfm+QQceUOt3/YsuJA4=,tag:tWgQjLwcg+4k3gz7sLLUYg==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:WSF4dgkktDzX911k8gqTcTxx4BZm7Qf9CrPKFpCqGG3kfmtD/E4isG3pUkS6Qo9qWfSrxpbb6/gGC+tscmj6IA==,iv:g6cJWcrOJsWZkQXtM9N56hOPd+CzPIBRYQL60DzH+Qc=,tag:e02C5ct2DAwiXVyw1e4iNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyB5dXI4
            UlN5OTZkcUdJZHhiM3B5b3phTE80NW9lUFRoaFlaRkNiRUhlcFVNCmRLK3JUYjB0
            cHhleUpmK0NscXpnQ1lqQTVZY2JsWWQwdytMN2haNEJPeUkKLS0tIEIrUW9TNXZk
            Q05VUGFCZzVkRnJoMkpxM1ordU9WMmxob1NlRWU4d29yR2cKz4KS/A295ghTtbUr
            UzMW+1dtRnSn6xte6LSl7UhLKor3neLPampDa6AvaTE8DvxPdn6rCnprYs0i385N
            NxpSqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc2RDNk9wTDk1L0dtb0d5
            aUdzNlZqV21xVlpPVEhjZjBFSUdNL3hXeFMwClNyY1lSQkpzODF4eFF2UnI5TVNq
            K0ZZeUlSM28zM3AyNTRJYldyakJwWnMKLS0tIGxhQ0k4ck1jaUlIOEo5NkhmbnJh
            dnYwTWxrYm8vQXpFUXVlMEFMNm5pMDgK/2N27Csdj5ZLi0uKPs78rDaLVCod4So2
            u86yj37wK9TtNL3yM26oUngrlvVZT+38hh3ON+ncsR3M63HoWkxlVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSArRUpk
            bmJwYXNJYTVpSmVWTkNzOUlrNWpRVjAzOVYrM1RnaEVzYnBHVEY4CkZZT0treG16
            ZEF4ZjdtTllRTEdMZnVIQmsvcmRCaTVwd09DQ2IvZ1lTODAKLS0tIC9rRXhxeVg2
            T2lvYkJ2TmRUY21yRlFGVVArTEM3T2E5WFlyd1R0NFV5TmMKnLo4o5uylM/8ERLE
            ByqhG2Wvk1RnIWO0SGscWw1lb0a00ZRzMFc/dcU1+qqa6sp3rr8SIT9y1TyUdzkA
            Qq9b/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOHJWOEZnZ2dBb2FCRzFX
            R2NxQ2R4anhrblB2TFNLemFVdWswd1VBekdvCnlvNVdNVzFqOVV3SmFtYndZM2Ru
            dlRSSDFvMUxzazhyR3ptREJubDVxU1kKLS0tIDFPbXJLQVB2cHBISGQvdXdPRTFq
            OXprVm1aOW9yVURVUVBFWGpyT2FFRk0KxZTQP0vWMVkeDyJ45dB4lTl1vX7rkH2N
            SruVFSoiNUqZaOrQqLcuWcVhvGIX0z1KXLBsIVL3GewyyrdDdO2E9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ttrfgxxjy2ww7kurs6qpl7tv3vsypp323zln7ye2y23scyt48eqqvnuj6n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWHVYbXV5QW5UY1VIZmpv
            N1RlL25KK0Q3SEJCQld0a1h1Uk9yT0JmOVhVCmlXeDRtdVV6L3N6R1Y0ZzREU2k3
            VVdYU2ZRZG1aS0hpdHpZYjlJMUUvelkKLS0tIDI1dXZWLzM3WFhQLzYxWUJvZVBF
            bGFxQWVYKzh5d2dTNWZwQXgvMmNvck0KnywCc3o+jO7sxcLOeteSrAc4vqfU9IPb
            AFDKdGwOSzbCjnsFCgXKA1D+MTlmwHhx9S6NJLrb7+aLKhv94NNvgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T23:58:10Z"
    mac: ENC[AES256_GCM,data:Pim60e4JR6ZiB3yN7IEtKR2RUIvIaPxMha4IsD2Pe6edwDWYBgMPQF0wMgSI435fBBSE07ZM9dliASm7WdBXEIqmxTG/ZVA2KGxP7Kj4Cd73F9znHqHJMsMCtYjfN6cW3v+SPODo0mPKX8P1smwG70cmKq/wD0conQ2fpUAvONU=,iv:RlkdiuWNO3TI0EpRC/k3cVZrMQJr6XswjkkXAQvjOAQ=,tag:yrJcbcdA6h8XCrvGZt1UyA==,type:str]
    version: 3.13.1
