apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: centralized-oidc-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    template:
      engineVersion: v2
      data:
        client-secret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: centralized-oidc-secret
