apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- externalsecret.yaml
- gateway-class.yaml
- gateway.yaml
- http-redirect.yaml
- password.yaml
- public-certificate.yaml
- public-gateway.yaml
- securitypolicy.yaml
- sso-gateway.yaml
