apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr
  labels:
    app: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr
  template:
    metadata:
      labels:
        app: arr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: init-directories
          image: busybox:latest@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/torrents/radarr /data/media/movies /data/torrents/tv-sonarr /data/media/tv",
            ]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: radarr
          image: ghcr.io/home-operations/radarr:6.4.1@sha256:260469d707617f4b5be1cd11a40be7e4889c63c5e7cdbc6a429626dc05863b6b
          env:
            - name: RADARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-stack-static-secret
                  key: RADARR__AUTH__APIKEY
            - name: RADARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: RADARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 7878
              name: radarr
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: radarr-config
              mountPath: /config

        - name: sonarr
          image: ghcr.io/home-operations/sonarr:4.0.17@sha256:1989718e9fceb3fd35b4e73f61696c68f8959b8f09981cf137fdef8e6338b85f
          env:
            - name: SONARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-stack-static-secret
                  key: SONARR__AUTH__APIKEY
            - name: SONARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: SONARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8989
              name: sonarr
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: sonarr-config
              mountPath: /config

        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:2.6.2@sha256:13c576d2ad93764ab78d4e75c80447bc5489a06a15fd39e89c0be0be01e2ba3a
          env:
            - name: PROWLARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: arr-stack-static-secret
                  key: PROWLARR__AUTH__APIKEY
            - name: PROWLARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: PROWLARR__AUTH__METHOD
              value: External
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9696
              name: prowlarr
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
