apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arr-stack-secret
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: arr-stack-password
