apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- externalsecret.yaml
- password.yaml
- prowlarr-config-pvc.yaml
- prowlarr-httproute.yaml
- radarr-config-pvc.yaml
- radarr-httproute.yaml
- service.yaml
- sonarr-config.pvc.yaml
- sonarr-httproute.yaml
