apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: arr-stack-password
spec:
  length: 64
  allowRepeat: true
  symbols: 0
  secretKeys:
    - SONARR__AUTH__APIKEY
    - RADARR__AUTH__APIKEY
    - PROWLARR__AUTH__APIKEY
