pages:
  - name: Home
    columns:
      - size: small
        widgets:

          - type: calendar

      - size: full
        widgets:

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://jellyfin.home.parents-basement.win
                icon: si:jellyfin
              - title: Pi-hole
                url: https://pihole.home.parents-basement.win
                icon: si:pihole

          - type: hacker-news

          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim
