---
- name: Tune kernel inotify limits
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  loop:
    - { key: 'fs.inotify.max_user_instances', value: '8192' }
    - { key: 'fs.inotify.max_user_watches', value: '524288' }

- name: Ensure AppArmor packages are present
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
      - auditd

- name: Ensure RKE2 manifests directory exists
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy Cilium config manifest
  ansible.builtin.copy:
    src: rke2-cilium-config.yaml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
    mode: '0644'
    owner: root
    group: root

- name: Copy Flux secret
  ansible.builtin.copy:
    content: "{{ flux_secret_content }}"
    dest: /var/lib/rancher/rke2/server/manifests/01-flux-system-secret.yaml
    mode: '0600'
    owner: root
    group: root

- name: Template Flux Operator manifests
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/var/lib/rancher/rke2/server/manifests/{{ item }}"
    mode: '0644'
    owner: root
    group: root
  loop:
    - 00-flux-system-namespace.yaml
    - 02-flux-operator.yaml
    - 03-flux-instance.yaml

- name: Check currently installed RKE2 version
  ansible.builtin.command: /usr/local/bin/rke2 --version
  register: rke2_current_version
  failed_when: false
  changed_when: false

- name: Install RKE2
  ansible.builtin.shell:
    cmd: "curl -sfL https://get.rke2.io | sh -"
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
  when: >
    rke2_current_version.rc != 0 or
    rke2_version not in rke2_current_version.stdout
  notify: Restart rke2-server.service

- name: Ensure /etc/rancher/rke2 directory exists
  ansible.builtin.file:
    path: /etc/rancher/rke2
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Configure RKE2
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart rke2-server.service

- name: Flush handlers
  meta: flush_handlers

- name: Fetch kube_config
  ansible.builtin.fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /sops/{{ cluster_name }}/kube_config.orig
    flat: true
  register: kube_config_fetched

- name: Process and encrypt fetched kubeconfig locally
  when: kube_config_fetched.changed
  delegate_to: localhost
  block:
    - name: Create working copy of kube_config
      ansible.builtin.copy:
        src: '/sops/{{ cluster_name }}/kube_config.orig'
        dest: '/sops/{{ cluster_name }}/kube_config'

    - name: Update server IP in fetched kube_config
      ansible.builtin.replace:
        path: '/sops/{{ cluster_name }}/kube_config'
        regexp: '127\.0\.0\.1'
        replace: '{{ inventory_hostname }}'

    - name: Rename cluster, context, and user from 'default'
      ansible.builtin.replace:
        path: '/sops/{{ cluster_name }}/kube_config'
        regexp: 'default'
        replace: '{{ cluster_name }}'

    - name: Copy kube_config to kube_config.enc
      ansible.builtin.copy:
        src: '/sops/{{ cluster_name }}/kube_config'
        dest: '/sops/{{ cluster_name }}/kube_config.enc'

    - name: Encrypt kube_config.enc
      ansible.builtin.command: 'sops --config /.sops.yaml encrypt -i /sops/{{ cluster_name }}/kube_config.enc'
