apiVersion: v1
kind: Secret
metadata:
    name: gitlab-agent-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:RE1gAhRq4Ak9gsO9Cb4qyMyhWCjWawuUmGlVU+My3kKvyTm7kXD6i/CM5T2e1Kj6LXYF8q4MpzNWdYPLTLeSd5o=,iv:BWlT2JU4WjLSNo0c70F5ckoajhvjwn0JCYf4kfSubNg=,tag:mCOhuNhbQvhrbJ8AjhYRwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBOMnY1
            UnBWNUwzbWkyY0lCczNnNnZDK084RjFwZjFjcHhMbW9zeklIY1dBCjhOQ2k0NXU4
            Vi9xRm12S3huMTZqd1U5QVVtaGIwbTFsVFlZeHdJN1RUU1UKLS0tIHZIa3Z4RGRS
            dU9seUM0WjQwZmtYSGJsci9nN1pmMXM4TWpRTzVQUUhFTWMKNcJhPneq+dgrmTfJ
            DqwDNjhTnekV2no3VqE0eypHIUTMPOuT1UZRgAl1eQ+NlW5/Bvya7gYUeg39hYI2
            XL+G7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUWd0MGV2Z3ZtakFHemJK
            QmFCb2RrVXVzbWNmQWhlaU9XcWVaVW50NVN3CnVQakxpUXZKNjJPVVdNdGltOXBT
            Zk5aNVB2YnNCRUF5QWFvVC9DYnBieWsKLS0tIHdFYXVXam5OVHZDcUdtQ1EvT0Zu
            UmxieUR0emhsM1ZsaHppWkljOWpwMHMKX4JM+QjoRIc9Lv9yO/To1VpirD0v+7F5
            SfEvV5pzn44wEA4Vf5yvqsv4VweU9zayx2KLjR//54+Frq43pcB3Eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSAyUnk5
            RXp0MXF5SkcrYkIydHFDSy9NWTBaWHJ5bGVKVkFnSHBjYm5hclhnCmgxTy9sbmVS
            SVhVdkRmenVYM1kwMFE5emRNekliWDhwT3VEcnhyK3N3NU0KLS0tIHpzOUR2OVZR
            R05KWlZyL0Zqd1J3dnY0dTM4MXQ4U1AzT3Q2UUU4OVhuTUUKRetCTm95uqpkic6Q
            NirHWaJExgNuQ9hCwcq5dSPP3YKCwxOSBL6uV1zA+CTnpFQWJJpRgxlJDzY77S9R
            VxqW8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVWVxb1I0UTRNL3hqeUVQ
            WVZ5aE9YQnlkTTdCcDE2TVd2K1dkUVl4ZkZJCm9QaXZuT0d4WVIvcTkxYkMyVXpr
            ejJoYmNkVFlEQkdiUUhCMllVbnI1cEUKLS0tIDBzYnlUYUtTWFdQVlhkeGZPdlA1
            M2dSWjNxSTBxSzMrb0hQU2RLSjVkeWMKNJjxvSAvhPMDtUgSchoxgCPrIWf6pNr6
            XFqrGLBSbqlJlCYhf/jyYhI79i2I9YQ3NliJ7IM7sBTt2qRxnNsxpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T00:35:13Z"
    mac: ENC[AES256_GCM,data:f0IWRSYQJj4xIYk6w413xp2GPWTpi64wqRh3+xH8WJ7BFcm/RjKGvymisQDiWTbKWibV/4Id7FFcUl3ApsJaEg/Lgniu9Lw1v9AuEX9U2AFbDPfF/6vaPGJmuFo2ccqXJGkEXWCAqJlnEne26rt4/LZazrH/nvaAetWM14Vp+20=,iv:bQFqEACWE81gQhZvB1RxkrSFil+O6b69hKWlazdUvY0=,tag:RTGtsQSgShbR+wFcVO095A==,type:str]
    version: 3.13.1
