apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:qIMfBiSJD7HW5fveuYd3t9vc5FAR1KJDujORu3ypsuXx6wrBe595d6v1R3U=,iv:uikbX1kWEuN/XWzHI2+EDiiEhRQ6j0+LDxuDQNqtj84=,tag:SVqjQeMdpvxqUpkHc15aRg==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:9//Tz+3epS41C8NOzzXA30tzA+nw8Lis+7kU9h48DN7UDXfymsetdAw=,iv:pbueGMIdjzPe0fcMov9jZYFAXI2sEEedtKBb1vAvHRc=,tag:jPGffdR12Xi4MgScMuSllw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBReDlr
            Y0U1Q3FncS9SaVdoR21EL3doa3R0Zy9Eb21JYVpDZTRRR05SK25VCkVRcG90WVhm
            SzFOb3YrZjVqdmNTRmdraGxCaVdGWGZkME5KT0VBTFZEYVUKLS0tIHJqV2FZakJz
            ZVByZlJRSlJmMzc4cHVUTitXMDBMZzFwcGM4bldhekwxRlkKktIgull7sCYycyqR
            tGSfvOS43Pcyn6zCDZR38z9oglrophejsluQr4kXmP84ntaoSdnwIp5swXkUOoWo
            INCoHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQW1SM0VCMjJvQ1IvOHJw
            Z1BrY1VHSXNJZEp5NDc5SVhoaENhRXllY2dJCmFFZlpWZEhOd0ZFTmpHZEk1T1RU
            T1VkTVhtSG5nekQyeGxBOVlBYzNqYm8KLS0tIHNnS0NFVTc4V3kyd1hKQzdCbjNr
            djZSM3lqdjJFNUMxYlZvUWpHQXNrRTgKCzC2aE6ep7vXygALccLRHAfLS1ZBq1lh
            pHpqlAvsG4HvlBdjxKjTXVF82eb1Syjp6Rd1RwFWaj4NmfVfxWr7TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBnaVRr
            eTJ0LzNtMkc5QWtRbFNwZTdJbklIb043V1dPdzNFNVh1Y0VkSnhjCmpiVWZYRUpt
            Yyt6QkJUUDREdmNoNEUybFJUZERCNDdxVzViQUxmeW1RTVUKLS0tIHByUkpVY29l
            c0xNeTdlZlVILzNaNkhKQko4T0x2NWNlaWdERU1lOWtVU1kK3+10Q8I3mUxSnlN2
            tV3HCJJFzdB14EuRk/SAT3qLFZo85gToSsg+qOk1G3LF1U0sqrwq4OKBKAevSCIf
            jd+Egw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjBtRXZUNURRL2V5WUZF
            RFcxYVBFUmxUdFNxZ2t5di9kZU4zejBjTlI0CisyYkVIS3ZMbXdwQnBFR3ZiN1h5
            VVVGcytjQUtuN080WjVaUVUybHRjTlUKLS0tIGwxc0JLeVRqNzNHM0p0cy9YNnNX
            cjdMWis4c20vWW5oQUFZaVZLVW9UbUkKn8XnuujjvoFAUTFGWvAU6KugL5NZz40/
            jhRgbPUKThg9xaxS+96HkuzrvMr5Hdxji7zYakirmpmv49rt1msbAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzp73yjss0c5gap9k5ye96cl7z86affv86209xllpuc3n896hces8mhtmx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T20:04:17Z"
    mac: ENC[AES256_GCM,data:oeZijkukcKssi0w45umdty4X3SBsmxaiQsqYVoVAgdA+T5ta9IEOpsyDs8vvNGLr0ml+9Jj3UaIYqGhuQuT+COUrqRpCwlbsSxDjFLDE2hZIY0q2KIrZUtPNuALKu2N8EEB/9rK8cpYFobWR79Hh80tBvndS9FvudK5YO9zBOS0=,iv:9UlMGPAYvysBdhIay3DeUa/N863u0yGMFBhPH05Uyb8=,tag:PZliEis8UfYyDvgbs+kzBQ==,type:str]
    version: 3.13.1
