apiVersion: v1
kind: Secret
metadata:
    name: flux-sops
    namespace: flux-system
type: Opaque
stringData:
    age_key: ENC[AES256_GCM,data:b7g7a48iyEvj3FordXxMXq5xIUQglvTByZd/94O7NOJODJwiyTU746NibM4SplVXUyB2qyk2of/3NGkgpAtCMGNA02feecug7SAhOPkO8yypNDq5sR9z/sNnqCdPxPQ8aM/nvFaJTWgCWFZuCjefr25cxpr7wEyGgU2yO6riXtGJyRGiO6o4H7cEWclceMaoii2M83EP9wrxenQ1BK0Ghz6pfIlt7cZqAZETlY0g63mpmypHTtq00lPZyEed,iv:ryX/mmTVlx8snliO3/i2OzjTgZCSX+e4UMfbkQ8T1HQ=,tag:EW0Id6WCqeernlFei1O6/g==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSArdmpD
            ZzlaMmpLM3B3M2lhcWU3UU9Mc1hpQk1oNVl4OThMRHVmZC9ubVN3Cm1FaGZLRW14
            SVp1R0RBTUVnVzhXODZhSDVJUzlIQVFQNXZaditkdjIxRncKLS0tIDhrRHdpOUJj
            SU0zd0k0Rm15emRKSWdVSnBpMFdNSHE1WHZlZDUyODA1V3cKDSHP5wtRZknZDrpk
            4mVshNT4Va6l7s0CWPMWwaxJ3m3cEXjkhK/wUrwBGupQLxe3rrPj3DqMT2UAcDDd
            qb8MEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd1ZyS3o2S05UL0ZYQ0VG
            UDlMQ3R3ZG9oQS95MTcySzRKNDQrS2lXQ0VFCllrMUlrYmJLNXR4bEtsRnBIVlF2
            aHh1TjBVeW1wOTQ2U2RmeFZNcG1nckUKLS0tIFpqQURXeGQxSHRvUzYwZ0ttbjNi
            eHlWcXNzTTltaFJIZjQrZHloWSttY1EKR3PAK2SmckEXaOZuV5G66x7znVsxOhyg
            /x6JN3TI1V5om/SY1sY7ZHmdwLFddNCA35XnlgSbcvAz1czp5LVFdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T01:10:35Z"
    mac: ENC[AES256_GCM,data:VeH0Cg5y/kbwKybiH0h+cjHabaJ2a6m7uoohTUjpwhwJgeLiHDyBfArjnDc4z9YneqR06CnIh3VeUuSm2wwbggOcmtC6dSEp37FzsBvHSF9u2Ex9dGRRzz3A5SqcWn1nijsn5Hp9ITPQCywFAtnZqATus2EMybXa+OstwYLOTj0=,iv:Fz7qDFxJprTjcKFtn5PIDpBJSKlPuFj9LRzKuOAI0U0=,tag:Us1WEpgXRtT/9o+QxwclIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
