apiVersion: v1
kind: Secret
metadata:
    name: flux-sops
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:5D9/9/gtVx8ip/HEAiRdtRbWf3ymvnxKjIlfiHKFLcOiduJPGhvtN7FFEDEYPklDryxiwKBGYDigoZ8Ts3jW7aMGoUF8UmJwpTM=,iv:OzgtBoPaTqVFVllhOBtMeMImr6tcr9LCibSEO/4Urxc=,tag:ePeja5nEuJe9/7GBDBfBbQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSB1WFJX
            M0tjY2lHd2FQVUVvQm4vTC9Ea0RIbXdNN2FQREdZdVNqcCtVL1FNCnlZZEZHMHg5
            WElocVV3bDVwOFdBQ1ZHS3ZDTnlJV3BpUDdLRnY3WVpnZTAKLS0tIGNXTFRsR3Rh
            U1pndlc1ekw0TWo3V0d0bHdNQXVaOURpUnN5VUpRbG1ZUEEK4U78rsPxSWEe9iZi
            zdSpGn00LrqWewzyumWc/mbO9IeajgTtR6iAR0b7CBJmSkugeZYiOuO26zYMrnRk
            9Pj3xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNVlLSytScUt4c05nMWFp
            Q0RBbDBMbEM0THN3Q0ZMb3kwckxtTEJzOUYwCkxOajU1L0JhekozeVR6RmtSRVdK
            bzAzOHdoSWR2RTdPMTdWYzgrSW9wdDAKLS0tIDYyQzhZdjE0WlYvMVlYTzY1djFU
            Zks1VVgrWGl6bWtqVkhINTM3ZGNTUDAKscw6h94cnPmN5aW/VThTfXkYuexfZUho
            MjqeUGmJ5UqD/BbzyikBYujuiZ6EC/iaAxnZzYvqrjVtt1HNI/u2DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T13:15:21Z"
    mac: ENC[AES256_GCM,data:4i7pd3f4q0Qrf4fZrIYP0NMrQxGqyvQ0UwQEOWBLrxr0YWdJi00c3jf2bUMhkYHMRZCMnEH1bMWYRyL80sl7BvptVBJNcOPkz1LDz2Leaymdec7trAPkugBiv9FBGxJz81ATJL+aozIHuxs7kwm4pcK6jRyII4eVcTfgQLJhKyI=,iv:MZEeZiZSk9w8KcvXrovp+bLhWInQtEaz74d+nrOzp/s=,tag:ntrm7Ng3smfGdS7/1jiUnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
