apiVersion: seaweed.seaweedfs.com/v1
kind: ResourceReferenceGrant
metadata:
  name: allow-s3
spec:
  from:
    - group: seaweed.seaweedfs.com
      kind: Bucket
      namespace: s3
    - group: seaweed.seaweedfs.com
      kind: S3Identity
      namespace: s3
    - group: seaweed.seaweedfs.com
      kind: S3Credentials
      namespace: s3
    - group: seaweed.seaweedfs.com
      kind: S3Policy
      namespace: s3
    - group: seaweed.seaweedfs.com
      kind: S3PolicyBinding
      namespace: s3
  to:
    - group: seaweed.seaweedfs.com
      kind: Seaweed
      name: seaweed
