apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
spec:
  image: chrislusf/seaweedfs:4.44@sha256:e67e8c385484120b78bff47ba5f4debbca47fbd27ed1a39f016f47e8baea615b
  master:
    replicas: 1
  #    persistence:
  #      enabled: true
  #      resources:
  #        requests:
  #          storage: "1Gi"
  volume:
    replicas: 1
    requests:
      storage: 100Gi
  filer:
    replicas: 1
    persistence:
      enabled: true
      resources:
        requests:
          storage: "1Gi"
  s3:
    replicas: 1
