apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
spec:
  image: chrislusf/seaweedfs:4.47@sha256:ce9e796f1fe6f06968f4c04bdaf8f678dad9c8acdfef3d244133d71bfa6bf882
  master:
    replicas: 1
    volumeSizeLimitMB: 1024
  #    persistence:
  #      enabled: true
  #      resources:
  #        requests:
  #          storage: "1Gi"
  volume:
    replicas: 1
    requests:
      storage: 2Ti
  filer:
    replicas: 1
    persistence:
      enabled: true
      resources:
        requests:
          storage: "1Gi"
  s3:
    replicas: 1
