apiVersion: v1
kind: Secret
metadata:
    name: alloy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7pl7pSfFOiqjVSl552uHewukcNVIjJ7SBeRa83dJJBmUxuELB3k2LTcICH8nCjPSOefCyfgk,iv:lB7Dkwxr80J7at6VXmnEE7zMyrCxqnDyGIeJ5w3vi6U=,tag:UvdiHt6f4drzWXyTh2y9vA==,type:comment]
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:zKhq+eFvw/Pr+vx2xhNwN8RFzujbDYok6wySXdVKVjsH5CzkvThs5Fnpj61Fk68UNx3OyqfJbZ7CukOKOgtpcrQmeZp9pDZ0Llp5rjkj1NxSuCG6lDff9P7yLoKG/mwCTxF7fyUp7dsYJ1+JI7DDDAnPPUjvdsjXQl6RMZp7K8Ym3+FaD6ezb94D3qH/2n/szLaYa4Qs5OmxPRcNqC5O2ZQ6SN0=,iv:IzByXE0u02Qx4WUGiqmagla6RbHkwF4s5QZEQUsy15c=,tag:UBwE56hgSqxSdbLrLfcxjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdkRkorZyBOMnY1
            UnBWNUwzbWkyY0lCczNnNnZDK084RjFwZjFjcHhMbW9zeklIY1dBCjhOQ2k0NXU4
            Vi9xRm12S3huMTZqd1U5QVVtaGIwbTFsVFlZeHdJN1RUU1UKLS0tIHZIa3Z4RGRS
            dU9seUM0WjQwZmtYSGJsci9nN1pmMXM4TWpRTzVQUUhFTWMKNcJhPneq+dgrmTfJ
            DqwDNjhTnekV2no3VqE0eypHIUTMPOuT1UZRgAl1eQ+NlW5/Bvya7gYUeg39hYI2
            XL+G7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYine9qQWjvBhbxoEP5OFz7bWzuMwUZVPR+7VgfZd1X
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUWd0MGV2Z3ZtakFHemJK
            QmFCb2RrVXVzbWNmQWhlaU9XcWVaVW50NVN3CnVQakxpUXZKNjJPVVdNdGltOXBT
            Zk5aNVB2YnNCRUF5QWFvVC9DYnBieWsKLS0tIHdFYXVXam5OVHZDcUdtQ1EvT0Zu
            UmxieUR0emhsM1ZsaHppWkljOWpwMHMKX4JM+QjoRIc9Lv9yO/To1VpirD0v+7F5
            SfEvV5pzn44wEA4Vf5yvqsv4VweU9zayx2KLjR//54+Frq43pcB3Eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSAyUnk5
            RXp0MXF5SkcrYkIydHFDSy9NWTBaWHJ5bGVKVkFnSHBjYm5hclhnCmgxTy9sbmVS
            SVhVdkRmenVYM1kwMFE5emRNekliWDhwT3VEcnhyK3N3NU0KLS0tIHpzOUR2OVZR
            R05KWlZyL0Zqd1J3dnY0dTM4MXQ4U1AzT3Q2UUU4OVhuTUUKRetCTm95uqpkic6Q
            NirHWaJExgNuQ9hCwcq5dSPP3YKCwxOSBL6uV1zA+CTnpFQWJJpRgxlJDzY77S9R
            VxqW8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVWVxb1I0UTRNL3hqeUVQ
            WVZ5aE9YQnlkTTdCcDE2TVd2K1dkUVl4ZkZJCm9QaXZuT0d4WVIvcTkxYkMyVXpr
            ejJoYmNkVFlEQkdiUUhCMllVbnI1cEUKLS0tIDBzYnlUYUtTWFdQVlhkeGZPdlA1
            M2dSWjNxSTBxSzMrb0hQU2RLSjVkeWMKNJjxvSAvhPMDtUgSchoxgCPrIWf6pNr6
            XFqrGLBSbqlJlCYhf/jyYhI79i2I9YQ3NliJ7IM7sBTt2qRxnNsxpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dqkegdud54tzus44czqltxukjuumefejyhn5zlzxqmyuvnnj4d3qte4u0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T22:27:54Z"
    mac: ENC[AES256_GCM,data:huTriZxwAchUSKyKdJPjrbtVYsoMcSE4tWoZzz/9+uzuqwsbsHvz8Wv/cdTZqleQtkjLw2j4bgRTcp7E+DAfy8azlrQig6ikMsrnDMFUDM2BOhaFOOgwG8QcBMLcwzBhDkujQemJiWOPQi70LLYwsAXlKPS1cY3g7/Zuqy3SvYQ=,iv:glcjAS8Z620XJeHwRe+y5feSggwDl89zxwCtkzouB1o=,tag:aHkWR2/k9co6DmV3vHMXjg==,type:str]
    version: 3.13.1
