---
- name: Restart rootless container - {{ service }}
  become: true
  become_user: '{{ service }}'
  become_method: community.general.machinectl
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: restarted
    scope: user
  listen: Restart rootless container

- name: Restart rootful container - {{ service }}
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: '{{ service }}.service'
    state: restarted
    scope: user
  listen: Restart rootful container
