apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: homelab-creds
spec:
  seaweedRef:
    name: seaweed
    namespace: seaweedfs-operator
  identityRef:
    name: homelab
  secretRef:
    name: homelab-s3-credentials
